"""
Config drift detection (G-A4)
==============================
Compares the *intended* device configs (Jinja2-generated by the frontend's
`lib/configgen.ts`, sent as `{hostname: config_text}`) against the latest
*running-config* backups written by `nornir_tasks.run_pre_checks()` to
`BACKUP_DIR/{deployment_id}/{hostname}.cfg`.

This is a text-level diff of "what we intended to push" vs "what is actually
running" — distinct from `telemetry/drift_detector.py`, which compares the
design intent against live gNMI *metrics*.
"""

from __future__ import annotations

import difflib
import os
from pathlib import Path
import re
from typing import Any

BACKUP_DIR = Path(os.environ.get("BACKUP_DIR", "/tmp/netdesign_backups"))


def _normalize(text: str) -> list[str]:
    """Strip trailing whitespace and drop blank lines for a stable diff."""
    return [line.rstrip() for line in text.splitlines() if line.strip()]


def diff_configs(intended: str, running: str) -> dict[str, Any]:
    """
    Unified diff between intended and running config text.

    Returns:
        {
          "has_drift": bool,
          "added":   list[str]  — lines present in running but not intended
          "removed": list[str]  — lines present in intended but not running
          "unified_diff": str   — standard unified diff (intended -> running)
        }
    """
    intended_lines = _normalize(intended)
    running_lines  = _normalize(running)

    if intended_lines == running_lines:
        return {"has_drift": False, "added": [], "removed": [], "unified_diff": ""}

    diff = list(difflib.unified_diff(
        intended_lines, running_lines,
        fromfile="intended", tofile="running",
        lineterm="",
    ))

    added   = [l[1:] for l in diff if l.startswith("+") and not l.startswith("+++")]
    removed = [l[1:] for l in diff if l.startswith("-") and not l.startswith("---")]

    return {
        "has_drift": True,
        "added": added,
        "removed": removed,
        "unified_diff": "\n".join(diff),
    }


def latest_backup_dir() -> Path | None:
    """Most recently modified deployment subdirectory under BACKUP_DIR."""
    if not BACKUP_DIR.exists():
        return None
    subdirs = [d for d in BACKUP_DIR.iterdir() if d.is_dir()]
    if not subdirs:
        return None
    return max(subdirs, key=lambda d: d.stat().st_mtime)


def get_running_config(hostname: str, deployment_id: str | None = None) -> str | None:
    """
    Read the backed-up running-config for `hostname`.

    If `deployment_id` is given, look in `BACKUP_DIR/{deployment_id}/`.
    Otherwise fall back to the most recently modified deployment directory.
    Returns None if no backup file exists.
    """
    if deployment_id:
        backup_dir = BACKUP_DIR / deployment_id
    else:
        backup_dir = latest_backup_dir()
        if backup_dir is None:
            return None

    cfg_file = backup_dir / f"{hostname}.cfg"
    if not cfg_file.exists():
        return None
    return cfg_file.read_text()


def check_config_drift(
    configs: dict[str, str],
    deployment_id: str | None = None,
) -> dict[str, Any]:
    """
    Compare each intended config against its running-config backup.

    Returns:
        {
          "devices": [
            {
              "hostname": str,
              "has_drift": bool,
              "added": list[str],
              "removed": list[str],
              "unified_diff": str,
              "no_baseline": bool,   # True if no running-config backup found
            },
            ...
          ],
          "drift_count": int,   # devices with has_drift == True
          "device_count": int,
        }
    """
    devices: list[dict[str, Any]] = []
    drift_count = 0

    for hostname, intended in configs.items():
        running = get_running_config(hostname, deployment_id)

        if running is None:
            devices.append({
                "hostname": hostname,
                "has_drift": False,
                "added": [],
                "removed": [],
                "unified_diff": "",
                "no_baseline": True,
            })
            continue

        result = diff_configs(intended, running)
        if result["has_drift"]:
            drift_count += 1

        devices.append({
            "hostname": hostname,
            "no_baseline": False,
            **result,
        })

    return {
        "devices": devices,
        "drift_count": drift_count,
        "device_count": len(devices),
    }


# ---------------------------------------------------------------------------
# G-A16: inline remediation — turn a detected drift into the CLI commands that
# bring the *running* config back in line with the *intended* config.
#
# Drift semantics (see diff_configs):
#   removed = lines in INTENDED but missing from RUNNING → re-apply them
#   added   = lines in RUNNING but absent from INTENDED  → negate/remove them
#
# This generates a reviewable command block per device; it does NOT push to any
# device. Applying remediation to live equipment stays a deliberate, separate
# human action.
# ---------------------------------------------------------------------------


try:
    from change_update import cli_family
except ImportError:  # pragma: no cover - package-relative import
    from .change_update import cli_family  # type: ignore

#: Families whose "undo this line" form is mechanically derivable from the line.
#:
#: EXOS and FortiOS are deliberately absent (AL1). EXOS negation is per-command
#: (``unconfigure`` / ``disable`` / ``delete`` depending on what the line
#: configured) and FortiOS needs the enclosing ``config`` path to emit
#: ``unset``, so neither can be produced from an arbitrary diff line. Emitting a
#: plausible ``unconfigure <line>`` would be exactly the guess AG5 stopped
#: making — worse than saying so, because it looks runnable.
DERIVABLE_FAMILIES: frozenset[str] = frozenset({"ios", "junos", "nokia", "panos", "nvue"})

UNSUPPORTED_NOTE: dict[str, str] = {
    "exos": (
        "EXOS negation is per-command (unconfigure / disable / delete depending on what "
        "the line set), so it cannot be derived from a diff line. Review each line against "
        "the EXOS command reference."
    ),
    "fortios": (
        "FortiOS needs the enclosing `config` path to emit `unset`, which a diff line does "
        "not carry. Review each line inside its `config … end` block."
    ),
}


def remediation_family(token: str) -> str:
    """Resolve a dialect from EITHER a catalogue vendor name or a platform/NOS
    string — both are live inputs.

    The UI passes ``d.vendor`` ("Nokia"), while this module's field is literally
    named ``platform`` and receives NOS tokens ("juniper-junos", "ios-xe").
    ``cli_family`` exact-matches vendor names, so resolving a NOS token through
    it alone silently returned ``ios`` — which is how the first draft of AL1
    broke Juniper, caught by an existing test.

    Must stay identical to frontend ``lib/drift-remediation.ts::remediationFamily``;
    ``test_drift_remediation_parity.py`` asserts it.
    """
    via_vendor = cli_family(token)
    if via_vendor != "ios":
        return via_vendor              # matched a catalogue vendor
    t = token.lower()
    if re.search(r"jun", t):
        return "junos"
    if re.search(r"srl|srlinux|nokia", t):
        return "nokia"
    if re.search(r"cumulus|nvue|nvidia", t):
        return "nvue"
    if re.search(r"exos|extreme", t):
        return "exos"
    if re.search(r"forti", t):
        return "fortios"
    if re.search(r"pan-?os|palo", t):
        return "panos"
    # ios-xe, iosxr, nxos, eos, dellos10, arubaoscx and anything unknown.
    return "ios"


def _negate_cisco(line: str) -> str:
    """Negate a Cisco/Arista-style config line, preserving indentation."""
    stripped = line.lstrip()
    indent = line[: len(line) - len(stripped)]
    if stripped.startswith("no "):
        return f"{indent}{stripped[3:]}"   # already a negation → re-enable
    return f"{indent}no {stripped}"


def _restore_line(family: str, line: str) -> str:
    """Re-apply an intended line that drift removed from the running config."""
    s = line.strip()
    if family in ("junos", "panos", "nokia"):
        if s.startswith("set "):
            return s
        if s.startswith("delete "):
            return "set " + s[len("delete "):]
        return f"set {s}"
    if family == "nvue":
        if s.startswith("nv set "):
            return s
        if s.startswith("nv unset "):
            return "nv set " + s[len("nv unset "):]
        return f"nv set {s}"
    return line   # ios: the intended line is simply re-applied


def _negate_line(family: str, line: str) -> str:
    """Undo a line that drift added to the running config."""
    s = line.strip()
    if family in ("junos", "panos", "nokia"):
        if s.startswith("set "):
            return "delete " + s[len("set "):]
        if s.startswith("delete "):
            return s
        return f"delete {s}"
    if family == "nvue":
        if s.startswith("nv set "):
            return "nv unset " + s[len("nv set "):]
        if s.startswith("nv unset "):
            return s
        return f"nv unset {s}"
    return _negate_cisco(line)


def generate_remediation(
    hostname: str,
    platform: str,
    added: list[str],
    removed: list[str],
) -> dict[str, Any]:
    """
    Build the remediation command list for a single device's drift.

    Returns:
        {
          "hostname": str,
          "platform": str,
          "commands": list[str],   # ordered: restore missing, then prune extra
          "command_count": int,
        }
    """
    # AL1 — dialect from the shared cli_family map (AG9) rather than a binary
    # Junos-or-Cisco split that handed 8 of 10 vendors `no <line>`.
    family = remediation_family(platform)

    if family not in DERIVABLE_FAMILIES:
        return {
            "hostname": hostname,
            "platform": platform,
            "commands": [],
            "command_count": 0,
            "supported": False,
            "note": UNSUPPORTED_NOTE.get(
                family, f"No remediation dialect for {platform}; review the diff manually."
            ),
        }

    commands: list[str] = []

    # 1. Restore intended lines that are missing from the running config.
    for line in removed:
        commands.append(_restore_line(family, line))

    # 2. Remove extra lines that are on the device but not intended.
    for line in added:
        commands.append(_negate_line(family, line))

    return {
        "hostname": hostname,
        "platform": platform,
        "commands": commands,
        "command_count": len(commands),
        "supported": True,
        "note": "",
    }


def build_remediation(devices: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Build remediation for a batch of drifted devices.

    Each device dict: {hostname, platform, added: list[str], removed: list[str]}.
    Returns: {"devices": [generate_remediation(...), ...]}.
    """
    out = [
        generate_remediation(
            d.get("hostname", ""),
            d.get("platform", "ios-xe"),
            d.get("added", []),
            d.get("removed", []),
        )
        for d in devices
    ]
    return {"devices": out}
