"""
Config drift detection (G-A4)
==============================
Compares the *intended* device configs (Jinja2-generated by the frontend's
`lib/configgen.ts`, sent as `{hostname: config_text}`) against the latest
*running-config* backups written by `nornir_tasks.run_pre_checks()` to
`BACKUP_DIR/{deployment_id}/{hostname}.cfg`.

This is a text-level diff of "what we intended to push" vs "what is actually
running" — distinct from `telemetry/drift_detector.py`, which compares the
design intent against live gNMI *metrics*.
"""

from __future__ import annotations

import difflib
import os
from pathlib import Path
from typing import Any

BACKUP_DIR = Path(os.environ.get("BACKUP_DIR", "/tmp/netdesign_backups"))


def _normalize(text: str) -> list[str]:
    """Strip trailing whitespace and drop blank lines for a stable diff."""
    return [line.rstrip() for line in text.splitlines() if line.strip()]


def diff_configs(intended: str, running: str) -> dict[str, Any]:
    """
    Unified diff between intended and running config text.

    Returns:
        {
          "has_drift": bool,
          "added":   list[str]  — lines present in running but not intended
          "removed": list[str]  — lines present in intended but not running
          "unified_diff": str   — standard unified diff (intended -> running)
        }
    """
    intended_lines = _normalize(intended)
    running_lines  = _normalize(running)

    if intended_lines == running_lines:
        return {"has_drift": False, "added": [], "removed": [], "unified_diff": ""}

    diff = list(difflib.unified_diff(
        intended_lines, running_lines,
        fromfile="intended", tofile="running",
        lineterm="",
    ))

    added   = [l[1:] for l in diff if l.startswith("+") and not l.startswith("+++")]
    removed = [l[1:] for l in diff if l.startswith("-") and not l.startswith("---")]

    return {
        "has_drift": True,
        "added": added,
        "removed": removed,
        "unified_diff": "\n".join(diff),
    }


def latest_backup_dir() -> Path | None:
    """Most recently modified deployment subdirectory under BACKUP_DIR."""
    if not BACKUP_DIR.exists():
        return None
    subdirs = [d for d in BACKUP_DIR.iterdir() if d.is_dir()]
    if not subdirs:
        return None
    return max(subdirs, key=lambda d: d.stat().st_mtime)


def get_running_config(hostname: str, deployment_id: str | None = None) -> str | None:
    """
    Read the backed-up running-config for `hostname`.

    If `deployment_id` is given, look in `BACKUP_DIR/{deployment_id}/`.
    Otherwise fall back to the most recently modified deployment directory.
    Returns None if no backup file exists.
    """
    if deployment_id:
        backup_dir = BACKUP_DIR / deployment_id
    else:
        backup_dir = latest_backup_dir()
        if backup_dir is None:
            return None

    cfg_file = backup_dir / f"{hostname}.cfg"
    if not cfg_file.exists():
        return None
    return cfg_file.read_text()


def check_config_drift(
    configs: dict[str, str],
    deployment_id: str | None = None,
) -> dict[str, Any]:
    """
    Compare each intended config against its running-config backup.

    Returns:
        {
          "devices": [
            {
              "hostname": str,
              "has_drift": bool,
              "added": list[str],
              "removed": list[str],
              "unified_diff": str,
              "no_baseline": bool,   # True if no running-config backup found
            },
            ...
          ],
          "drift_count": int,   # devices with has_drift == True
          "device_count": int,
        }
    """
    devices: list[dict[str, Any]] = []
    drift_count = 0

    for hostname, intended in configs.items():
        running = get_running_config(hostname, deployment_id)

        if running is None:
            devices.append({
                "hostname": hostname,
                "has_drift": False,
                "added": [],
                "removed": [],
                "unified_diff": "",
                "no_baseline": True,
            })
            continue

        result = diff_configs(intended, running)
        if result["has_drift"]:
            drift_count += 1

        devices.append({
            "hostname": hostname,
            "no_baseline": False,
            **result,
        })

    return {
        "devices": devices,
        "drift_count": drift_count,
        "device_count": len(devices),
    }


# ---------------------------------------------------------------------------
# G-A16: inline remediation — turn a detected drift into the CLI commands that
# bring the *running* config back in line with the *intended* config.
#
# Drift semantics (see diff_configs):
#   removed = lines in INTENDED but missing from RUNNING → re-apply them
#   added   = lines in RUNNING but absent from INTENDED  → negate/remove them
#
# This generates a reviewable command block per device; it does NOT push to any
# device. Applying remediation to live equipment stays a deliberate, separate
# human action.
# ---------------------------------------------------------------------------


def _is_junos(platform: str) -> bool:
    return "jun" in platform.lower()


def _negate_cisco(line: str) -> str:
    """Negate a Cisco/Arista-style config line, preserving indentation."""
    stripped = line.lstrip()
    indent = line[: len(line) - len(stripped)]
    if stripped.startswith("no "):
        return f"{indent}{stripped[3:]}"   # already a negation → re-enable
    return f"{indent}no {stripped}"


def _restore_junos(line: str) -> str:
    """Re-apply an intended Junos line as a `set` statement."""
    s = line.strip()
    if s.startswith("set "):
        return s
    if s.startswith("delete "):
        return "set " + s[len("delete "):]
    return f"set {s}"


def _negate_junos(line: str) -> str:
    """Remove an extra Junos line via a `delete` statement."""
    s = line.strip()
    if s.startswith("set "):
        return "delete " + s[len("set "):]
    if s.startswith("delete "):
        return s
    return f"delete {s}"


def generate_remediation(
    hostname: str,
    platform: str,
    added: list[str],
    removed: list[str],
) -> dict[str, Any]:
    """
    Build the remediation command list for a single device's drift.

    Returns:
        {
          "hostname": str,
          "platform": str,
          "commands": list[str],   # ordered: restore missing, then prune extra
          "command_count": int,
        }
    """
    junos = _is_junos(platform)
    commands: list[str] = []

    # 1. Restore intended lines that are missing from the running config.
    for line in removed:
        commands.append(_restore_junos(line) if junos else line)

    # 2. Remove extra lines that are on the device but not intended.
    for line in added:
        commands.append(_negate_junos(line) if junos else _negate_cisco(line))

    return {
        "hostname": hostname,
        "platform": platform,
        "commands": commands,
        "command_count": len(commands),
    }


def build_remediation(devices: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Build remediation for a batch of drifted devices.

    Each device dict: {hostname, platform, added: list[str], removed: list[str]}.
    Returns: {"devices": [generate_remediation(...), ...]}.
    """
    out = [
        generate_remediation(
            d.get("hostname", ""),
            d.get("platform", "ios-xe"),
            d.get("added", []),
            d.get("removed", []),
        )
        for d in devices
    ]
    return {"devices": out}
