"""
Custom Policy Generator
========================
Allows users to define explicit network parameters and generate
production-ready device configs for multiple platforms.

Classes
-------
CustomPolicyInput  — Pydantic v2 input model with full validation
CustomPolicy       — Generator class; returns {device_hostname: config_text}

Supported platforms:
  cisco_ios   — IOS / IOS-XE (classic syntax)
  cisco_nxos  — NX-OS (data-center OS)
  juniper_junos — Junos (set-style commands)
  arista_eos  — Arista EOS
"""
from __future__ import annotations

import ipaddress
from typing import Literal, Optional

from jinja2 import Environment, BaseLoader
from pydantic import BaseModel, Field, field_validator


# ── Sub-models ───────────────────────────────────────────────────────────────

class VlanEntry(BaseModel):
    id: int = Field(..., ge=1, le=4094)
    name: str
    description: Optional[str] = None


class PeerGroup(BaseModel):
    name: str
    remote_as: int
    update_source: str = "Loopback0"
    peer_ips: list[str] = []


class BgpConfig(BaseModel):
    asn: int = Field(..., ge=1, le=4294967295)
    router_id: str
    peer_groups: list[PeerGroup] = []


class PrefixList(BaseModel):
    name: str
    action: Literal["permit", "deny"]
    prefixes: list[str] = []


class InterfaceConfig(BaseModel):
    name: str
    ip_address: str
    description: str = ""
    vlan_id: Optional[int] = None


# ── Top-level input model ─────────────────────────────────────────────────────

class CustomPolicyInput(BaseModel):
    name: str
    device_type: Literal["cisco_ios", "cisco_nxos", "juniper_junos", "arista_eos"]
    vlans: list[VlanEntry] = []
    bgp: Optional[BgpConfig] = None
    prefix_lists: list[PrefixList] = []
    interfaces: list[InterfaceConfig] = []
    ntp_servers: list[str] = []
    dns_servers: list[str] = []
    banner: Optional[str] = None

    @field_validator("name")
    @classmethod
    def name_not_empty(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("policy name must not be empty")
        return v


# ── Jinja2 templates per platform ────────────────────────────────────────────

_CISCO_IOS_TEMPLATE = """\
! ============================================================
! Custom Policy: {{ policy.name }}
! Platform: Cisco IOS / IOS-XE
! Generated by NetDesign AI
! ============================================================
!
{% if policy.banner %}
banner motd ^
{{ policy.banner }}
^
!
{% endif %}
{% if policy.vlans %}
! --- VLANs ---
{% for v in policy.vlans %}
vlan {{ v.id }}
 name {{ v.name }}
{% if v.description %} ! {{ v.description }}{% endif %}
{% endfor %}
!
{% endif %}
{% if policy.interfaces %}
! --- Interfaces ---
{% for iface in policy.interfaces %}
interface {{ iface.name }}
{% if iface.description %} description {{ iface.description }}{% endif %}
{% if iface.vlan_id %} switchport access vlan {{ iface.vlan_id }}
 switchport mode access{% else %} ip address {{ iface.ip_address }}{% endif %}
 no shutdown
!
{% endfor %}
{% endif %}
{% if policy.prefix_lists %}
! --- Prefix Lists ---
{% for pl in policy.prefix_lists %}
{% for prefix in pl.prefixes %}
ip prefix-list {{ pl.name }} {{ pl.action }} {{ prefix }}
{% endfor %}
{% endfor %}
!
{% endif %}
{% if policy.bgp %}
! --- BGP ---
router bgp {{ policy.bgp.asn }}
 bgp router-id {{ policy.bgp.router_id }}
 bgp log-neighbor-changes
{% for pg in policy.bgp.peer_groups %}
 neighbor {{ pg.name }} peer-group
 neighbor {{ pg.name }} remote-as {{ pg.remote_as }}
 neighbor {{ pg.name }} update-source {{ pg.update_source }}
{% for peer_ip in pg.peer_ips %}
 neighbor {{ peer_ip }} peer-group {{ pg.name }}
{% endfor %}
{% endfor %}
!
{% endif %}
{% if policy.ntp_servers %}
! --- NTP ---
{% for ntp in policy.ntp_servers %}
ntp server {{ ntp }}
{% endfor %}
!
{% endif %}
{% if policy.dns_servers %}
! --- DNS ---
{% for dns in policy.dns_servers %}
ip name-server {{ dns }}
{% endfor %}
!
{% endif %}
end
"""

_CISCO_NXOS_TEMPLATE = """\
! ============================================================
! Custom Policy: {{ policy.name }}
! Platform: Cisco NX-OS
! Generated by NetDesign AI
! ============================================================
!
{% if policy.banner %}
banner motd #
{{ policy.banner }}
#
!
{% endif %}
{% if policy.vlans %}
! --- VLANs ---
{% for v in policy.vlans %}
vlan {{ v.id }}
  name {{ v.name }}
  state active
{% endfor %}
!
{% endif %}
{% if policy.interfaces %}
! --- Interfaces ---
{% for iface in policy.interfaces %}
interface {{ iface.name }}
{% if iface.description %}  description {{ iface.description }}{% endif %}
{% if iface.vlan_id %}  switchport
  switchport mode access
  switchport access vlan {{ iface.vlan_id }}{% else %}  ip address {{ iface.ip_address }}{% endif %}
  no shutdown
!
{% endfor %}
{% endif %}
{% if policy.prefix_lists %}
! --- IP Prefix Lists ---
{% for pl in policy.prefix_lists %}
{% for prefix in pl.prefixes %}
ip prefix-list {{ pl.name }} {{ pl.action }} {{ prefix }}
{% endfor %}
{% endfor %}
!
{% endif %}
{% if policy.bgp %}
! --- BGP ---
router bgp {{ policy.bgp.asn }}
  router-id {{ policy.bgp.router_id }}
  log-neighbor-changes
{% for pg in policy.bgp.peer_groups %}
  neighbor {{ pg.name }}
    remote-as {{ pg.remote_as }}
    update-source {{ pg.update_source }}
{% for peer_ip in pg.peer_ips %}
  neighbor {{ peer_ip }}
    remote-as {{ pg.remote_as }}
    update-source {{ pg.update_source }}
{% endfor %}
{% endfor %}
!
{% endif %}
{% if policy.ntp_servers %}
! --- NTP ---
{% for ntp in policy.ntp_servers %}
ntp server {{ ntp }} use-vrf management
{% endfor %}
!
{% endif %}
{% if policy.dns_servers %}
! --- DNS ---
{% for dns in policy.dns_servers %}
ip name-server {{ dns }}
{% endfor %}
!
{% endif %}
"""

_JUNIPER_JUNOS_TEMPLATE = """\
# ============================================================
# Custom Policy: {{ policy.name }}
# Platform: Juniper Junos
# Generated by NetDesign AI
# ============================================================
#
{% if policy.banner %}
set system login message "{{ policy.banner }}"
#
{% endif %}
{% if policy.vlans %}
# --- VLANs ---
{% for v in policy.vlans %}
set vlans {{ v.name }} vlan-id {{ v.id }}
{% if v.description %}set vlans {{ v.name }} description "{{ v.description }}"{% endif %}
{% endfor %}
#
{% endif %}
{% if policy.interfaces %}
# --- Interfaces ---
{% for iface in policy.interfaces %}
set interfaces {{ iface.name }} description "{{ iface.description }}"
{% if iface.vlan_id %}set interfaces {{ iface.name }} unit 0 family ethernet-switching vlan members {{ iface.vlan_id }}{% else %}{% set parts = iface.ip_address.split('/') %}set interfaces {{ iface.name }} unit 0 family inet address {{ iface.ip_address }}{% endif %}
{% endfor %}
#
{% endif %}
{% if policy.prefix_lists %}
# --- Prefix Lists (policy-options prefix-lists) ---
{% for pl in policy.prefix_lists %}
{% for prefix in pl.prefixes %}
set policy-options prefix-list {{ pl.name }} {{ prefix }}
{% endfor %}
{% endfor %}
#
{% endif %}
{% if policy.bgp %}
# --- BGP ---
set routing-options router-id {{ policy.bgp.router_id }}
set routing-options autonomous-system {{ policy.bgp.asn }}
{% for pg in policy.bgp.peer_groups %}
set protocols bgp group {{ pg.name }} type external
set protocols bgp group {{ pg.name }} peer-as {{ pg.remote_as }}
set protocols bgp group {{ pg.name }} local-address {{ policy.bgp.router_id }}
{% for peer_ip in pg.peer_ips %}
set protocols bgp group {{ pg.name }} neighbor {{ peer_ip }}
{% endfor %}
{% endfor %}
#
{% endif %}
{% if policy.ntp_servers %}
# --- NTP ---
{% for ntp in policy.ntp_servers %}
set system ntp server {{ ntp }}
{% endfor %}
#
{% endif %}
{% if policy.dns_servers %}
# --- DNS ---
{% for dns in policy.dns_servers %}
set system name-server {{ dns }}
{% endfor %}
#
{% endif %}
"""

_ARISTA_EOS_TEMPLATE = """\
! ============================================================
! Custom Policy: {{ policy.name }}
! Platform: Arista EOS
! Generated by NetDesign AI
! ============================================================
!
{% if policy.banner %}
banner motd
{{ policy.banner }}
EOF
!
{% endif %}
{% if policy.vlans %}
! --- VLANs ---
{% for v in policy.vlans %}
vlan {{ v.id }}
   name {{ v.name }}
{% if v.description %}   ! {{ v.description }}{% endif %}
{% endfor %}
!
{% endif %}
{% if policy.interfaces %}
! --- Interfaces ---
{% for iface in policy.interfaces %}
interface {{ iface.name }}
{% if iface.description %}   description {{ iface.description }}{% endif %}
{% if iface.vlan_id %}   switchport mode access
   switchport access vlan {{ iface.vlan_id }}{% else %}   ip address {{ iface.ip_address }}{% endif %}
   no shutdown
!
{% endfor %}
{% endif %}
{% if policy.prefix_lists %}
! --- IP Prefix Lists ---
{% for pl in policy.prefix_lists %}
{% for prefix in pl.prefixes %}
ip prefix-list {{ pl.name }} {{ pl.action }} {{ prefix }}
{% endfor %}
{% endfor %}
!
{% endif %}
{% if policy.bgp %}
! --- BGP ---
router bgp {{ policy.bgp.asn }}
   router-id {{ policy.bgp.router_id }}
   bgp log-neighbor-changes
{% for pg in policy.bgp.peer_groups %}
   neighbor {{ pg.name }} peer group
   neighbor {{ pg.name }} remote-as {{ pg.remote_as }}
   neighbor {{ pg.name }} update-source {{ pg.update_source }}
{% for peer_ip in pg.peer_ips %}
   neighbor {{ peer_ip }} peer group {{ pg.name }}
{% endfor %}
{% endfor %}
!
{% endif %}
{% if policy.ntp_servers %}
! --- NTP ---
{% for ntp in policy.ntp_servers %}
ntp server {{ ntp }}
{% endfor %}
!
{% endif %}
{% if policy.dns_servers %}
! --- DNS ---
{% for dns in policy.dns_servers %}
ip name-server {{ dns }}
{% endfor %}
!
{% endif %}
end
"""

# ── Template registry ─────────────────────────────────────────────────────────

_TEMPLATES: dict[str, str] = {
    "cisco_ios":      _CISCO_IOS_TEMPLATE,
    "cisco_nxos":     _CISCO_NXOS_TEMPLATE,
    "juniper_junos":  _JUNIPER_JUNOS_TEMPLATE,
    "arista_eos":     _ARISTA_EOS_TEMPLATE,
}


# ── Validation helpers ────────────────────────────────────────────────────────

def _is_rfc1918(ip_str: str) -> bool:
    """Return True if the address falls in RFC1918 private space."""
    try:
        addr = ipaddress.ip_address(ip_str)
        return addr.is_private
    except ValueError:
        return False


def _vlans_overlap(vlans: list[VlanEntry]) -> list[str]:
    seen: set[int] = set()
    dupes: list[str] = []
    for v in vlans:
        if v.id in seen:
            dupes.append(str(v.id))
        seen.add(v.id)
    return dupes


def _prefixes_overlap(prefix_lists: list[PrefixList]) -> list[str]:
    """Detect prefix entries that are subnets/supernets of each other."""
    warnings: list[str] = []
    all_nets: list[tuple[str, ipaddress.IPv4Network | ipaddress.IPv6Network]] = []
    for pl in prefix_lists:
        for p in pl.prefixes:
            try:
                net = ipaddress.ip_network(p, strict=False)
                for prev_name, prev_net in all_nets:
                    if net.overlaps(prev_net):
                        warnings.append(
                            f"Prefix {p} in '{pl.name}' overlaps with {str(prev_net)} in '{prev_name}'"
                        )
                all_nets.append((pl.name, net))
            except ValueError:
                warnings.append(f"Invalid prefix: '{p}' in list '{pl.name}'")
    return warnings


# ── Generator class ───────────────────────────────────────────────────────────

class CustomPolicy:
    """Generates device configs from a CustomPolicyInput object."""

    _jinja_env = Environment(loader=BaseLoader(), trim_blocks=True, lstrip_blocks=True)

    def generate(self, policy_input: CustomPolicyInput) -> dict[str, str]:
        """
        Render a config for the specified device_type.

        Returns
        -------
        dict[str, str]
            Keys are device hostnames derived from policy name + device type.
            Values are full config text strings.
        """
        template_src = _TEMPLATES[policy_input.device_type]
        template = self._jinja_env.from_string(template_src)
        config_text = template.render(policy=policy_input)

        # Sanitise device name for use as a key
        safe_name = policy_input.name.replace(" ", "_").replace("/", "-").lower()
        hostname = f"{safe_name}-{policy_input.device_type}"

        return {hostname: config_text}

    @staticmethod
    def validate(policy_input: CustomPolicyInput) -> list[str]:
        """
        Return a list of warning strings (not errors) about the input.
        An empty list means no warnings.
        """
        warnings: list[str] = []

        # VLAN range check (1-4094 is enforced by Pydantic; flag reserved ones)
        for v in policy_input.vlans:
            if v.id in (0, 1, 4094, 4095):
                warnings.append(f"VLAN {v.id} is a reserved VLAN and may not be configurable on all platforms")

        # Duplicate VLANs
        dupes = _vlans_overlap(policy_input.vlans)
        for d in dupes:
            warnings.append(f"Duplicate VLAN ID: {d}")

        # BGP router-id RFC1918 check
        if policy_input.bgp:
            if not _is_rfc1918(policy_input.bgp.router_id):
                warnings.append(
                    f"BGP router-id {policy_input.bgp.router_id} is not an RFC1918 address — "
                    "ensure this is intentional for your topology"
                )
            # Large ASN hint
            if policy_input.bgp.asn > 4200000000:
                warnings.append(f"ASN {policy_input.bgp.asn} is above the IANA private ASN range (64512-65534 / 4200000000-4294967294)")

        # Prefix list overlap check
        warnings.extend(_prefixes_overlap(policy_input.prefix_lists))

        # NTP / DNS count advisory
        if len(policy_input.ntp_servers) == 1:
            warnings.append("Only one NTP server configured — consider adding a second for redundancy")
        if len(policy_input.dns_servers) == 1:
            warnings.append("Only one DNS server configured — consider adding a second for redundancy")

        return warnings
