"""
Jira integration — create issues for change approvals and deployment failures.

Config keys:
  base_url      — https://yourcompany.atlassian.net
  email         — Atlassian account email (for Basic auth)
  api_token     — Atlassian API token
  project_key   — Jira project key (e.g. "NET" or "NETOPS")
  issue_type    — Issue type name (default: "Change Request")
  priority      — Default priority (default: "Medium")
  label         — Label applied to all issues (default: "netdesign-ai")
"""

from __future__ import annotations
import logging
from typing import Any
import httpx

log = logging.getLogger("netdesign.integrations.jira")


async def _get_config(org_id: str) -> dict | None:
    try:
        from db import _SessionLocal
        from models import IntegrationConfig
        from sqlalchemy import select
        if not _SessionLocal:
            return None
        async with _SessionLocal() as s:
            row = await s.execute(
                select(IntegrationConfig).where(
                    IntegrationConfig.org_id == org_id,
                    IntegrationConfig.provider == "jira",
                    IntegrationConfig.enabled == True,
                )
            )
            cfg = row.scalar_one_or_none()
            return cfg.config if cfg else None
    except Exception:
        return None


def _client(cfg: dict) -> httpx.AsyncClient:
    import base64
    token = base64.b64encode(f"{cfg['email']}:{cfg['api_token']}".encode()).decode()
    return httpx.AsyncClient(
        base_url=cfg["base_url"].rstrip("/"),
        headers={
            "Authorization": f"Basic {token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
        timeout=10.0,
    )


async def create_change_issue(approval, design) -> tuple[str, str]:
    """
    Create a Jira issue for the approval.
    Returns (issue_key, issue_url) or ("", "") on failure.
    """
    if not approval.org_id:
        return "", ""
    cfg = await _get_config(approval.org_id)
    if not cfg:
        return "", ""

    design_name = getattr(design, "name", approval.design_id) if design else approval.design_id
    risk_label  = "High" if approval.risk_score >= 75 else "Medium" if approval.risk_score >= 40 else "Low"
    priority    = cfg.get("priority", risk_label)

    description = {
        "type": "doc", "version": 1,
        "content": [
            {"type": "paragraph", "content": [
                {"type": "text", "text": "Automated change request generated by ", "marks": []},
                {"type": "text", "text": "NetDesign AI", "marks": [{"type": "strong"}]},
                {"type": "text", "text": "."},
            ]},
            {"type": "bulletList", "content": [
                {"type": "listItem", "content": [{"type": "paragraph", "content": [
                    {"type": "text", "text": f"Design: {design_name}"}]}]},
                {"type": "listItem", "content": [{"type": "paragraph", "content": [
                    {"type": "text", "text": f"Environment: {approval.environment}"}]}]},
                {"type": "listItem", "content": [{"type": "paragraph", "content": [
                    {"type": "text", "text": f"Risk Score: {approval.risk_score}/100 ({risk_label})"}]}]},
                {"type": "listItem", "content": [{"type": "paragraph", "content": [
                    {"type": "text", "text": f"Devices affected: {approval.device_count}"}]}]},
                {"type": "listItem", "content": [{"type": "paragraph", "content": [
                    {"type": "text", "text": f"Requested by: {approval.requested_by}"}]}]},
            ]},
            *([] if not approval.summary else [
                {"type": "paragraph", "content": [{"type": "text", "text": approval.summary}]}
            ]),
        ],
    }

    payload: dict[str, Any] = {
        "fields": {
            "project":     {"key": cfg["project_key"]},
            "summary":     f"[NetDesign AI] Deploy '{design_name}' → {approval.environment}",
            "description": description,
            "issuetype":   {"name": cfg.get("issue_type", "Change Request")},
            "priority":    {"name": priority},
            "labels":      [cfg.get("label", "netdesign-ai")],
        }
    }

    try:
        async with _client(cfg) as client:
            resp = await client.post("/rest/api/3/issue", json=payload)
            resp.raise_for_status()
            data = resp.json()
            key = data.get("key", "")
            url = f"{cfg['base_url']}/browse/{key}"
            log.info("Jira issue created: %s", key)
            return key, url
    except Exception as exc:
        log.warning("Jira create_change_issue failed: %s", exc)
        return "", ""


async def transition_issue(issue_key: str | None, org_id: str, transition_name: str) -> None:
    """Move a Jira issue to a named transition (e.g. 'Approve', 'Reject', 'Done')."""
    if not issue_key:
        return
    cfg = await _get_config(org_id)
    if not cfg:
        return
    try:
        async with _client(cfg) as client:
            # Fetch available transitions
            r = await client.get(f"/rest/api/3/issue/{issue_key}/transitions")
            r.raise_for_status()
            transitions = r.json().get("transitions", [])
            match = next(
                (t for t in transitions if t["name"].lower() == transition_name.lower()), None
            )
            if not match:
                log.warning("Jira: transition '%s' not found for %s", transition_name, issue_key)
                return
            resp = await client.post(
                f"/rest/api/3/issue/{issue_key}/transitions",
                json={"transition": {"id": match["id"]}},
            )
            resp.raise_for_status()
    except Exception as exc:
        log.warning("Jira transition_issue failed: %s", exc)


async def add_comment(issue_key: str | None, org_id: str, text: str) -> None:
    if not issue_key:
        return
    cfg = await _get_config(org_id)
    if not cfg:
        return
    try:
        body = {"body": {"type": "doc", "version": 1, "content": [
            {"type": "paragraph", "content": [{"type": "text", "text": text}]}
        ]}}
        async with _client(cfg) as client:
            resp = await client.post(f"/rest/api/3/issue/{issue_key}/comment", json=body)
            resp.raise_for_status()
    except Exception as exc:
        log.warning("Jira add_comment failed: %s", exc)
