"""
ServiceNow integration — create and update Change Requests (CHG).

Config keys:
  instance_url    — https://<tenant>.service-now.com
  username        — ServiceNow API user
  password        — ServiceNow API password (or use client_id/client_secret for OAuth)
  assignment_group — sys_id or name of the network team's group (optional)
  category        — Change category (default: "Network")
  cmdb_ci         — CMDB CI sys_id to attach to the change (optional)
"""

from __future__ import annotations
import logging
from typing import Any
import httpx

log = logging.getLogger("netdesign.integrations.servicenow")

_CHANGE_TABLE = "change_request"


async def _get_config(org_id: str) -> dict | None:
    try:
        from db import _SessionLocal
        from models import IntegrationConfig
        from sqlalchemy import select
        if not _SessionLocal:
            return None
        async with _SessionLocal() as s:
            row = await s.execute(
                select(IntegrationConfig).where(
                    IntegrationConfig.org_id == org_id,
                    IntegrationConfig.provider == "servicenow",
                    IntegrationConfig.enabled == True,
                )
            )
            cfg = row.scalar_one_or_none()
            return cfg.config if cfg else None
    except Exception:
        return None


def _client(cfg: dict) -> httpx.AsyncClient:
    return httpx.AsyncClient(
        base_url=cfg["instance_url"].rstrip("/"),
        auth=(cfg["username"], cfg["password"]),
        headers={"Content-Type": "application/json", "Accept": "application/json"},
        timeout=10.0,
    )


async def create_change_ticket(approval, design) -> tuple[str, str]:
    """
    Create a Normal Change Request.
    Returns (sys_id, ticket_url) or ("", "") on failure.
    """
    if not approval.org_id:
        return "", ""
    cfg = await _get_config(approval.org_id)
    if not cfg:
        return "", ""

    design_name = getattr(design, "name", approval.design_id) if design else approval.design_id
    risk_label  = "High" if approval.risk_score >= 75 else "Medium" if approval.risk_score >= 40 else "Low"

    body: dict[str, Any] = {
        "short_description": f"[NetDesign AI] Deploy '{design_name}' to {approval.environment}",
        "description": (
            f"Automated change request generated by NetDesign AI.\n\n"
            f"Design: {design_name}\n"
            f"Environment: {approval.environment}\n"
            f"Risk Score: {approval.risk_score}/100 ({risk_label})\n"
            f"Devices affected: {approval.device_count}\n"
            f"Requested by: {approval.requested_by}\n\n"
            f"Change Summary:\n{approval.summary or 'No summary provided.'}"
        ),
        "type": "normal",
        "risk": risk_label.lower(),
        "category": cfg.get("category", "Network"),
        "justification": approval.summary or "Network change from NetDesign AI",
        "state": "assess",   # -5=new,−4=assess, −3=auth, −2=scheduled, −1=implement, 0=review, 3=closed
    }
    if cfg.get("assignment_group"):
        body["assignment_group"] = cfg["assignment_group"]
    if cfg.get("cmdb_ci"):
        body["cmdb_ci"] = cfg["cmdb_ci"]

    try:
        async with _client(cfg) as client:
            resp = await client.post(f"/api/now/table/{_CHANGE_TABLE}", json=body)
            resp.raise_for_status()
            result = resp.json().get("result", {})
            sys_id = result.get("sys_id", "")
            number = result.get("number", sys_id)
            ticket_url = f"{cfg['instance_url']}/nav_to.do?uri={_CHANGE_TABLE}.do?sys_id={sys_id}"
            log.info("ServiceNow change created: %s (%s)", number, sys_id)
            return sys_id, ticket_url
    except Exception as exc:
        log.warning("ServiceNow create_change_ticket failed: %s", exc)
        return "", ""


async def update_change_ticket(sys_id: str | None, state: str, note: str = "") -> None:
    """Update an existing change ticket with the approval decision."""
    if not sys_id:
        return

    # Resolve org_id from the approval to get config — best-effort
    try:
        from db import _SessionLocal
        from models import ApprovalRequest, IntegrationConfig
        from sqlalchemy import select
        if not _SessionLocal:
            return
        async with _SessionLocal() as s:
            row = await s.execute(
                select(ApprovalRequest).where(ApprovalRequest.itsm_ticket_id == sys_id)
            )
            approval = row.scalar_one_or_none()
            if not approval:
                return
            cfg = await _get_config(approval.org_id)
            if not cfg:
                return

        snow_state = -3 if state == "approved" else 4   # −3=authorized, 4=cancelled
        body: dict[str, Any] = {"state": snow_state}
        if note:
            body["work_notes"] = note

        async with _client(cfg) as client:
            resp = await client.patch(f"/api/now/table/{_CHANGE_TABLE}/{sys_id}", json=body)
            resp.raise_for_status()
            log.info("ServiceNow ticket %s updated to state %s", sys_id, state)
    except Exception as exc:
        log.warning("ServiceNow update_change_ticket failed: %s", exc)


async def close_change_ticket(sys_id: str | None, org_id: str, outcome: str) -> None:
    """Close the change ticket after deployment completes."""
    if not sys_id:
        return
    cfg = await _get_config(org_id)
    if not cfg:
        return
    try:
        snow_state = 3 if outcome == "success" else 4   # 3=closed, 4=cancelled
        close_code = "successful" if outcome == "success" else "unsuccessful"
        async with _client(cfg) as client:
            resp = await client.patch(
                f"/api/now/table/{_CHANGE_TABLE}/{sys_id}",
                json={"state": snow_state, "close_code": close_code,
                      "close_notes": f"Deployment {outcome} — closed by NetDesign AI"},
            )
            resp.raise_for_status()
    except Exception as exc:
        log.warning("ServiceNow close_change_ticket failed: %s", exc)
