'use strict';

// Per-vendor config template generators

function nxosSpineConfig(dev, state) {
  var hn = dev.hostname;
  var asn = 65000;
  return '! ' + hn + ' — Cisco NX-OS Spine\n' +
    'hostname ' + hn + '\n' +
    'feature bgp\nfeature pim\nfeature interface-vlan\nfeature vn-segment-vlan-based\nfeature nv overlay\n\n' +
    'ip pim rp-address 10.0.0.1 group-list 239.0.0.0/8\n' +
    'ip pim ssm range 232.0.0.0/8\n\n' +
    'router bgp ' + asn + '\n' +
    '  router-id 10.0.0.' + (dev.unit || 1) + '\n' +
    '  address-family l2vpn evpn\n' +
    '    retain route-target all\n' +
    '  neighbor 10.1.0.0/24\n' +
    '    remote-as route-map LEAF-ASN\n' +
    '    update-source loopback0\n' +
    '    address-family l2vpn evpn\n' +
    '      send-community both\n' +
    '      route-reflector-client\n';
}

function nxosLeafConfig(dev, state) {
  var hn = dev.hostname;
  var leafAsn = 65001 + (dev.unit || 0);
  return '! ' + hn + ' — Cisco NX-OS Leaf\n' +
    'hostname ' + hn + '\n' +
    'feature bgp\nfeature pim\nfeature interface-vlan\nfeature vn-segment-vlan-based\nfeature nv overlay\n' +
    'feature lacp\nfeature vpc\n\n' +
    'vlan 10\n  name SERVERS\n  vn-segment 10010\n\n' +
    'interface nve1\n  no shutdown\n  source-interface loopback1\n  host-reachability protocol bgp\n' +
    '  member vni 10010 associate-vrf\n\n' +
    'router bgp ' + leafAsn + '\n' +
    '  router-id 10.1.0.' + (dev.unit || 1) + '\n' +
    '  address-family ipv4 unicast\n    network 10.1.0.' + (dev.unit || 1) + '/32\n' +
    '  address-family l2vpn evpn\n' +
    '  neighbor 10.0.0.0/24\n' +
    '    remote-as 65000\n' +
    '    update-source loopback0\n' +
    '    address-family l2vpn evpn\n' +
    '      send-community both\n';
}

function aristaSpineConfig(dev, state) {
  var hn = dev.hostname;
  return '! ' + hn + ' — Arista EOS Spine\n' +
    'hostname ' + hn + '\n\n' +
    'service routing protocols model multi-agent\n\n' +
    'ip routing\nrouter bgp 65000\n' +
    '   router-id 10.0.0.' + (dev.unit || 1) + '\n' +
    '   bgp listen range 10.1.0.0/24 peer-group LEAF-PEERS remote-as 65001\n' +
    '   neighbor LEAF-PEERS peer group\n' +
    '   neighbor LEAF-PEERS send-community extended\n' +
    '   address-family evpn\n' +
    '      neighbor LEAF-PEERS activate\n' +
    '   address-family ipv4\n' +
    '      neighbor LEAF-PEERS activate\n';
}

function juniperLeafConfig(dev, state) {
  var hn = dev.hostname;
  return '# ' + hn + ' — Juniper QFX Leaf\n' +
    'set system host-name ' + hn + '\n' +
    'set protocols bgp group SPINES type external\n' +
    'set protocols bgp group SPINES export LOOPBACKS\n' +
    'set protocols bgp group SPINES neighbor 10.0.0.1 peer-as 65000\n' +
    'set protocols bgp group SPINES neighbor 10.0.0.2 peer-as 65000\n' +
    'set protocols evpn encapsulation vxlan\n' +
    'set protocols evpn extended-vni-list all\n' +
    'set switch-options vtep-source-interface lo0.0\n' +
    'set switch-options vrf-target target:65000:1\n';
}

function genericConfig(dev, state) {
  var hn = dev.hostname;
  return '! ' + hn + ' — ' + dev.vendor + ' ' + dev.subLayer + '\n' +
    'hostname ' + hn + '\n' +
    '! Generated by NetDesign AI\n' +
    '! Use case: ' + (state.useCase || 'dc') + '\n' +
    '! Site: ' + (state.siteName || 'SITE') + '\n';
}

var VENDOR_GEN = {
  'Cisco': {
    'spine':    nxosSpineConfig,
    'leaf':     nxosLeafConfig,
    'default':  genericConfig
  },
  'Arista': {
    'spine':    aristaSpineConfig,
    'default':  genericConfig
  },
  'Juniper': {
    'leaf':     juniperLeafConfig,
    'default':  genericConfig
  }
};

/**
 * Generate configs for all devices in state.devices.
 * Returns object keyed by device instanceId.
 * Also stores on state.configs.
 */
function generateAllConfigs(state) {
  var configs = {};
  (state.devices || []).forEach(function(dev) {
    var vendorGens = VENDOR_GEN[dev.vendor] || {};
    var genFn = vendorGens[dev.subLayer] || vendorGens['default'] || genericConfig;
    configs[dev.instanceId] = genFn(dev, state);
  });
  state.configs = configs;
  return configs;
}

/**
 * Render config viewer HTML: device selector + config textarea.
 */
function renderConfigViewer(state) {
  var devices = state.devices || [];
  if (!devices.length) {
    return '<p class="empty-state">No devices — complete Step 1 first.</p>';
  }

  var options = devices.map(function(dev) {
    return '<option value="' + dev.instanceId + '">' + dev.hostname + ' (' + dev.model + ')</option>';
  }).join('');

  return '<div class="config-viewer">' +
    '<div class="config-toolbar">' +
      '<select id="cfg-device-select" onchange="window.showDeviceConfig(this.value)">' +
        options +
      '</select>' +
      '<button class="btn btn-secondary" onclick="window.downloadConfig()">Download</button>' +
      '<button class="btn btn-secondary" onclick="window.downloadAllConfigs()">Download All</button>' +
    '</div>' +
    '<pre id="cfg-output" class="config-pre">' +
      (Object.values(state.configs || {})[0] || '! Select a device') +
    '</pre>' +
  '</div>';
}

window.generateAllConfigs  = generateAllConfigs;
window.renderConfigViewer  = renderConfigViewer;
