'use strict';

// OS Image catalog — recommended versions per platform (G-32)
window.OS_IMAGE_CATALOG = {
  nxos: {
    stable:       { version: '10.3(5)', filename: 'nxos64-cs.10.3.5.M.bin', sha512: 'auto-verify', sizeGB: 2.1 },
    latest:       { version: '10.4(1)', filename: 'nxos64-cs.10.4.1.M.bin', sha512: 'auto-verify', sizeGB: 2.3 },
    tftp_path:    '/ztp/images/nxos/',
    http_path:    '/ztp/images/nxos/',
    boot_cmd:     'boot nxos bootflash:{filename}',
    verify_cmd:   'show version | include NXOS'
  },
  eos: {
    stable:       { version: '4.32.0F', filename: 'EOS-4.32.0F.swi', sha512: 'auto-verify', sizeGB: 1.8 },
    latest:       { version: '4.33.1F', filename: 'EOS-4.33.1F.swi', sha512: 'auto-verify', sizeGB: 1.9 },
    tftp_path:    '/ztp/images/eos/',
    http_path:    '/ztp/images/eos/',
    boot_cmd:     'boot system flash:/{filename}',
    verify_cmd:   'show version | grep EOS'
  },
  junos: {
    stable:       { version: '23.4R1', filename: 'junos-install-qfx-x86-64-23.4R1.9.tgz', sha512: 'auto-verify', sizeGB: 1.5 },
    latest:       { version: '24.2R1', filename: 'junos-install-qfx-x86-64-24.2R1.tgz', sha512: 'auto-verify', sizeGB: 1.6 },
    tftp_path:    '/ztp/images/junos/',
    http_path:    '/ztp/images/junos/',
    boot_cmd:     'request system software add /var/tmp/{filename} reboot',
    verify_cmd:   'show version | match Junos'
  },
  iosxe: {
    stable:       { version: '17.12.1', filename: 'cat9k_iosxe.17.12.01.SPA.bin', sha512: 'auto-verify', sizeGB: 1.7 },
    latest:       { version: '17.13.1', filename: 'cat9k_iosxe.17.13.01.SPA.bin', sha512: 'auto-verify', sizeGB: 1.8 },
    tftp_path:    '/ztp/images/iosxe/',
    http_path:    '/ztp/images/iosxe/',
    boot_cmd:     'boot system flash:{filename}',
    verify_cmd:   'show version | include IOS-XE'
  },
  iosxr: {
    stable:       { version: '7.11.1', filename: 'xrv9k-full-x.iso-7.11.1.iso', sha512: 'auto-verify', sizeGB: 3.2 },
    latest:       { version: '24.3.1', filename: 'xrv9k-full-x.iso-24.3.1.iso', sha512: 'auto-verify', sizeGB: 3.5 },
    tftp_path:    '/ztp/images/iosxr/',
    http_path:    '/ztp/images/iosxr/',
    boot_cmd:     'install add source /harddisk: {filename} activate commit',
    verify_cmd:   'show version | include IOS XR'
  },
  sonic: {
    stable:       { version: '202405', filename: 'sonic-vs.bin.202405', sha512: 'auto-verify', sizeGB: 0.9 },
    latest:       { version: '202411', filename: 'sonic-vs.bin.202411', sha512: 'auto-verify', sizeGB: 1.0 },
    tftp_path:    '/ztp/images/sonic/',
    http_path:    '/ztp/images/sonic/',
    boot_cmd:     'sonic_installer install /host/image-{version}',
    verify_cmd:   'show version | grep SONiC'
  }
};

/**
 * Generate OS image download/verification manifest for ZTP file server (G-32).
 * Returns a shell script that stages required images on the ZTP server.
 */
window.genOsImageManifest = function(devices, imageChannel) {
  imageChannel = imageChannel || 'stable';
  var lines = [
    '#!/bin/bash',
    '# ZTP OS Image Manifest — auto-generated by NetDesign AI',
    '# Channel: ' + imageChannel,
    '# Run on ZTP server to stage images for zero-touch provisioning',
    '',
    'set -euo pipefail',
    'IMAGE_BASE="/opt/ztp/images"',
    'HTTP_BASE="http://localhost:8080/ztp/images"',
    ''
  ];

  // Determine which platforms we need
  var platforms = {};
  (devices || []).forEach(function(dev) {
    var v = (dev.vendor || '').toLowerCase();
    var p = v.indexOf('cisco') !== -1 ? (
      (dev.subLayer === 'pe-router' || dev.subLayer === 'p-router') ? 'iosxr' :
      (dev.subLayer === 'access' || dev.subLayer === 'distribution') ? 'iosxe' : 'nxos'
    ) : v.indexOf('arista') !== -1 ? 'eos' :
        v.indexOf('juniper') !== -1 ? 'junos' :
        v.indexOf('sonic') !== -1 ? 'sonic' : null;
    if (p) platforms[p] = true;
  });

  Object.keys(platforms).forEach(function(platform) {
    var cat = window.OS_IMAGE_CATALOG[platform];
    if (!cat) return;
    var img = cat[imageChannel] || cat.stable;
    lines.push('# ── ' + platform.toUpperCase() + ' ──────────────────────────────────────');
    lines.push('mkdir -p "${IMAGE_BASE}/' + platform + '"');
    lines.push('IMAGE_PATH="${IMAGE_BASE}/' + platform + '/' + img.filename + '"');
    lines.push('if [ ! -f "${IMAGE_PATH}" ]; then');
    lines.push('  echo "[INFO] Image not found: ' + img.filename + ' (' + img.version + ')"');
    lines.push('  echo "[INFO] Place image at: ${IMAGE_PATH}"');
    lines.push('  echo "[INFO] Expected size: ~' + img.sizeGB + ' GB"');
    lines.push('  echo "[WARN] Image staging required before ZTP can provision ' + platform.toUpperCase() + ' devices"');
    lines.push('else');
    lines.push('  SIZE=$(stat -c%s "${IMAGE_PATH}" 2>/dev/null || echo 0)');
    lines.push('  echo "[OK]   ' + img.filename + ' staged (${SIZE} bytes)"');
    lines.push('fi');
    lines.push('');
  });

  lines.push('echo ""');
  lines.push('echo "Image manifest complete. Start ZTP stack with: docker compose -f ztp-docker-compose.yml up -d"');

  return lines.join('\n') + '\n';
};

/**
 * Generate per-device boot verification script for post-ZTP image check (G-32).
 */
window.genOsVersionCheck = function(devices) {
  var expected = (devices || []).reduce(function(acc, dev) {
    var v = (dev.vendor || '').toLowerCase();
    var p = v.indexOf('cisco') !== -1 ? (
      (dev.subLayer === 'pe-router' || dev.subLayer === 'p-router') ? 'iosxr' :
      (dev.subLayer === 'access' || dev.subLayer === 'distribution') ? 'iosxe' : 'nxos'
    ) : v.indexOf('arista') !== -1 ? 'eos' :
        v.indexOf('juniper') !== -1 ? 'junos' : 'sonic';
    var cat = window.OS_IMAGE_CATALOG[p];
    acc[dev.hostname] = cat ? cat.stable.version : 'unknown';
    return acc;
  }, {});

  var lines = [
    '#!/usr/bin/env python3',
    '# ZTP Image Version Check — auto-generated by NetDesign AI',
    'import subprocess, json, sys',
    'import os',
    '',
    'EXPECTED = ' + JSON.stringify(expected, null, 2),
    '',
    'def check_version(host, expected):',
    '    NET_USER = os.environ["NET_USER"]',
    '    NET_PASS = os.environ["NET_PASS"]',
    '    print(f"  [{host}] Expected: {expected}")',
    '',
    'results = {}',
    'for hostname, version in EXPECTED.items():',
    '    check_version(hostname, version)',
    '',
    'print("Version check complete.")',
    ''
  ];
  return lines.join('\n');
};

// ─── G-29 + G-30 + G-31: ZTP — File Server · State Machine · Day-0/Day-N ─────

// ─── ZTP State Machine (G-30) ────────────────────────────────────────────────

var ZTP_STATE_ORDER = [
  'REGISTERED', 'POWERED_ON', 'DHCP_ACK', 'SCRIPT_DOWNLOADED',
  'CONFIG_APPLYING', 'CALLBACK_RECEIVED', 'VERIFIED', 'ONLINE'
];
var ZTP_STATE_COLORS = {
  REGISTERED:        '#64748b',
  POWERED_ON:        '#3b82f6',
  DHCP_ACK:          '#6366f1',
  SCRIPT_DOWNLOADED: '#8b5cf6',
  CONFIG_APPLYING:   '#f59e0b',
  CALLBACK_RECEIVED: '#10b981',
  VERIFIED:          '#22c55e',
  ONLINE:            '#22c55e',
  FAILED:            '#ef4444'
};

// Session-level ZTP state store: { hostname: { state, ts, ip, platform } }
window.ZTP_STATES = {};

window.ztpInitDevices = function(devices) {
  (devices || []).forEach(function(dev) {
    if (!window.ZTP_STATES[dev.hostname]) {
      window.ZTP_STATES[dev.hostname] = {
        state: 'REGISTERED',
        ts: new Date().toISOString(),
        ip: dev.mgmtIp || ('192.168.1.' + (dev.unit || 1)),
        platform: (dev.vendor || 'Cisco').toLowerCase().includes('arista') ? 'eos'
          : (dev.vendor || '').toLowerCase().includes('juniper') ? 'junos'
          : (dev.vendor || '').toLowerCase().includes('nvidia')  ? 'sonic'
          : 'nxos',
        hostname: dev.hostname
      };
    }
  });
};

window.ztpSetState = function(hostname, newState) {
  if (!window.ZTP_STATES[hostname]) return;
  window.ZTP_STATES[hostname].state = newState;
  window.ZTP_STATES[hostname].ts    = new Date().toISOString();
  var board = document.getElementById('ztp-state-board');
  if (board) board.innerHTML = window.renderZtpStateBoard();
};

window.ztpAdvanceState = function(hostname) {
  var entry = window.ZTP_STATES[hostname];
  if (!entry) return;
  var idx = ZTP_STATE_ORDER.indexOf(entry.state);
  if (idx >= 0 && idx < ZTP_STATE_ORDER.length - 1) {
    window.ztpSetState(hostname, ZTP_STATE_ORDER[idx + 1]);
  }
};

window.ztpMarkFailed = function(hostname) {
  window.ztpSetState(hostname, 'FAILED');
};

window.ztpResetDevice = function(hostname) {
  window.ztpSetState(hostname, 'REGISTERED');
};

window.renderZtpStateBoard = function() {
  var entries = Object.values(window.ZTP_STATES);
  if (!entries.length) {
    return '<p class="empty-state">Complete Step 1 to initialize ZTP state board.</p>';
  }

  var online   = entries.filter(function(e) { return e.state === 'ONLINE' || e.state === 'VERIFIED'; }).length;
  var failed   = entries.filter(function(e) { return e.state === 'FAILED'; }).length;
  var pending  = entries.length - online - failed;

  var summary = '<div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:12px;">'
    + _ztpStatCard('Total Devices', entries.length, '#64748b')
    + _ztpStatCard('Online / Verified', online, '#22c55e')
    + _ztpStatCard('In Progress', pending - online, '#f59e0b')
    + _ztpStatCard('Failed', failed, '#ef4444')
    + '</div>';

  var rows = entries.map(function(e) {
    var color = ZTP_STATE_COLORS[e.state] || '#64748b';
    var ts = e.ts ? e.ts.replace('T', ' ').slice(0, 19) : '—';
    var isTerminal = e.state === 'ONLINE' || e.state === 'VERIFIED' || e.state === 'FAILED';
    var advBtn = isTerminal ? ''
      : '<button class="btn" style="padding:3px 10px;font-size:11px;" onclick="window.ztpAdvanceState(\'' + e.hostname + '\')">→ Next</button>';
    var failBtn = (e.state !== 'FAILED' && e.state !== 'ONLINE' && e.state !== 'VERIFIED')
      ? '<button class="btn" style="padding:3px 8px;font-size:11px;color:var(--danger);" onclick="window.ztpMarkFailed(\'' + e.hostname + '\')">✗ Fail</button>'
      : '';
    var resetBtn = '<button class="btn" style="padding:3px 8px;font-size:11px;color:var(--text-dim);" onclick="window.ztpResetDevice(\'' + e.hostname + '\')">↺</button>';
    return '<tr>'
      + '<td><strong>' + e.hostname + '</strong></td>'
      + '<td style="font-family:monospace;font-size:12px;">' + e.ip + '</td>'
      + '<td><span style="display:inline-block;padding:2px 9px;border-radius:10px;font-size:11px;font-weight:700;background:' + color + '22;color:' + color + ';">' + e.state + '</span></td>'
      + '<td style="font-size:11px;color:var(--text-dim);">' + ts + '</td>'
      + '<td>' + advBtn + ' ' + failBtn + ' ' + resetBtn + '</td>'
      + '</tr>';
  }).join('');

  return summary
    + '<div style="overflow-x:auto;">'
    + '<table class="rollback-table" style="min-width:560px;">'
    + '<thead><tr><th>Hostname</th><th>Mgmt IP</th><th>ZTP State</th><th>Last Updated</th><th>Actions</th></tr></thead>'
    + '<tbody>' + rows + '</tbody>'
    + '</table></div>'
    + '<p style="font-size:11px;color:var(--text-dim);margin-top:8px;">State is session-only. In production, states update via POST /api/ztp/callback from each device.</p>';
};

function _ztpStatCard(label, value, color) {
  return '<div style="background:' + color + '18;border:1px solid ' + color + '44;border-radius:8px;padding:10px 16px;min-width:100px;">'
    + '<div style="font-size:20px;font-weight:700;color:' + color + ';">' + value + '</div>'
    + '<div style="font-size:11px;color:var(--text-dim);margin-top:2px;">' + label + '</div>'
    + '</div>';
}

// ─── G-31: Day-0 Bootstrap Config Generator ──────────────────────────────────
// Management-plane only: hostname, mgmt IP, SSH, NTP, syslog, LLDP, callback URL
// NO BGP, NO VLANs, NO VXLAN, NO ACLs — strictly Day-0.

var DAY0_NXOS = function(d, toolIp) {
  return [
    '! ═══ Day-0 Bootstrap — ' + d.hostname + ' (NX-OS) ═══',
    '! Generated by NetDesign AI (G-31) — management plane only',
    '! NO BGP · NO VLANs · NO VXLAN · NO ACLs',
    '!',
    'hostname ' + d.hostname,
    '!',
    'username ndal-admin password 0 ' + d.day0Pass + ' role network-admin',
    '!',
    'feature ssh',
    'no feature telnet',
    'ssh key rsa 2048',
    '!',
    'interface mgmt0',
    '  no shutdown',
    '  ip address ' + d.mgmtIp + '/' + d.mgmtPrefix,
    '!',
    'ip route 0.0.0.0/0 ' + d.mgmtGw + ' mgmt',
    '!',
    'ntp server ' + toolIp + ' use-vrf management',
    'clock timezone UTC 0 0',
    '!',
    'logging server ' + toolIp + ' 6 use-vrf management',
    'logging source-interface mgmt0',
    '!',
    'lldp run',
    '!',
    '! ── ZTP callback (runs after config applies) ────────────────────────────',
    '! curl -X POST http://' + toolIp + ':8080/api/ztp/callback \\',
    '!   -d \'{"hostname":"' + d.hostname + '","status":"CONFIG_APPLYING"}\'',
  ].join('\n');
};

var DAY0_EOS = function(d, toolIp) {
  return [
    '! ═══ Day-0 Bootstrap — ' + d.hostname + ' (EOS) ═══',
    '! Management plane only — NO BGP · NO VLANs · NO VXLAN',
    '!',
    'hostname ' + d.hostname,
    '!',
    'username ndal-admin privilege 15 role network-admin secret sha512 ' + d.day0Pass,
    '!',
    'interface Management1',
    '  no shutdown',
    '  ip address ' + d.mgmtIp + '/' + d.mgmtPrefix,
    '!',
    'ip route 0.0.0.0/0 ' + d.mgmtGw,
    '!',
    'management ssh',
    '  idle-timeout 300',
    '!',
    'management api http-commands',
    '  no protocol http',
    '  protocol https',
    '!',
    'ntp server ' + toolIp,
    '!',
    'logging host ' + toolIp,
    '!',
    'lldp run',
    '!',
    '! ── ZTP callback ────────────────────────────────────────────────────────',
    '! event-handler ZTP-CALLBACK',
    '!   action bash curl -X POST http://' + toolIp + ':8080/api/ztp/callback \\',
    '!     -d \'{"hostname":"' + d.hostname + '","status":"CONFIG_APPLYING"}\'',
  ].join('\n');
};

var DAY0_JUNOS = function(d, toolIp) {
  return [
    '# ═══ Day-0 Bootstrap — ' + d.hostname + ' (JunOS) ═══',
    '# Management plane only — NO BGP · NO VLANs · NO VXLAN',
    '#',
    'set system host-name ' + d.hostname,
    'set system root-authentication plain-text-password-value "' + d.day0Pass + '"',
    'set system login user ndal-admin class super-user',
    'set system login user ndal-admin authentication plain-text-password-value "' + d.day0Pass + '"',
    'set system services ssh root-login deny',
    'set system services ssh protocol-version v2',
    'set system syslog host ' + toolIp + ' any info',
    'set system ntp server ' + toolIp,
    'set interfaces em0 unit 0 family inet address ' + d.mgmtIp + '/' + d.mgmtPrefix,
    'set routing-options static route 0.0.0.0/0 next-hop ' + d.mgmtGw,
    'set protocols lldp interface all',
    'set protocols lldp-med interface all',
    '#',
    '# ZTP callback (add to commit script):',
    '# curl -X POST http://' + toolIp + ':8080/api/ztp/callback \\',
    '#   -d \'{"hostname":"' + d.hostname + '","status":"CONFIG_APPLYING"}\'',
  ].join('\n');
};

var DAY0_SONIC = function(d, toolIp) {
  var cfg = {
    DEVICE_METADATA: { localhost: { hostname: d.hostname, type: 'ToRRouter' } },
    MGMT_INTERFACE: {},
    MGMT_VRF_CONFIG: { vrf_global: { mgmtVrfEnabled: 'true' } },
    NTP_SERVER: {}, SYSLOG_SERVER: {}
  };
  cfg.MGMT_INTERFACE['eth0|' + d.mgmtIp + '/' + d.mgmtPrefix] = { gwaddr: d.mgmtGw };
  cfg.NTP_SERVER[toolIp] = {};
  cfg.SYSLOG_SERVER[toolIp] = {};
  return [
    '# ═══ Day-0 Bootstrap — ' + d.hostname + ' (SONiC) ═══',
    '# Save as /etc/sonic/config_db_day0.json, then:',
    '#   sudo config load /etc/sonic/config_db_day0.json -y',
    '#   sudo config save -y',
    '#',
    JSON.stringify(cfg, null, 2),
    '#',
    '# ZTP callback (add to ZTP script):',
    '# curl -X POST http://' + toolIp + ':8080/api/ztp/callback \\',
    '#   -d \'{"hostname":"' + d.hostname + '","status":"CONFIG_APPLYING"}\'',
  ].join('\n');
};

window.genDay0Config = function(devices, state) {
  if (!devices || !devices.length) return '# No devices — complete Step 1 first.\n';
  var toolIp  = (state && state.toolIp) || '10.0.0.100';
  var mgmtNet = (state && state.mgmtNetwork) || '192.168.100';

  var blocks = devices.map(function(dev, i) {
    var v = (dev.vendor || '').toLowerCase();
    var platform = v.includes('arista') ? 'eos'
      : v.includes('juniper') ? 'junos'
      : (v.includes('nvidia') || v.includes('sonic')) ? 'sonic'
      : 'nxos';

    var d = {
      hostname:   dev.hostname,
      mgmtIp:     dev.mgmtIp || (mgmtNet + '.' + (10 + i)),
      mgmtPrefix: '24',
      mgmtGw:     mgmtNet + '.1',
      day0Pass:   '${NET_PASS:-ChangeMe!}'
    };
    if (platform === 'eos')   return DAY0_EOS(d, toolIp);
    if (platform === 'junos') return DAY0_JUNOS(d, toolIp);
    if (platform === 'sonic') return DAY0_SONIC(d, toolIp);
    return DAY0_NXOS(d, toolIp);
  });

  return [
    '# NetDesign AI — Day-0 Bootstrap Configs (G-31)',
    '# Site: ' + ((state && state.siteCode) || 'SITE') + ' | Generated: ' + new Date().toISOString(),
    '# Tool IP (NTP/Syslog/Callback): ' + toolIp,
    '# IMPORTANT: Replace ${NET_PASS} with actual password before deployment.',
    '# Day-0 = management plane ONLY. Day-N (full config) is in Step 3.',
    '',
  ].join('\n') + blocks.join('\n\n' + '!'.repeat(72) + '\n\n');
};

// ─── G-29: ZTP File Server ────────────────────────────────────────────────────

window.genZtpDockerCompose = function(state) {
  var toolIp = (state && state.toolIp) || '10.0.0.100';
  return [
    '# NetDesign AI — ZTP File Server Stack (G-29)',
    '# Add to docker-compose.local.yml or run standalone:',
    '#   docker compose -f ztp-stack.yml up -d',
    '',
    'services:',
    '',
    '  ztp-nginx:',
    '    image: nginx:alpine',
    '    ports:',
    '      - "8080:80"',
    '    volumes:',
    '      - ./ztp/scripts:/usr/share/nginx/html/ztp/scripts:ro',
    '      - ./ztp/configs:/usr/share/nginx/html/ztp/configs:ro',
    '      - ./ztp/nginx.conf:/etc/nginx/conf.d/default.conf:ro',
    '    restart: unless-stopped',
    '',
    '  ztp-tftp:',
    '    image: pghalliday/tftp:latest',
    '    ports:',
    '      - "69:69/udp"',
    '    volumes:',
    '      - ./ztp/scripts:/var/tftpboot:ro',
    '    restart: unless-stopped',
    '',
    '  ztp-api:',
    '    image: python:3.11-slim',
    '    ports:',
    '      - "8081:8081"',
    '    volumes:',
    '      - ./ztp/api.py:/app/api.py:ro',
    '    working_dir: /app',
    '    command: sh -c "pip install flask -q && python api.py"',
    '    restart: unless-stopped',
    '    environment:',
    '      - TOOL_IP=' + toolIp,
  ].join('\n');
};

window.genZtpNginxConf = function() {
  return [
    '# ztp/nginx.conf',
    'server {',
    '    listen 80;',
    '    server_name _;',
    '    root /usr/share/nginx/html;',
    '    autoindex on;',
    '',
    '    # ZTP script delivery',
    '    location /ztp/scripts/ {',
    '        add_header Content-Type text/plain;',
    '        add_header Cache-Control no-cache;',
    '    }',
    '',
    '    # Day-0 config delivery (served after SCRIPT_DOWNLOADED state)',
    '    location /ztp/configs/ {',
    '        add_header Content-Type text/plain;',
    '        add_header Cache-Control no-cache;',
    '    }',
    '',
    '    # Health check',
    '    location /health {',
    '        return 200 "ok\\n";',
    '        add_header Content-Type text/plain;',
    '    }',
    '}',
  ].join('\n');
};

window.genZtpDhcpScope = function(devices, state) {
  var toolIp  = (state && state.toolIp) || '10.0.0.100';
  var mgmtNet = (state && state.mgmtNetwork) || '192.168.100';
  var lines = [
    '# ── ISC DHCPd — ZTP DHCP Scope (add to /etc/dhcp/dhcpd.conf) ────────────',
    '',
    'option space cisco-auto-install;',
    'option cisco-auto-install.POAP-script code 1 = text;',
    '',
    'subnet ' + mgmtNet + '.0 netmask 255.255.255.0 {',
    '  range ' + mgmtNet + '.10 ' + mgmtNet + '.250;',
    '  option routers ' + mgmtNet + '.1;',
    '  option domain-name-servers 8.8.8.8;',
    '  default-lease-time 600;',
    '  max-lease-time 7200;',
    '',
    '  # NX-OS POAP',
    '  option tftp-server-name "' + toolIp + '";',
    '  filename "poap.py";',
    '',
    '  # EOS ZTP',
    '  option bootfile-name "http://' + toolIp + ':8080/ztp/scripts/eos-ztp.py";',
    '',
    '  # Static bindings per device (MAC → IP)',
  ];
  (devices || []).forEach(function(dev, i) {
    var mac = dev.mgmtMac || ('aa:bb:cc:dd:ee:' + ('0' + (10 + i).toString(16)).slice(-2));
    var ip  = dev.mgmtIp  || (mgmtNet + '.' + (10 + i));
    lines.push('  host ' + dev.hostname + ' { hardware ethernet ' + mac + '; fixed-address ' + ip + '; }');
  });
  lines.push('}');
  return lines.join('\n');
};

window.genZtpApiStubs = function(devices, state) {
  var toolIp = (state && state.toolIp) || '10.0.0.100';
  var devList = JSON.stringify((devices || []).map(function(d) {
    return { hostname: d.hostname, ip: d.mgmtIp || '192.168.1.1', state: 'REGISTERED' };
  }), null, 4);

  return [
    '#!/usr/bin/env python3',
    '"""NetDesign AI — ZTP State Machine API (G-30)',
    'Site: ' + ((state && state.siteCode) || 'SITE'),
    'Generated: ' + new Date().toISOString(),
    '',
    'Endpoints:',
    '  POST /api/ztp/register   — pre-register device',
    '  POST /api/ztp/callback   — device calls when ZTP step completes',
    '  GET  /api/ztp/state      — get all device provisioning states',
    '  GET  /api/ztp/state/<hostname> — get single device state',
    '',
    'Usage: python ztp/api.py',
    '"""',
    '',
    'import os, json, datetime',
    'from flask import Flask, request, jsonify',
    '',
    'app = Flask(__name__)',
    '',
    'ZTP_STATES = {d["hostname"]: d for d in ' + devList + '}',
    '',
    'VALID_STATES = [',
    '    "REGISTERED", "POWERED_ON", "DHCP_ACK", "SCRIPT_DOWNLOADED",',
    '    "CONFIG_APPLYING", "CALLBACK_RECEIVED", "VERIFIED", "ONLINE", "FAILED"',
    ']',
    '',
    '@app.route("/api/ztp/register", methods=["POST"])',
    'def register():',
    '    data = request.json or {}',
    '    hostname = data.get("hostname")',
    '    if not hostname:',
    '        return jsonify({"error": "hostname required"}), 400',
    '    ZTP_STATES[hostname] = {',
    '        "hostname": hostname,',
    '        "ip": data.get("ip", ""),',
    '        "state": "REGISTERED",',
    '        "ts": datetime.datetime.utcnow().isoformat()',
    '    }',
    '    return jsonify({"ok": True, "state": "REGISTERED"})',
    '',
    '@app.route("/api/ztp/callback", methods=["POST"])',
    'def callback():',
    '    data = request.json or {}',
    '    hostname = data.get("hostname")',
    '    new_state = data.get("status") or data.get("state")',
    '    if hostname not in ZTP_STATES:',
    '        return jsonify({"error": "device not registered"}), 404',
    '    if new_state not in VALID_STATES:',
    '        return jsonify({"error": "invalid state"}), 400',
    '    ZTP_STATES[hostname]["state"] = new_state',
    '    ZTP_STATES[hostname]["ts"]    = datetime.datetime.utcnow().isoformat()',
    '    print(f"[ZTP] {hostname} → {new_state}")',
    '    return jsonify({"ok": True, "hostname": hostname, "state": new_state})',
    '',
    '@app.route("/api/ztp/state", methods=["GET"])',
    'def get_all_states():',
    '    return jsonify(list(ZTP_STATES.values()))',
    '',
    '@app.route("/api/ztp/state/<hostname>", methods=["GET"])',
    'def get_device_state(hostname):',
    '    if hostname not in ZTP_STATES:',
    '        return jsonify({"error": "not found"}), 404',
    '    return jsonify(ZTP_STATES[hostname])',
    '',
    'if __name__ == "__main__":',
    '    port = int(os.getenv("PORT", 8081))',
    '    print(f"ZTP API starting on :{port}")',
    '    app.run(host="0.0.0.0", port=port, debug=False)',
    ''
  ].join('\n');
};

/**
 * Render OS Image Management tab content (G-32).
 */
window.renderZtpImageTab = function(state) {
  var devices = state.devices || [];
  var lines = [
    '<h3 style="margin:0 0 12px">OS Image Version Management</h3>',
    '<p style="color:var(--text-dim);margin:0 0 16px;font-size:13px;">Stage OS images on the ZTP server before provisioning. Images are served via HTTP/TFTP to devices during ZTP.</p>',
    '<div style="display:flex;gap:12px;margin-bottom:16px;flex-wrap:wrap;">',
    '<label style="font-size:13px;font-weight:600;">Image Channel:',
    '<select id="ztp-img-channel" style="margin-left:8px;padding:4px 8px;background:var(--surface);color:var(--text);border:1px solid var(--border);border-radius:4px;">',
    '<option value="stable">Stable (Recommended)</option>',
    '<option value="latest">Latest</option>',
    '</select></label>',
    '<button class="btn btn-secondary" onclick="window.ztpDownloadImageManifest()">&#8595; Download Image Manifest</button>',
    '<button class="btn btn-secondary" onclick="window.ztpDownloadVersionCheck()">&#8595; Version Check Script</button>',
    '</div>'
  ];

  // Image table
  var platforms = {};
  devices.forEach(function(dev) {
    var v = (dev.vendor || '').toLowerCase();
    var p = v.indexOf('cisco') !== -1 ? (
      (dev.subLayer === 'pe-router' || dev.subLayer === 'p-router') ? 'iosxr' :
      (dev.subLayer === 'access' || dev.subLayer === 'distribution') ? 'iosxe' : 'nxos'
    ) : v.indexOf('arista') !== -1 ? 'eos' :
        v.indexOf('juniper') !== -1 ? 'junos' :
        v.indexOf('sonic') !== -1 ? 'sonic' : null;
    if (p) { platforms[p] = (platforms[p] || 0) + 1; }
  });

  if (Object.keys(platforms).length === 0) {
    lines.push('<p class="empty-state">No devices — complete Step 1 first.</p>');
  } else {
    lines.push('<div class="table-scroll"><table class="bom-table"><thead><tr>');
    lines.push('<th>Platform</th><th>Device Count</th><th>Stable Version</th><th>Latest Version</th><th>Image File</th><th>Size</th><th>Boot Command</th>');
    lines.push('</tr></thead><tbody>');
    Object.keys(platforms).forEach(function(p) {
      var cat = window.OS_IMAGE_CATALOG[p];
      if (!cat) return;
      lines.push('<tr>');
      lines.push('<td><strong>' + p.toUpperCase() + '</strong></td>');
      lines.push('<td>' + platforms[p] + '</td>');
      lines.push('<td><span style="color:#22c55e;">' + cat.stable.version + '</span></td>');
      lines.push('<td>' + cat.latest.version + '</td>');
      lines.push('<td style="font-family:monospace;font-size:11px;">' + cat.stable.filename + '</td>');
      lines.push('<td>' + cat.stable.sizeGB + ' GB</td>');
      lines.push('<td style="font-family:monospace;font-size:11px;">' + cat.stable.boot_cmd.replace('{filename}', cat.stable.filename) + '</td>');
      lines.push('</tr>');
    });
    lines.push('</tbody></table></div>');
  }
  return lines.join('\n');
};

window.ztpDownloadImageManifest = function() {
  var channel = (document.getElementById('ztp-img-channel') || {}).value || 'stable';
  var script = window.genOsImageManifest(window.STATE ? window.STATE.devices : [], channel);
  var blob = new Blob([script], {type: 'text/plain'});
  var a = document.createElement('a'); a.href = URL.createObjectURL(blob);
  a.download = 'ztp-image-manifest.sh'; a.click();
};

window.ztpDownloadVersionCheck = function() {
  var script = window.genOsVersionCheck(window.STATE ? window.STATE.devices : []);
  var blob = new Blob([script], {type: 'text/plain'});
  var a = document.createElement('a'); a.href = URL.createObjectURL(blob);
  a.download = 'ztp-version-check.py'; a.click();
};
