"""
Ansible playbook export for NetDesign AI.

Generates a ready-to-run Ansible playbook YAML from a design state
and optional per-device rendered configs.  Platform-appropriate
modules are selected automatically (ios_config, eos_config, etc.).
"""
from __future__ import annotations

import textwrap
from typing import Any


# Map platform → Ansible network module
_MODULE: dict[str, str] = {
    "ios_xe":   "cisco.ios.ios_config",
    "ios":      "cisco.ios.ios_config",
    "nxos":     "cisco.nxos.nxos_config",
    "eos":      "arista.eos.eos_config",
    "sonic":    "community.general.sonic_config",
    "junos":    "junipernetworks.junos.junos_config",
    "palo_alto":"paloaltonetworks.panos.panos_config_element",
    "default":  "ansible.netcommon.cli_config",
}

# Role → likely platform (used when per-device platform not specified)
_ROLE_PLATFORM: dict[str, str] = {
    "spine":        "nxos",
    "leaf":         "nxos",
    "gpu-spine":    "sonic",
    "gpu-tor":      "sonic",
    "core":         "ios_xe",
    "distribution": "ios_xe",
    "access":       "ios_xe",
    "firewall":     "palo_alto",
    "wan-router":   "ios_xe",
}


def _module_for(platform: str) -> str:
    return _MODULE.get(platform.lower(), _MODULE["default"])


def _yaml_str(text: str, indent: int = 6) -> str:
    """Wrap a multi-line config block as a YAML literal scalar."""
    pad = " " * indent
    lines = text.splitlines()
    body  = "\n".join(pad + "  " + ln for ln in lines)
    return f"|\n{body}"


def _build_inventory(devices: list[dict]) -> str:
    lines = ["all:", "  hosts:"]
    for dev in devices:
        ip       = dev.get("ip", dev.get("hostname", "REPLACE_ME"))
        platform = dev.get("platform", "default")
        lines.append(f"    {dev['hostname']}:")
        lines.append(f"      ansible_host: {ip}")
        lines.append(f"      ansible_network_os: {platform}")
    return "\n".join(lines)


def _build_playbook(
    org_name:     str,
    use_case:     str,
    devices:      list[dict],
    configs:      dict[str, str],
) -> str:
    """Return the playbook YAML string."""

    tasks_by_platform: dict[str, list[dict]] = {}
    for dev in devices:
        platform = dev.get("platform", _ROLE_PLATFORM.get(dev.get("role", ""), "default"))
        cfg_text = configs.get(dev["hostname"], "")
        tasks_by_platform.setdefault(platform, []).append({
            "hostname": dev["hostname"],
            "config":   cfg_text,
            "module":   _module_for(platform),
        })

    plays = []
    for platform, devs in tasks_by_platform.items():
        host_list = [d["hostname"] for d in devs]
        module    = devs[0]["module"]

        task_blocks = []
        for d in devs:
            if d["config"]:
                lines_yaml = "\n".join(
                    f"            - {ln}" for ln in d["config"].splitlines() if ln.strip()
                )
                task_blocks.append(
                    f"        - name: Apply config to {d['hostname']}\n"
                    f"          {module}:\n"
                    f"            lines:\n"
                    f"{lines_yaml}\n"
                    f"          when: inventory_hostname == \"{d['hostname']}\""
                )
            else:
                task_blocks.append(
                    f"        - name: Validate reachability — {d['hostname']}\n"
                    f"          {module}:\n"
                    f"            commands:\n"
                    f"              - show version\n"
                    f"          when: inventory_hostname == \"{d['hostname']}\""
                )

        tasks_str = "\n\n".join(task_blocks)
        hosts_str = ", ".join(host_list)

        plays.append(
            f"    - name: Configure {platform} devices\n"
            f"      hosts: {hosts_str}\n"
            f"      gather_facts: false\n"
            f"      connection: network_cli\n"
            f"      become: true\n"
            f"      become_method: enable\n"
            f"      tasks:\n"
            f"{tasks_str}\n"
        )

    plays_str = "\n".join(plays)

    return textwrap.dedent(f"""\
        ---
        # NetDesign AI — Ansible Playbook
        # Organisation : {org_name}
        # Use-case     : {use_case}
        # Generated by : NetDesign AI v2.4.0
        #
        # Usage:
        #   ansible-playbook -i inventory.yml netdesign_deploy.yml
        #   ansible-playbook -i inventory.yml netdesign_deploy.yml --check   (dry-run)
        #
        # Vars file (create group_vars/all.yml):
        #   ansible_user: admin
        #   ansible_password: "{{ vault_net_password }}"
        #   ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

        - name: NetDesign AI — {org_name} deployment
          hosts: all
          gather_facts: false
          tasks:

            - name: Pre-flight connectivity check
              wait_for_connection:
                timeout: 10

        {plays_str}
        - name: Post-deploy verification
          hosts: all
          gather_facts: false
          connection: network_cli
          tasks:

            - name: Collect show version
              cli_command:
                command: show version
              register: show_version_out

            - name: Save show version to local file
              copy:
                content: "{{ show_version_out.stdout }}"
                dest: "./post_deploy/{{ inventory_hostname }}_version.txt"
              delegate_to: localhost
    """)


def generate_ansible(
    design_state: dict[str, Any],
    configs:      dict[str, str] | None = None,
    ip_plan:      dict[str, Any]  | None = None,
) -> tuple[str, str]:
    """
    Returns (playbook_yaml, inventory_yaml).
    """
    configs   = configs or {}
    ip_plan   = ip_plan or {}
    org_name  = design_state.get("orgName", "network")
    use_case  = design_state.get("uc", "campus")

    # Build device list from ip_plan or fall back to design_state topology counts
    devices: list[dict] = []

    ip_devices = ip_plan.get("devices", [])
    if ip_devices:
        for dev in ip_devices:
            devices.append({
                "hostname": dev.get("hostname", "device"),
                "ip":       dev.get("loopback", dev.get("ip", "REPLACE_ME")),
                "role":     dev.get("role", "default"),
                "platform": dev.get("platform", _ROLE_PLATFORM.get(dev.get("role",""), "default")),
            })
    else:
        # Fallback: synthesise from design_state counts (mirrors drawio._build_layers logic)
        uc = use_case
        def _gen(role, prefix, count, platform):
            return [
                {"hostname": f"{prefix}{i+1:02d}", "role": role, "platform": platform,
                 "ip": f"REPLACE_ME_{prefix}{i+1:02d}"}
                for i in range(min(count, 20))
            ]
        if uc in ("campus", "enterprise"):
            devices += _gen("firewall",     "FW-",    design_state.get("numFirewalls", 1), "ios_xe")
            devices += _gen("core",         "CORE-",  design_state.get("numCore", 2),      "ios_xe")
            devices += _gen("distribution", "DIST-",  design_state.get("numDist", 4),      "ios_xe")
            devices += _gen("access",       "ACC-",   design_state.get("numAccess", 8),    "ios_xe")
        elif uc in ("datacenter", "dc"):
            devices += _gen("firewall", "FW-",    design_state.get("numFirewalls", 2), "palo_alto")
            devices += _gen("spine",    "SPINE-", design_state.get("numSpine", 2),     "nxos")
            devices += _gen("leaf",     "LEAF-",  design_state.get("numLeaf", 8),      "nxos")
        elif uc in ("gpu", "ai_fabric"):
            devices += _gen("gpu-spine", "GPUSPINE-", design_state.get("numSpine", 2), "sonic")
            devices += _gen("gpu-tor",   "TOR-",      design_state.get("numLeaf", 8),  "sonic")
        else:
            devices += _gen("core",   "CORE-", design_state.get("numCore", 2),   "ios_xe")
            devices += _gen("access", "ACC-",  design_state.get("numAccess", 4), "ios_xe")

    playbook  = _build_playbook(org_name, use_case, devices, configs)
    inventory = _build_inventory(devices)
    return playbook, inventory
