/**
 * ansible-export.ts — inventory and playbook generation from the BOM.
 *
 * Replaces the inline generators in Step6Deploy, which took only a list of
 * hostnames and therefore threw away everything the BOM knows. Those emitted
 * `ansible_network_os=ios` for EVERY device — so a Juniper, Arista or Nokia
 * fleet got the IOS cliconf plugin and the run failed on the first task —
 * plus fabricated sequential `10.0.0.x` management IPs and a global
 * `become_method=enable` that is meaningless outside IOS/NX-OS.
 *
 * Platform resolution reuses `ztpPlatform()` rather than a second vendor
 * table: two mappings that must agree is exactly the drift this codebase
 * keeps paying for.
 */
import type { BOMDevice } from '@/types'
import { ztpPlatform, type ZTPPlatform } from '@/lib/ztp'

/** Ansible `ansible_network_os` value for each platform we generate for. */
const NETWORK_OS: Record<ZTPPlatform, string> = {
  nxos: 'cisco.nxos.nxos',
  'ios-xe': 'cisco.ios.ios',
  iosxr: 'cisco.iosxr.iosxr',
  eos: 'arista.eos.eos',
  junos: 'junipernetworks.junos.junos',
  srl: 'nokia.srlinux.srlinux',
  cumulus: 'community.network.cumulus',
  dellos10: 'dellemc.os10.os10',
  fortios: 'fortinet.fortios.fortios',
  arubaoscx: 'arubanetworks.aoscx.aoscx',
  exos: 'community.network.exos',
  panos: 'paloaltonetworks.panos.panos',
}

/** The config-push module for each platform. */
const CONFIG_MODULE: Record<ZTPPlatform, string> = {
  nxos: 'cisco.nxos.nxos_config',
  'ios-xe': 'cisco.ios.ios_config',
  iosxr: 'cisco.iosxr.iosxr_config',
  eos: 'arista.eos.eos_config',
  junos: 'junipernetworks.junos.junos_config',
  srl: 'nokia.srlinux.config',
  cumulus: 'ansible.netcommon.cli_config',
  dellos10: 'dellemc.os10.os10_config',
  fortios: 'fortinet.fortios.fortios_configuration_fact',
  arubaoscx: 'arubanetworks.aoscx.aoscx_config',
  exos: 'ansible.netcommon.cli_config',
  panos: 'paloaltonetworks.panos.panos_config_element',
}

/**
 * Platforms whose CLI has a privileged "enable" mode. `become` on anything
 * else is at best ignored and at worst breaks the connection plugin.
 */
const NEEDS_ENABLE = new Set<ZTPPlatform>(['nxos', 'ios-xe', 'iosxr', 'eos'])

/** Platforms Ansible drives over NETCONF rather than a screen-scraped CLI. */
const NETCONF_PLATFORMS = new Set<ZTPPlatform>(['junos', 'srl'])

export function ansibleNetworkOs(dev: BOMDevice): string {
  return NETWORK_OS[ztpPlatform(dev)]
}

export function ansibleConfigModule(dev: BOMDevice): string {
  return CONFIG_MODULE[ztpPlatform(dev)]
}

export function ansibleConnection(dev: BOMDevice): string {
  return NETCONF_PLATFORMS.has(ztpPlatform(dev))
    ? 'ansible.netcommon.netconf'
    : 'ansible.netcommon.network_cli'
}

/** Ansible group name for a device — its BOM tier, normalised. */
function groupOf(dev: BOMDevice): string {
  return (dev.subLayer || dev.role || 'device').replace(/[^a-zA-Z0-9]+/g, '_')
}

/**
 * YAML inventory. Grouped by BOM tier so a play can target `leaf` or
 * `firewall` directly, with per-device platform vars — the whole point of
 * generating this from the BOM rather than from a list of names.
 *
 * Management addressing is left as `<CHANGE-ME-mgmt-ip>`: the tool does not
 * own the OOB plan, and inventing `10.0.0.x` produced an inventory that
 * looked complete and connected to nothing.
 */
export function buildAnsibleInventory(devices: BOMDevice[]): string {
  const real = devices.filter(d => !['gpu-compute', 'cloud-gw', 'cloud-transit'].includes(d.subLayer))
  if (!real.length) return '# No CLI-manageable devices in this design.\n'

  const groups = new Map<string, BOMDevice[]>()
  for (const d of real) {
    const g = groupOf(d)
    groups.set(g, [...(groups.get(g) ?? []), d])
  }

  const lines: string[] = [
    '# Ansible inventory — generated by NetDesign AI from the BOM.',
    '# Replace every <CHANGE-ME-*> before running.',
    'all:',
    '  children:',
  ]
  for (const [group, devs] of [...groups].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`    ${group}:`, '      hosts:')
    for (const d of devs) {
      lines.push(
        `        ${d.hostname || d.id}:`,
        `          ansible_host: <CHANGE-ME-mgmt-ip>`,
        `          ansible_network_os: ${ansibleNetworkOs(d)}`,
        `          ansible_connection: ${ansibleConnection(d)}`,
        `          nd_vendor: ${d.vendor}`,
        `          nd_model: ${d.model}`,
      )
      if (NEEDS_ENABLE.has(ztpPlatform(d))) {
        lines.push('          ansible_become: true', '          ansible_become_method: enable')
      }
    }
  }
  lines.push(
    '  vars:',
    '    ansible_user: <CHANGE-ME-username>',
    '    ansible_password: <CHANGE-ME-password>',
    '    ansible_python_interpreter: auto_silent',
  )
  return lines.join('\n') + '\n'
}

/** Indent a config blob as a YAML literal scalar. */
function literalBlock(text: string, indent: number): string {
  const pad = ' '.repeat(indent)
  return '|\n' + text.split('\n').map(l => pad + l).join('\n')
}

/**
 * Push playbook. One play per platform, because the config module differs —
 * a single play with one module cannot drive a multi-vendor fleet.
 */
export function buildAnsiblePlaybook(
  devices: BOMDevice[],
  configs: Record<string, string> = {},
): string {
  const real = devices.filter(d => !['gpu-compute', 'cloud-gw', 'cloud-transit'].includes(d.subLayer))
  if (!real.length) return '# No CLI-manageable devices in this design.\n'

  const byPlatform = new Map<ZTPPlatform, BOMDevice[]>()
  for (const d of real) {
    const p = ztpPlatform(d)
    byPlatform.set(p, [...(byPlatform.get(p) ?? []), d])
  }

  const out: string[] = [
    '---',
    '# Config push — generated by NetDesign AI.',
    '# One play per platform: the config module differs per NOS, so a single',
    '# play cannot drive a multi-vendor fleet.',
  ]
  for (const [platform, devs] of [...byPlatform].sort((a, b) => a[0].localeCompare(b[0]))) {
    out.push(
      `- name: Push configuration (${platform})`,
      `  hosts: ${devs.map(d => d.hostname || d.id).join(',')}`,
      '  gather_facts: false',
      '  connection: ' + ansibleConnection(devs[0]),
      '  tasks:',
    )
    for (const d of devs) {
      const name = d.hostname || d.id
      const cfg = configs[d.id]
      out.push(
        `    - name: ${name} — apply generated configuration`,
        `      when: inventory_hostname == '${name}'`,
        `      ${ansibleConfigModule(d)}:`,
      )
      out.push(cfg
        ? `        src: ${literalBlock(cfg, 10)}`
        : `        src: "{{ lookup('file', 'configs/${name}.cfg') }}"`)
      out.push('      register: nd_push', '')
    }
  }
  return out.join('\n')
}
