/**
 * cloud-terraform.ts — Infrastructure-as-Code for multicloud / Aviatrix designs.
 *
 * A multicloud design is made entirely of cloud gateways and transit VPCs.
 * Those are provisioned through a provider API, not a device CLI, so the
 * config generator produced nothing for them and the use case had no
 * deliverable at all beyond a device list (audit finding AA2).
 *
 * The backend already had these three stacks as Jinja2 templates behind
 * POST /api/export/terraform, which no UI ever called. This is the
 * client-side mirror, so multicloud produces real IaC in demo mode like
 * every other use case (§3). The templates carry no control flow — only
 * variable substitution — so they were converted mechanically, and
 * `cloud-terraform.parity.test.ts` renders both sides with the same context
 * and asserts the HCL is byte-identical.
 *
 * Keep in step with backend/templates/multicloud/*.tf.j2.
 */

export type CloudProvider = 'aws' | 'azure' | 'gcp'

/** Inputs shared by all three stacks; mirrors the backend context builders. */
export interface CloudTerraformOpts {
  orgName?: string
  /** Provider-native region: us-east-1 / eastus / us-central1. */
  region?: string
  env?: string
  /** Organisation supernet advertised into the cloud hub. */
  orgCidr?: string
  /** Address space for the hub itself. */
  hubCidr?: string
  bgpAsn?: number
  /** AWS: the Amazon-side ASN of the Direct Connect / TGW association. */
  amazonAsn?: number
  availabilityZones?: string[]
  dxPrefixes?: string[]
  /** Azure: ExpressRoute ASN; defaults to bgpAsn, then 65515. */
  erAsn?: number
  azureRg?: string
  gcpProject?: string
  cloudRouterAsn?: number
}

const DEFAULT_REGION: Record<CloudProvider, string> = {
  aws: 'us-east-1', azure: 'eastus', gcp: 'us-central1',
}

/**
 * Jinja's `tojson` puts a space after each comma; `JSON.stringify` does not.
 * Matching it keeps the emitted HCL byte-identical to the backend's.
 */
function tfList(items: string[]): string {
  return '[' + items.map(i => JSON.stringify(i)).join(', ') + ']'
}

/** Lower-case, hyphenated slug — matches the backend's org_slug. */
function slug(s: string): string {
  return s.toLowerCase().split(' ').join('-')
}

/** The backend derives region_code as region minus hyphens, capped at 8. */
function regionCode(region: string): string {
  return region.split('-').join('').slice(0, 8)
}

export function generateAwsTerraform(opts: CloudTerraformOpts = {}): string {
  const org_name = opts.orgName ?? 'NetDesignAI'
  const region = opts.region ?? DEFAULT_REGION.aws
  const stack_name = `${slug(org_name)}-tgw`
  const region_code = regionCode(region)
  const env = opts.env ?? 'prod'
  const cidr = opts.orgCidr ?? '10.0.0.0/8'
  const hub_cidr = opts.hubCidr ?? '10.254.0.0/16'
  const amazon_asn = opts.amazonAsn ?? 64512
  const customer_asn = opts.bgpAsn ?? 65001
  const azs = opts.availabilityZones ?? ['a', 'b', 'c']
  const dx_prefixes = opts.dxPrefixes ?? ['10.0.0.0/8']
  return `
# ═══════════════════════════════════════════════════════════
# Stack  : ${stack_name}
# Region : ${region}
# Org    : ${org_name}
# Env    : ${env}
# Generated by NetDesign AI — multicloud use case
# ═══════════════════════════════════════════════════════════

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {
    bucket         = "${org_name.toLowerCase().split(" ").join("-")}-tf-state"
    key            = "network/${stack_name}/terraform.tfstate"
    region         = "${region}"
    dynamodb_table = "tf-state-lock"
    encrypt        = true
  }
}

provider "aws" {
  region = "${region}"
  default_tags {
    tags = {
      ManagedBy   = "Terraform"
      Environment = "${env}"
      Stack       = "${stack_name}"
      Org         = "${org_name}"
    }
  }
}

locals {
  org_name     = "${org_name.toLowerCase().split(" ").join("-")}"
  stack_name   = "${stack_name}"
  region       = "${region}"
  region_code  = "${region_code}"
  env          = "${env}"
  cidr         = "${cidr}"
  hub_cidr     = "${hub_cidr}"
  amazon_asn   = ${amazon_asn}
  customer_asn = ${customer_asn}
  azs          = ${tfList(azs)}
  dx_prefixes  = ${tfList(dx_prefixes)}
}

# ── Transit Gateway ─────────────────────────────────────────
module "tgw" {
  source  = "../../../../modules/aws-tgw-hub"
  version = "~> 2.0"

  org_name     = local.org_name
  stack_name   = local.stack_name
  region       = local.region
  region_code  = local.region_code
  env          = local.env
  cidr         = local.cidr
  hub_cidr     = local.hub_cidr
  amazon_asn   = local.amazon_asn
  customer_asn = local.customer_asn
  azs          = local.azs
  dx_prefixes  = local.dx_prefixes

  # Route table attachment IDs (populated after attachment)
  enable_inspection_vpc   = true
  enable_shared_services  = true
  inspection_vpc_cidr     = local.hub_cidr
  gwlb_target_group_arn   = module.inspection.gwlb_target_group_arn
}

# ── Inspection VPC (PA VM-Series behind GWLB) ────────────────
module "inspection" {
  source = "../../../../modules/aws-inspection-vpc"

  org_name   = local.org_name
  vpc_cidr   = local.hub_cidr
  region     = local.region
  azs        = local.azs

  # PA VM-Series AMI — set via SSM param
  pa_ami_id  = data.aws_ssm_parameter.pa_ami.value
  pa_version = "11.1"
}

# ── Direct Connect Gateway ───────────────────────────────────
resource "aws_dx_gateway" "main" {
  name            = "\${local.org_name}-dxgw-\${local.region_code}"
  amazon_side_asn = local.amazon_asn
}

resource "aws_dx_gateway_association" "tgw" {
  dx_gateway_id         = aws_dx_gateway.main.id
  associated_gateway_id = module.tgw.tgw_id
  allowed_prefixes      = local.dx_prefixes
}

# ── TGW Route Tables ─────────────────────────────────────────
# prod — all prod VPC attachments; routes to inspection first
resource "aws_ec2_transit_gateway_route_table" "prod" {
  transit_gateway_id = module.tgw.tgw_id
  tags = { Name = "\${local.org_name}-tgw-rt-prod" }
}

# nonprod
resource "aws_ec2_transit_gateway_route_table" "nonprod" {
  transit_gateway_id = module.tgw.tgw_id
  tags = { Name = "\${local.org_name}-tgw-rt-nonprod" }
}

# shared-services
resource "aws_ec2_transit_gateway_route_table" "shared" {
  transit_gateway_id = module.tgw.tgw_id
  tags = { Name = "\${local.org_name}-tgw-rt-shared" }
}

# inspection (GWLB hairpin)
resource "aws_ec2_transit_gateway_route_table" "inspection" {
  transit_gateway_id = module.tgw.tgw_id
  tags = { Name = "\${local.org_name}-tgw-rt-inspection" }
}

# ── PA AMI lookup ────────────────────────────────────────────
data "aws_ssm_parameter" "pa_ami" {
  name = "/aws/service/marketplace/prod-pa-vm-series/11.1/ami-id"
}

# ── Outputs ──────────────────────────────────────────────────
output "tgw_id" {
  value       = module.tgw.tgw_id
  description = "Transit Gateway ID"
}

output "dxgw_id" {
  value       = aws_dx_gateway.main.id
  description = "Direct Connect Gateway ID"
}

output "inspection_vpc_id" {
  value       = module.inspection.vpc_id
  description = "Inspection VPC ID"
}

output "tgw_rt_prod_id" {
  value       = aws_ec2_transit_gateway_route_table.prod.id
  description = "TGW Prod route table ID"
}

output "tgw_rt_nonprod_id" {
  value       = aws_ec2_transit_gateway_route_table.nonprod.id
  description = "TGW NonProd route table ID"
}
`
}

export function generateAzureTerraform(opts: CloudTerraformOpts = {}): string {
  const org_name = opts.orgName ?? 'NetDesignAI'
  const location = opts.region ?? DEFAULT_REGION.azure
  const org_slug = slug(org_name)
  const stack_name = `${org_slug}-vwan`
  const region_code = regionCode(location)
  const env = opts.env ?? 'prod'
  const cidr = opts.orgCidr ?? '10.0.0.0/8'
  const hub_cidr = opts.hubCidr ?? '10.254.0.0/16'
  const er_asn = opts.erAsn ?? opts.bgpAsn ?? 65515
  const rg_name = opts.azureRg ?? `${org_slug}-network-rg`
  return `
# ═══════════════════════════════════════════════════════════
# Stack    : ${stack_name}
# Location : ${location}
# Org      : ${org_name}
# Env      : ${env}
# Generated by NetDesign AI — multicloud use case
# ═══════════════════════════════════════════════════════════

terraform {
  required_version = ">= 1.6"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90"
    }
  }
  backend "azurerm" {
    resource_group_name  = "${rg_name}-tfstate"
    storage_account_name = "${org_name.toLowerCase().split(" ").join("").split("-").join("").slice(0, 20)}tfstate"
    container_name       = "tfstate"
    key                  = "network/${stack_name}/terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
}

locals {
  org_name    = "${org_name}"
  stack_name  = "${stack_name}"
  location    = "${location}"
  region_code = "${region_code}"
  env         = "${env}"
  cidr        = "${cidr}"
  hub_cidr    = "${hub_cidr}"
  er_asn      = ${er_asn}
  rg_name     = "${rg_name}"
}

# ── Resource Group ────────────────────────────────────────────
resource "azurerm_resource_group" "network" {
  name     = local.rg_name
  location = local.location
  tags = {
    ManagedBy   = "Terraform"
    Environment = local.env
    Org         = local.org_name
  }
}

# ── vWAN + vHub ───────────────────────────────────────────────
module "vwan" {
  source  = "../../../../modules/azure-vwan-hub"
  version = "~> 2.0"

  org_name          = local.org_name
  resource_group_id = azurerm_resource_group.network.id
  location          = local.location
  env               = local.env
  hub_cidr          = local.hub_cidr
  er_asn            = local.er_asn

  # Azure Firewall Premium — routing intent
  enable_azure_firewall       = true
  firewall_sku_tier           = "Premium"
  enable_routing_intent       = true
  routing_intent_destinations = ["Internet", "PrivateTraffic"]
}

# ── ExpressRoute Gateway ──────────────────────────────────────
module "er_gateway" {
  source = "../../../../modules/azure-er-gateway"

  resource_group_id = azurerm_resource_group.network.id
  location          = local.location
  virtual_hub_id    = module.vwan.virtual_hub_id
  er_sku            = "ErGw3AZ"
}

# ── Azure Firewall Policy (Premium) ──────────────────────────
resource "azurerm_firewall_policy" "premium" {
  name                = "\${local.org_name}-fwpol-\${local.region_code}"
  resource_group_name = azurerm_resource_group.network.name
  location            = local.location
  sku                 = "Premium"

  threat_intelligence_mode = "Alert"
  intrusion_detection {
    mode = "Alert"
  }
}

# ── Spoke VNet peering to vHub ────────────────────────────────
# (Spoke VNets connect via module.vwan virtual_hub_connection)

# ── Outputs ───────────────────────────────────────────────────
output "vwan_id" {
  value       = module.vwan.vwan_id
  description = "Virtual WAN ID"
}

output "virtual_hub_id" {
  value       = module.vwan.virtual_hub_id
  description = "Virtual Hub ID"
}

output "er_gateway_id" {
  value       = module.er_gateway.gateway_id
  description = "ExpressRoute Gateway ID"
}

output "firewall_private_ip" {
  value       = module.vwan.firewall_private_ip
  description = "Azure Firewall Premium private IP"
}

output "firewall_policy_id" {
  value       = azurerm_firewall_policy.premium.id
  description = "Azure Firewall Policy (Premium) ID"
}

output "resource_group_id" {
  value       = azurerm_resource_group.network.id
  description = "Network resource group ID"
}
`
}

export function generateGcpTerraform(opts: CloudTerraformOpts = {}): string {
  const org_name = opts.orgName ?? 'NetDesignAI'
  const region = opts.region ?? DEFAULT_REGION.gcp
  const org_slug = slug(org_name)
  const stack_name = `${org_slug}-ncc`
  const region_code = regionCode(region)
  const env = opts.env ?? 'prod'
  const cidr = opts.orgCidr ?? '10.0.0.0/8'
  const hub_cidr = opts.hubCidr ?? '10.254.0.0/16'
  const project = opts.gcpProject ?? `${org_slug}-network`
  const cloud_router_asn = opts.cloudRouterAsn ?? opts.bgpAsn ?? 65000
  return `
# ═══════════════════════════════════════════════════════════
# Stack   : ${stack_name}
# Region  : ${region}
# Project : ${project}
# Org     : ${org_name}
# Env     : ${env}
# Generated by NetDesign AI — multicloud use case
# ═══════════════════════════════════════════════════════════

terraform {
  required_version = ">= 1.6"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
  backend "gcs" {
    bucket = "${org_name.toLowerCase().split(" ").join("-")}-tf-state"
    prefix = "network/${stack_name}"
  }
}

provider "google" {
  project = "${project}"
  region  = "${region}"
}

locals {
  org_name         = "${org_name}"
  stack_name       = "${stack_name}"
  project          = "${project}"
  region           = "${region}"
  region_code      = "${region_code}"
  env              = "${env}"
  cidr             = "${cidr}"
  hub_cidr         = "${hub_cidr}"
  cloud_router_asn = ${cloud_router_asn}
}

# ── NCC Hub + Host VPC ────────────────────────────────────────
module "ncc" {
  source  = "../../../../modules/gcp-ncc-hub"
  version = "~> 2.0"

  org_name         = local.org_name
  project          = local.project
  region           = local.region
  env              = local.env
  cidr             = local.cidr
  hub_cidr         = local.hub_cidr
  cloud_router_asn = local.cloud_router_asn

  # Cloud NGFW
  enable_cloud_ngfw = true
  ngfw_tier         = "STANDARD"
  enable_cloud_nat  = true
}

# ── Cloud Interconnect VLAN attachments ──────────────────────
module "interconnect" {
  source = "../../../../modules/gcp-cloud-interconnect"

  project    = local.project
  region     = local.region
  router_id  = module.ncc.cloud_router_id
  vlan_cidr  = "169.254.20.0/29"
  peer_asn   = 65000
  bandwidth  = "BPS_10G"
  redundancy = "REDUNDANT"
}

# ── NCC Spoke Hub Connections ─────────────────────────────────
resource "google_network_connectivity_hub" "main" {
  name        = "\${local.org_name}-ncc-hub-\${local.region_code}"
  description = "NCC Hub for \${local.org_name} \${local.region}"
  project     = local.project
}

# ── Cloud NAT (for outbound from private subnets) ────────────
resource "google_compute_router_nat" "main" {
  name                               = "\${local.org_name}-nat-\${local.region_code}"
  router                             = module.ncc.cloud_router_name
  region                             = local.region
  project                            = local.project
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"

  log_config {
    enable = true
    filter = "ERRORS_ONLY"
  }
}

# ── Firewall rules (Cloud NGFW base) ─────────────────────────
resource "google_compute_firewall" "allow_iap" {
  name    = "\${local.org_name}-allow-iap-\${local.region_code}"
  network = module.ncc.host_vpc_id
  project = local.project

  allow {
    protocol = "tcp"
    ports    = ["22", "3389"]
  }
  source_ranges = ["35.235.240.0/20"]
  target_tags   = ["iap-access"]
  description   = "Allow IAP tunnel access"
}

resource "google_compute_firewall" "allow_internal" {
  name    = "\${local.org_name}-allow-internal-\${local.region_code}"
  network = module.ncc.host_vpc_id
  project = local.project

  allow {
    protocol = "all"
  }
  source_ranges = [local.cidr]
  description   = "Allow all internal traffic from org CIDR"
}

# ── Outputs ───────────────────────────────────────────────────
output "ncc_hub_id" {
  value       = module.ncc.hub_id
  description = "NCC Hub ID"
}

output "cloud_router_id" {
  value       = module.ncc.cloud_router_id
  description = "Cloud Router ID"
}

output "host_vpc_id" {
  value       = module.ncc.host_vpc_id
  description = "Host VPC ID"
}

output "interconnect_attachment_ids" {
  value       = module.interconnect.attachment_ids
  description = "Cloud Interconnect VLAN attachment IDs"
}

output "google_ncc_hub_id" {
  value       = google_network_connectivity_hub.main.id
  description = "Google NCC Hub resource ID"
}
`
}

const GENERATORS: Record<CloudProvider, (o: CloudTerraformOpts) => string> = {
  aws: generateAwsTerraform,
  azure: generateAzureTerraform,
  gcp: generateGcpTerraform,
}

/**
 * Stacks for a design. Mirrors the backend dispatcher: a `multicloud` use
 * case emits all three providers, otherwise only those explicitly selected.
 */
export function buildCloudTerraform(
  useCase: string,
  cloudProviders: string[] = [],
  opts: CloudTerraformOpts = {},
): Record<string, string> {
  const all = useCase === 'multicloud'
  const selected = new Set(cloudProviders.map(p => p.toLowerCase()))
  const out: Record<string, string> = {}
  for (const p of ['aws', 'azure', 'gcp'] as CloudProvider[]) {
    if (all || selected.has(p)) out[p] = GENERATORS[p](opts)
  }
  return out
}

/** Filename Terraform expects for a provider stack. */
export function cloudTerraformFilename(provider: string): string {
  return `${provider}-hub.tf`
}
