/**
 * configgen.ts — Device configuration generators
 *
 * Design rules (enforced here):
 *  1. Each function emits ONE complete, self-contained config block — no
 *     "POLICY BLOCKS appended" sections that duplicate AAA/SNMP/NTP.
 *  2. Underlay = IS-IS for DC/GPU spine-leaf; OSPF for campus/WAN.
 *     Never both simultaneously.
 *  3. All credentials use <CHANGE-ME-*> placeholders. Never commit real secrets.
 *  4. Firewall roles produce zone-based / vendor-native configs, not router configs.
 *  5. GPU QoS includes ECN, WRED, PFC priority-3, DCQCN buffer carving.
 */

import type { BOMDevice, UseCase } from '@/types'

// ── Shared helpers ─────────────────────────────────────────────────────────────

/** Single management block used exactly once per config. */
function mgmtBlock(hostname: string, mgmtVlan = 10): string {
  return `
! ── MANAGEMENT ──────────────────────────────────────────────────────────────────
hostname ${hostname}
!
ip domain-name <CHANGE-ME-domain.example.com>
ip name-server 8.8.8.8
service timestamps log datetime msec localtime show-timezone
service timestamps debug datetime msec
service password-encryption
no service pad
no ip http server
ip http secure-server
ip http authentication aaa
no ip source-route
no ip bootp server
login block-for 60 attempts 5 within 30
login delay 2
!
banner motd ^
*******************************************************************************
*  ${hostname} — Authorized access only.  All activity is monitored.        *
*  Disconnect IMMEDIATELY if not an authorized user.                           *
*******************************************************************************
^
!
ip access-list standard MGMT-ACL
 permit <CHANGE-ME-mgmt-subnet> 0.0.0.255
 deny   any log
!
! Credentials — replace placeholders before deploying
username admin privilege 15 algorithm-type sha256 secret <CHANGE-ME-admin-password>
enable  algorithm-type sha256 secret <CHANGE-ME-enable-secret>
!
aaa new-model
!
tacacs server TACACS-PRIMARY
 address ipv4 <CHANGE-ME-tacacs-primary-ip>
 key <CHANGE-ME-tacacs-key>
 timeout 3
 single-connection
!
tacacs server TACACS-SECONDARY
 address ipv4 <CHANGE-ME-tacacs-secondary-ip>
 key <CHANGE-ME-tacacs-key>
 timeout 3
!
aaa group server tacacs+ TACACS-GROUP
 server name TACACS-PRIMARY
 server name TACACS-SECONDARY
 ip tacacs source-interface Vlan${mgmtVlan}
!
aaa authentication login default group TACACS-GROUP local
aaa authentication enable default group TACACS-GROUP enable
aaa authorization console
aaa authorization exec     default group TACACS-GROUP local if-authenticated
aaa authorization commands  1 default group TACACS-GROUP local if-authenticated
aaa authorization commands 15 default group TACACS-GROUP local if-authenticated
aaa accounting exec     default start-stop group TACACS-GROUP
aaa accounting commands  1 default start-stop group TACACS-GROUP
aaa accounting commands 15 default start-stop group TACACS-GROUP
!
! SNMP v3 only — no community strings
no snmp-server system-shutdown
snmp-server view NETDESIGN-VIEW iso included
snmp-server group NETDESIGN-RO v3 priv read  NETDESIGN-VIEW
snmp-server group NETDESIGN-RW v3 priv write NETDESIGN-VIEW
snmp-server user netmon NETDESIGN-RO v3 auth sha <CHANGE-ME-snmp-auth-pass> priv aes 128 <CHANGE-ME-snmp-priv-pass>
snmp-server host <CHANGE-ME-nms-ip> traps version 3 priv netmon
snmp-server enable traps bgp
snmp-server enable traps envmon
snmp-server enable traps interface
!
ntp authenticate
ntp authentication-key 1 md5 <CHANGE-ME-ntp-key>
ntp trusted-key 1
ntp source Vlan${mgmtVlan}
ntp server <CHANGE-ME-ntp-primary> prefer key 1
ntp server <CHANGE-ME-ntp-secondary> key 1
clock timezone UTC 0 0
!
logging host <CHANGE-ME-syslog-ip>
logging trap informational
logging source-interface Vlan${mgmtVlan}
!
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 3
ip ssh source-interface Vlan${mgmtVlan}
!
line vty 0 15
 access-class MGMT-ACL in
 exec-timeout 10 0
 transport input ssh
 logging synchronous
!`
}

// ── NX-OS Spine ───────────────────────────────────────────────────────────────

function nxosSpineConfig(dev: BOMDevice, idx: number, isGpu: boolean): string {
  const spineAsn = 65000
  const routerId = `10.255.1.${idx + 1}`
  const isisNet  = `49.0001.0102.5500.${String(idx + 1).padStart(4, '0')}.00`

  // GPU fabric: ECN + DCQCN + PFC lossless queuing.
  // Non-GPU: standard 4-class DSCP queuing.
  const qosBlock = isGpu ? nxosGpuQoS() : nxosStdQoS()

  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : DC Spine (Route-Reflector + IS-IS ABR)
! Model  : ${dev.model}
! Vendor : ${dev.vendor}
! Generated by NetDesign AI — $(date -u +%Y-%m-%dT%H:%MZ)
! IMPORTANT: Replace all <CHANGE-ME-*> tokens before deploying.
! ═══════════════════════════════════════════════════════════════

version 10.3(x) Bios:version
!
hostname ${dev.hostname}
!
! ── FEATURES ────────────────────────────────────────────────────────────────────
feature isis
feature bgp
feature pim
feature nxapi
feature interface-vlan
feature vn-segment-vlan-based
feature nv overlay
feature lldp
feature lacp
feature telemetry
!
! ── MANAGEMENT ──────────────────────────────────────────────────────────────────
ip domain-name <CHANGE-ME-domain.example.com>
ip name-server <CHANGE-ME-dns-ip>
!
banner motd ^
*******************************************************************************
*  ${dev.hostname} — Authorized access only. All sessions are monitored.    *
*  Disconnect immediately if not an authorized user.                           *
*******************************************************************************
^
!
username admin privilege 15 role network-admin password 5 <CHANGE-ME-admin-password>
!
aaa new-model
tacacs-server host <CHANGE-ME-tacacs-primary-ip> key <CHANGE-ME-tacacs-key>
tacacs-server host <CHANGE-ME-tacacs-secondary-ip> key <CHANGE-ME-tacacs-key>
aaa group server tacacs+ TACACS-GROUP
  server <CHANGE-ME-tacacs-primary-ip>
  server <CHANGE-ME-tacacs-secondary-ip>
aaa authentication login default group TACACS-GROUP local
aaa authorization exec default group TACACS-GROUP local
aaa accounting default group TACACS-GROUP
!
snmp-server user netmon network-operator auth sha <CHANGE-ME-snmp-auth-pass> priv <CHANGE-ME-snmp-priv-pass>
!
ntp server <CHANGE-ME-ntp-primary> prefer
ntp server <CHANGE-ME-ntp-secondary>
ntp source-interface mgmt0
!
logging server <CHANGE-ME-syslog-ip> 6 use-vrf management
logging source-interface mgmt0
!
ssh version 2
ip ssh source-interface mgmt0
!
! ── MANAGEMENT VRF ───────────────────────────────────────────────────────────
vrf context management
  ip route 0.0.0.0/0 <CHANGE-ME-oob-gateway>
!
interface mgmt0
  vrf member management
  ip address <CHANGE-ME-mgmt-ip>/24
  no shutdown
!
! ── LOOPBACK INTERFACES ───────────────────────────────────────────────────────
interface loopback0
  description ROUTER-ID / BGP / IS-IS SOURCE
  ip address ${routerId}/32
  ip router isis 1
  no shutdown
!
! ── UNDERLAY: IS-IS (single protocol — not combined with OSPF) ───────────────
! IS-IS is selected for DC spine-leaf: faster convergence, no DR election,
! lower overhead than OSPF in large-scale flat networks.
router isis 1
  net ${isisNet}
  is-type level-2-only
  address-family ipv4 unicast
    maximum-paths 64
    redistribute direct route-map CONNECTED-TO-ISIS
  log-adjacency-changes
  metric-style transition
!
! ── BGP / EVPN OVERLAY ───────────────────────────────────────────────────────
router bgp ${spineAsn}
  router-id ${routerId}
  log-neighbor-changes
  address-family ipv4 unicast
    maximum-paths ibgp 64
    redistribute direct route-map CONNECTED-TO-BGP
  address-family l2vpn evpn
    retain route-target all
  !
  template peer LEAF-RR-CLIENT
    remote-as ${spineAsn}
    update-source loopback0
    timers 3 9
    address-family ipv4 unicast
      route-reflector-client
      soft-reconfiguration inbound always
    address-family l2vpn evpn
      route-reflector-client
      send-community both
  !
  ! Add one neighbor entry per leaf:
  ! neighbor 10.255.2.1 inherit peer LEAF-RR-CLIENT
!
! ── SPINE FABRIC INTERFACES (adjust per cabling matrix) ─────────────────────
! interface Ethernet1/1
!   description DOWNLINK: <CHANGE-ME-leaf-hostname> Eth49/1
!   no switchport
!   mtu 9216
!   ip address <CHANGE-ME-p2p-ip>/31
!   ip router isis 1
!   isis network point-to-point
!   isis metric 10
!   no shutdown
!
${qosBlock}
!
! ── TELEMETRY (gRPC to collector) ────────────────────────────────────────────
telemetry
  destination-group 1
    ip address <CHANGE-ME-telemetry-collector-ip> port 57500 protocol gRPC encoding GPB
  sensor-group 1
    data-source NX-API
    path sys/intf depth unbounded
  sensor-group 2
    data-source NX-API
    path sys/bgp depth unbounded
  sensor-group 3
    data-source NX-API
    path sys/isis depth unbounded
  subscription 1
    dst-grp 1
    snsr-grp 1 sample-interval 10000
    snsr-grp 2 sample-interval 30000
    snsr-grp 3 sample-interval 30000
!
! ── ROUTE MAPS ───────────────────────────────────────────────────────────────
route-map CONNECTED-TO-ISIS permit 10
  match tag 100
route-map CONNECTED-TO-BGP  permit 10
  match ip address prefix-list LOOPBACKS
ip prefix-list LOOPBACKS seq 5 permit 10.255.0.0/16 ge 32
`
}

// ── NX-OS Leaf ────────────────────────────────────────────────────────────────

function nxosLeafConfig(dev: BOMDevice, idx: number, isGpu: boolean): string {
  const leafAsn  = 65001 + idx
  const routerId = `10.255.2.${idx + 1}`
  const vtepIp   = `10.254.0.${idx + 1}`
  const isisNet  = `49.0001.0102.5501.${String(idx + 1).padStart(4, '0')}.00`
  const qosBlock = isGpu ? nxosGpuQoS() : nxosStdQoS()

  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : DC Leaf (ToR / VTEP)
! Model  : ${dev.model}
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

version 10.3(x) Bios:version
!
hostname ${dev.hostname}
!
feature isis
feature bgp
feature vn-segment-vlan-based
feature nv overlay
feature interface-vlan
feature lacp
feature vpc
feature lldp
feature telemetry
!
username admin privilege 15 role network-admin password 5 <CHANGE-ME-admin-password>
!
aaa new-model
tacacs-server host <CHANGE-ME-tacacs-primary-ip> key <CHANGE-ME-tacacs-key>
tacacs-server host <CHANGE-ME-tacacs-secondary-ip> key <CHANGE-ME-tacacs-key>
aaa group server tacacs+ TACACS-GROUP
  server <CHANGE-ME-tacacs-primary-ip>
  server <CHANGE-ME-tacacs-secondary-ip>
aaa authentication login default group TACACS-GROUP local
aaa authorization exec default group TACACS-GROUP local
aaa accounting default group TACACS-GROUP
!
ntp server <CHANGE-ME-ntp-primary> prefer
ntp server <CHANGE-ME-ntp-secondary>
ntp source-interface mgmt0
!
logging server <CHANGE-ME-syslog-ip> 6 use-vrf management
!
! ── MANAGEMENT VRF ───────────────────────────────────────────────────────────
vrf context management
  ip route 0.0.0.0/0 <CHANGE-ME-oob-gateway>
!
interface mgmt0
  vrf member management
  ip address <CHANGE-ME-mgmt-ip>/24
  no shutdown
!
! ── TENANT VRF / VNI (example — replicate per tenant) ────────────────────────
vrf context TENANT-A
  vni 50000
  rd auto
  address-family ipv4 unicast
    route-target both auto evpn
!
vlan 10
  name SERVERS
  vn-segment 10010
!
! ── LOOPBACKS ────────────────────────────────────────────────────────────────
interface loopback0
  description ROUTER-ID / BGP SOURCE
  ip address ${routerId}/32
  ip router isis 1
  no shutdown
!
interface loopback1
  description VTEP SOURCE
  ip address ${vtepIp}/32
  ip router isis 1
  no shutdown
!
! ── UNDERLAY: IS-IS only (no OSPF — one routing protocol per domain) ─────────
router isis 1
  net ${isisNet}
  is-type level-2-only
  address-family ipv4 unicast
    maximum-paths 64
  log-adjacency-changes
  metric-style transition
!
! ── BGP / EVPN ───────────────────────────────────────────────────────────────
router bgp ${leafAsn}
  router-id ${routerId}
  log-neighbor-changes
  address-family ipv4 unicast
    network ${routerId}/32
    network ${vtepIp}/32
    maximum-paths ibgp 64
  address-family l2vpn evpn
  !
  template peer SPINE-RR
    remote-as 65000
    update-source loopback0
    timers 3 9
    address-family ipv4 unicast
      soft-reconfiguration inbound always
    address-family l2vpn evpn
      send-community both
  !
  ! neighbor <CHANGE-ME-spine1-loopback0> inherit peer SPINE-RR
  ! neighbor <CHANGE-ME-spine2-loopback0> inherit peer SPINE-RR
!
! ── VXLAN NVE (VTEP) ─────────────────────────────────────────────────────────
interface nve1
  no shutdown
  host-reachability protocol bgp
  source-interface loopback1
  member vni 10010 associate-vrf
  member vni 50000
    ingress-replication protocol bgp
!
! ── UPLINKS (adjust per cabling matrix) ──────────────────────────────────────
! interface Ethernet49/1
!   description UPLINK: <CHANGE-ME-spine1-hostname> Eth1/N
!   no switchport
!   mtu 9216
!   ip address <CHANGE-ME-p2p-ip>/31
!   ip router isis 1
!   isis network point-to-point
!   isis metric 10
!   no shutdown
!
${qosBlock}
!
! ── vPC PEER-LINK (if dual-ToR) ──────────────────────────────────────────────
vpc domain ${idx + 1}
  peer-keepalive destination <CHANGE-ME-peer-mgmt-ip> source <CHANGE-ME-local-mgmt-ip> vrf management
  peer-gateway
  auto-recovery
  delay restore 150
!
telemetry
  destination-group 1
    ip address <CHANGE-ME-telemetry-collector-ip> port 57500 protocol gRPC encoding GPB
  sensor-group 1
    data-source NX-API
    path sys/intf depth unbounded
  sensor-group 2
    data-source NX-API
    path sys/bgp depth unbounded
  subscription 1
    dst-grp 1
    snsr-grp 1 sample-interval 10000
    snsr-grp 2 sample-interval 30000
`
}

// ── NX-OS QoS blocks ──────────────────────────────────────────────────────────

function nxosStdQoS(): string {
  return `! ── QoS — Standard 4-class DSCP (non-GPU) ──────────────────────────────────
class-map type qos match-any CM-VOICE
  match dscp ef
class-map type qos match-any CM-VIDEO
  match dscp af41 af42
class-map type qos match-any CM-CRITICAL
  match dscp af31 af32 cs3
class-map type qos match-any CM-BULK
  match dscp af11 af12 cs1
!
class-map type queuing CM-VOICE-Q
  match qos-group 6
class-map type queuing CM-VIDEO-Q
  match qos-group 5
class-map type queuing CM-CRITICAL-Q
  match qos-group 4
!
policy-map type qos PM-INGRESS-CLASSIFY
  class CM-VOICE
    set qos-group 6
  class CM-VIDEO
    set qos-group 5
  class CM-CRITICAL
    set qos-group 4
  class class-default
    set qos-group 0
!
policy-map type queuing PM-EGRESS-QUEUING
  class type queuing CM-VOICE-Q
    priority percent 15
  class type queuing CM-VIDEO-Q
    bandwidth percent 20
  class type queuing CM-CRITICAL-Q
    bandwidth percent 30
  class type queuing class-default
    bandwidth percent 35
    random-detect dscp-based
!
system qos
  service-policy type qos      input PM-INGRESS-CLASSIFY
  service-policy type queuing  output PM-EGRESS-QUEUING`
}

function nxosGpuQoS(): string {
  return `! ── QoS — GPU/RoCEv2 Fabric (IS-IS underlay, ECN + DCQCN + PFC) ────────────
! Priority mapping:
!   PFC priority 3 → RoCEv2 / RDMA (lossless, no-drop)
!   PFC priority 6 → Storage (FCoE/NVMe-oF, lossless)
!   PFC priority 0-2,4,5,7 → lossy (ECN-marked)
!
! DSCP → qos-group mapping:
!   DSCP 26 (AF31) — RoCEv2 → qos-group 3 (PFC priority 3, lossless)
!   DSCP 46 (EF)   — Voice/ctrl → qos-group 6
!   DSCP 34 (AF41) — Video  → qos-group 5
!   DSCP  0 (CS0)  — Default → qos-group 0
!
class-map type qos match-any CM-RDMA
  match dscp 26 28
class-map type qos match-any CM-STORAGE
  match dscp 24 16
class-map type qos match-any CM-VOICE
  match dscp 46
class-map type qos match-any CM-VIDEO
  match dscp 34 32
class-map type qos match-any CM-BULK
  match dscp 10 12
class-map type qos match-any CM-SCAVENGER
  match dscp 8
!
class-map type queuing CM-RDMA-Q
  match qos-group 3
class-map type queuing CM-STORAGE-Q
  match qos-group 6
class-map type queuing CM-VOICE-Q
  match qos-group 5
class-map type queuing CM-VIDEO-Q
  match qos-group 4
class-map type queuing CM-BULK-Q
  match qos-group 1
!
policy-map type qos PM-INGRESS-CLASSIFY
  class CM-RDMA
    set qos-group 3
    set dscp 26
  class CM-STORAGE
    set qos-group 6
  class CM-VOICE
    set qos-group 5
  class CM-VIDEO
    set qos-group 4
  class CM-BULK
    set qos-group 1
  class CM-SCAVENGER
    set qos-group 0
    set dscp 8
  class class-default
    set qos-group 0
!
! Egress queuing — buffer carving:
!   RDMA   : 60% guaranteed BW, PFC enabled (lossless)
!   Storage: 10% guaranteed BW, PFC enabled (lossless)
!   Lossy  : remaining BW with ECN + WRED for congestion isolation
policy-map type queuing PM-EGRESS-QUEUING
  class type queuing CM-RDMA-Q
    bandwidth percent 60
    pause buffer-size 300
  class type queuing CM-STORAGE-Q
    bandwidth percent 10
    pause buffer-size 150
  class type queuing CM-VOICE-Q
    priority percent 5
  class type queuing CM-VIDEO-Q
    bandwidth percent 10
    random-detect dscp-based
    random-detect dscp 34 minimum-threshold 2000 maximum-threshold 8000
  class type queuing CM-BULK-Q
    bandwidth percent 5
    random-detect dscp-based
    random-detect dscp 10 minimum-threshold 500  maximum-threshold 4000
  class type queuing class-default
    bandwidth percent 10
    random-detect dscp-based
    random-detect dscp 0 minimum-threshold 1000 maximum-threshold 6000
!
! Network-QoS: PFC lossless + ECN on congestion queues
! PFC priority 3 = RDMA (RoCEv2), priority 6 = storage
policy-map type network-qos PM-PFC-LOSSLESS
  class type network-qos CM-RDMA-Q
    pause no-drop
    mtu 9216
    congestion-control ecn
  class type network-qos CM-STORAGE-Q
    pause no-drop
    mtu 9216
  class type network-qos CM-VIDEO-Q
    congestion-control ecn
    mtu 9216
  class type network-qos CM-BULK-Q
    congestion-control ecn
    mtu 9216
  class type network-qos class-default
    congestion-control ecn
    mtu 9216
!
system qos
  service-policy type qos         input PM-INGRESS-CLASSIFY
  service-policy type queuing     output PM-EGRESS-QUEUING
  service-policy type network-qos PM-PFC-LOSSLESS
!
! ── DCQCN parameters (RoCEv2 congestion control) ────────────────────────────
! These must be consistent across ALL switches in the GPU fabric.
! Adjust thresholds to match actual ASIC buffer size (see vendor datasheet).
hardware qos dcbx default
hardware qos pfc-watchdog on
hardware profile forwarding-mode fabricpath
!
! Per-port PFC/ECN settings (apply to every GPU-connected interface):
! interface Ethernet<N>
!   priority-flow-control mode on
!   priority-flow-control watch-dog-interval on
!   congestion-control ecn mark
!   no flowcontrol receive off
!   no flowcontrol send off`
}

// ── Arista EOS ────────────────────────────────────────────────────────────────

function aristaSpineConfig(dev: BOMDevice, idx: number, isGpu: boolean): string {
  const asn      = 65000
  const routerId = `10.255.1.${idx + 1}`
  const isisNet  = `0101.0255.000${idx + 1}`
  const qos      = isGpu ? aristaGpuQoS() : ''

  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : DC Spine
! OS     : Arista EOS
! Model  : ${dev.model}
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

hostname ${dev.hostname}
!
! ── MANAGEMENT ──────────────────────────────────────────────────────────────
ip domain-name <CHANGE-ME-domain.example.com>
dns server <CHANGE-ME-dns-ip>
!
username admin privilege 15 role network-admin secret sha512 <CHANGE-ME-admin-password>
!
aaa authentication login default group tacacs+ local
aaa authorization exec default group tacacs+ local
aaa accounting exec default start-stop group tacacs+
!
tacacs-server host <CHANGE-ME-tacacs-primary-ip> key <CHANGE-ME-tacacs-key>
tacacs-server host <CHANGE-ME-tacacs-secondary-ip> key <CHANGE-ME-tacacs-key>
!
snmp-server engineID local f5717f000001
snmp-server user NETDESIGN-USER priv-v3 auth sha <CHANGE-ME-snmp-auth-pass> priv aes <CHANGE-ME-snmp-priv-pass>
!
ntp server <CHANGE-ME-ntp-primary> prefer iburst
ntp server <CHANGE-ME-ntp-secondary> iburst
ntp source Management1
!
logging host <CHANGE-ME-syslog-ip>
logging source-interface Management1
!
management ssh
  idle-timeout 10
  authentication mode password
!
! ── MANAGEMENT INTERFACE ─────────────────────────────────────────────────────
interface Management1
  description OOB-MANAGEMENT
  ip address <CHANGE-ME-mgmt-ip>/24
!
ip route vrf MGMT 0.0.0.0/0 <CHANGE-ME-oob-gateway>
!
! ── ROUTING: IS-IS underlay (single protocol — no OSPF) ─────────────────────
service routing protocols model multi-agent
!
router isis UNDERLAY
  net 49.0001.${isisNet}.00
  is-type level-2
  address-family ipv4 unicast
    maximum-paths 64
    fast-reroute ti-lfa
!
! ── LOOPBACK ────────────────────────────────────────────────────────────────
interface Loopback0
  description ROUTER-ID / BGP SOURCE
  ip address ${routerId}/32
  isis enable UNDERLAY
  isis passive
!
! ── UPLINK INTERFACES (template — replicate per cabling matrix) ──────────────
! interface EthernetN
!   description DOWNLINK: <leaf-hostname>
!   no switchport
!   ip address <CHANGE-ME-p2p-ip>/31
!   isis enable UNDERLAY
!   isis network point-to-point
!   isis metric 10
!   mtu 9214
!   no shutdown
!
! ── BGP / EVPN OVERLAY ───────────────────────────────────────────────────────
router bgp ${asn}
  router-id ${routerId}
  no bgp default ipv4-unicast
  distance bgp 20 200 200
  maximum-paths 64
  graceful-restart
  !
  peer-group LEAF-RR-CLIENTS
    remote-as ${asn}
    update-source Loopback0
    bfd
    route-reflector-client
    send-community extended
    maximum-routes 12000
  !
  address-family ipv4
    neighbor LEAF-RR-CLIENTS activate
  address-family evpn
    neighbor LEAF-RR-CLIENTS activate
  !
  ! Add per-leaf neighbors:
  ! neighbor 10.255.2.N peer group LEAF-RR-CLIENTS
!
${qos}
!
! ── BANNER ───────────────────────────────────────────────────────────────────
banner login
*******************************************************************************
*  ${dev.hostname} — Authorized access only.                               *
*******************************************************************************
EOF
`
}

function aristaLeafConfig(dev: BOMDevice, idx: number, isGpu: boolean): string {
  const leafAsn  = 65001 + idx
  const routerId = `10.255.2.${idx + 1}`
  const vtepIp   = `10.254.0.${idx + 1}`
  const isisNet  = `0101.0255.000${idx + 101}`
  const qos      = isGpu ? aristaGpuQoS() : ''

  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : DC Leaf (VTEP)
! OS     : Arista EOS
! Model  : ${dev.model}
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

hostname ${dev.hostname}
!
service routing protocols model multi-agent
!
username admin privilege 15 role network-admin secret sha512 <CHANGE-ME-admin-password>
!
aaa authentication login default group tacacs+ local
aaa authorization exec default group tacacs+ local
aaa accounting exec default start-stop group tacacs+
tacacs-server host <CHANGE-ME-tacacs-primary-ip> key <CHANGE-ME-tacacs-key>
tacacs-server host <CHANGE-ME-tacacs-secondary-ip> key <CHANGE-ME-tacacs-key>
!
ntp server <CHANGE-ME-ntp-primary> prefer iburst
ntp server <CHANGE-ME-ntp-secondary> iburst
ntp source Management1
!
! ── IS-IS UNDERLAY (single protocol) ────────────────────────────────────────
router isis UNDERLAY
  net 49.0001.${isisNet}.00
  is-type level-2
  address-family ipv4 unicast
    maximum-paths 64
!
interface Loopback0
  ip address ${routerId}/32
  isis enable UNDERLAY
  isis passive
!
interface Loopback1
  description VTEP SOURCE
  ip address ${vtepIp}/32
  isis enable UNDERLAY
  isis passive
!
! ── UPLINKS to spines ────────────────────────────────────────────────────────
! interface EthernetN
!   no switchport
!   ip address <CHANGE-ME-p2p-ip>/31
!   isis enable UNDERLAY
!   isis network point-to-point
!   mtu 9214
!   no shutdown
!
! ── BGP / EVPN ───────────────────────────────────────────────────────────────
router bgp ${leafAsn}
  router-id ${routerId}
  no bgp default ipv4-unicast
  maximum-paths 4
  !
  peer-group SPINE-RR
    remote-as 65000
    update-source Loopback0
    bfd
    send-community extended
    maximum-routes 12000
  !
  neighbor <CHANGE-ME-spine1-lo0> peer group SPINE-RR
  neighbor <CHANGE-ME-spine2-lo0> peer group SPINE-RR
  !
  address-family ipv4
    neighbor SPINE-RR activate
    network ${routerId}/32
    network ${vtepIp}/32
  address-family evpn
    neighbor SPINE-RR activate
!
! ── VXLAN ────────────────────────────────────────────────────────────────────
interface Vxlan1
  description VTEP
  vxlan source-interface Loopback1
  vxlan udp-port 4789
  vxlan vlan 10 vni 10010
  vxlan learn-restrict any
!
${qos}
`
}

function aristaGpuQoS(): string {
  return `! ── QoS — Arista EOS GPU/RoCEv2 (ECN + PFC + DCQCN) ────────────────────────
! PFC priority 3 for RoCEv2, ECN on all lossy queues.
!
qos map dscp 26 28 to traffic-class 3    ! RoCEv2 → TC3 (lossless)
qos map dscp 46     to traffic-class 6    ! Voice  → TC6
qos map dscp 34 32  to traffic-class 5    ! Video  → TC5 (ECN)
qos map dscp 0      to traffic-class 0    ! Default
!
qos profile RDMA-TC3
  tx-queue 3
    bandwidth percent 60
    no priority
    pfc pause disable
  tx-queue 0
    bandwidth percent 40
    random-detect ecn
!
interface profile GPU-PORT
  pfc enable
  pfc mode on
  pfc priority 3 no-drop
  pfc priority 6 no-drop
  qos trust dscp
  qos profile RDMA-TC3
  flowcontrol receive off
  flowcontrol send off
!
! Apply profile to all GPU-connected ports:
! interface EthernetN
!   inherit profile GPU-PORT`
}

// ── Juniper QFX ───────────────────────────────────────────────────────────────

function juniperLeafConfig(dev: BOMDevice, idx: number): string {
  const leafAsn = 65001 + idx
  const lo0ip   = `10.255.2.${idx + 1}`

  return `# ═══════════════════════════════════════════════════════════════
# Device : ${dev.hostname}
# Role   : DC Leaf (ToR / VTEP)
# OS     : Juniper Junos (QFX)
# Model  : ${dev.model}
# Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
# ═══════════════════════════════════════════════════════════════

set system host-name ${dev.hostname}
set system domain-name <CHANGE-ME-domain.example.com>
set system name-server <CHANGE-ME-dns-ip>
set system login user admin class super-user authentication encrypted-password "<CHANGE-ME-admin-password>"
set system services ssh root-login deny
set system services ssh protocol-version v2
set system services netconf ssh
!
# ── AAA (single block — no duplication) ────────────────────────────────────
set system authentication-order [ tacplus password ]
set access tacacs-server <CHANGE-ME-tacacs-primary-ip> secret "<CHANGE-ME-tacacs-key>"
set access tacacs-server <CHANGE-ME-tacacs-primary-ip> single-connection
set access tacacs-server <CHANGE-ME-tacacs-secondary-ip> secret "<CHANGE-ME-tacacs-key>"
set access profile TACACS-PROFILE authentication-order tacplus
!
set system syslog host <CHANGE-ME-syslog-ip> any info
set system ntp server <CHANGE-ME-ntp-primary> prefer
set system ntp server <CHANGE-ME-ntp-secondary>
!
# ── MANAGEMENT ──────────────────────────────────────────────────────────────
set interfaces fxp0 unit 0 description "OOB-MANAGEMENT"
set interfaces fxp0 unit 0 family inet address <CHANGE-ME-mgmt-ip>/24
set routing-options static route 0.0.0.0/0 next-hop <CHANGE-ME-oob-gateway>
!
# ── LOOPBACK ────────────────────────────────────────────────────────────────
set interfaces lo0 unit 0 description "ROUTER-ID/BGP/ISIS-SOURCE"
set interfaces lo0 unit 0 family inet address ${lo0ip}/32
!
# ── UNDERLAY: IS-IS only (no OSPF) ─────────────────────────────────────────
set protocols isis interface lo0.0 passive
set protocols isis interface et-0/0/48.0 point-to-point
set protocols isis interface et-0/0/49.0 point-to-point
set protocols isis level 2 authentication-key "<CHANGE-ME-isis-auth-key>"
set protocols isis export LOOPBACKS-TO-ISIS
!
# ── BGP / EVPN ───────────────────────────────────────────────────────────────
set protocols bgp group SPINE-RR type external
set protocols bgp group SPINE-RR local-as ${leafAsn}
set protocols bgp group SPINE-RR neighbor <CHANGE-ME-spine1-lo0> peer-as 65000
set protocols bgp group SPINE-RR neighbor <CHANGE-ME-spine2-lo0> peer-as 65000
set protocols bgp group SPINE-RR multipath
set protocols bgp group SPINE-RR export LOOPBACKS-TO-BGP
set protocols bgp group SPINE-RR family evpn signaling
set protocols bgp group SPINE-RR family inet unicast
!
# ── EVPN / VXLAN ─────────────────────────────────────────────────────────────
set protocols evpn encapsulation vxlan
set protocols evpn extended-vni-list all
set protocols evpn default-gateway no-gateway-community
set switch-options vtep-source-interface lo0.0
set switch-options vrf-target target:65000:1
!
# ── POLICY ───────────────────────────────────────────────────────────────────
set policy-options policy-statement LOOPBACKS-TO-ISIS term 1 from interface lo0.0
set policy-options policy-statement LOOPBACKS-TO-ISIS term 1 then accept
set policy-options policy-statement LOOPBACKS-TO-BGP  term 1 from interface lo0.0
set policy-options policy-statement LOOPBACKS-TO-BGP  term 1 then accept
!
# ── MTU ───────────────────────────────────────────────────────────────────────
set interfaces et-0/0/0 mtu 9216
set interfaces et-0/0/1 mtu 9216
`
}

// ── Cisco Firewall (Zone-Based / FTD intent) ──────────────────────────────────

function ciscoFirewallConfig(dev: BOMDevice, _idx: number): string {
  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : Internet Perimeter Firewall (Zone-Based)
! OS     : Cisco IOS-XE (Zone-Based Firewall)
! Model  : ${dev.model}
! NOTE   : If deploying Firepower 4100/9300, this intent must be
!          realized through FMC policy deployment — the CLI below
!          is IOS-XE ZBF and illustrates the intended policy.
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

${mgmtBlock(dev.hostname, 10)}
!
! ── SECURITY ZONES ───────────────────────────────────────────────────────────
zone security OUTSIDE
  description UNTRUSTED-INTERNET
zone security DMZ
  description SEMI-TRUSTED-SERVERS
zone security INSIDE
  description TRUSTED-CORP-NETWORK
zone security MGMT
  description MANAGEMENT-PLANE
!
! ── CLASS MAPS (traffic classification) ──────────────────────────────────────
ip access-list extended ACL-INSIDE-TO-OUTSIDE
  permit ip 10.0.0.0 0.255.255.255 any
  permit ip 172.16.0.0 0.15.255.255 any
  permit ip 192.168.0.0 0.0.255.255 any
!
ip access-list extended ACL-INSIDE-TO-DMZ
  permit tcp 10.0.0.0 0.255.255.255 10.100.0.0 0.0.255.255 eq 443
  permit tcp 10.0.0.0 0.255.255.255 10.100.0.0 0.0.255.255 eq 80
!
ip access-list extended ACL-OUTSIDE-TO-DMZ
  permit tcp any 10.100.0.10 0.0.0.255 eq 443
  permit tcp any 10.100.0.10 0.0.0.255 eq 80
!
class-map type inspect match-all CM-INSIDE-TO-OUTSIDE
  match access-group name ACL-INSIDE-TO-OUTSIDE
class-map type inspect match-all CM-INSIDE-TO-DMZ
  match access-group name ACL-INSIDE-TO-DMZ
class-map type inspect match-all CM-OUTSIDE-TO-DMZ
  match access-group name ACL-OUTSIDE-TO-DMZ
!
! ── POLICY MAPS (stateful inspection per zone-pair) ──────────────────────────
policy-map type inspect PM-INSIDE-TO-OUTSIDE
  class type inspect CM-INSIDE-TO-OUTSIDE
    inspect
  class class-default
    drop log
!
policy-map type inspect PM-INSIDE-TO-DMZ
  class type inspect CM-INSIDE-TO-DMZ
    inspect
  class class-default
    drop log
!
policy-map type inspect PM-OUTSIDE-TO-DMZ
  class type inspect CM-OUTSIDE-TO-DMZ
    inspect
  class class-default
    drop log
!
! ── ZONE-PAIRS (bidirectional — explicit deny is default) ────────────────────
zone-pair security ZP-INSIDE-TO-OUTSIDE source INSIDE destination OUTSIDE
  service-policy type inspect PM-INSIDE-TO-OUTSIDE
!
zone-pair security ZP-INSIDE-TO-DMZ source INSIDE destination DMZ
  service-policy type inspect PM-INSIDE-TO-DMZ
!
zone-pair security ZP-OUTSIDE-TO-DMZ source OUTSIDE destination DMZ
  service-policy type inspect PM-OUTSIDE-TO-DMZ
!
! ── INTERFACES ───────────────────────────────────────────────────────────────
interface GigabitEthernet0/0/0
  description OUTSIDE-INTERNET
  zone-member security OUTSIDE
  ip address <CHANGE-ME-outside-ip> <CHANGE-ME-outside-mask>
  ip nat outside
  no ip proxy-arp
  no shutdown
!
interface GigabitEthernet0/0/1
  description INSIDE-CORE-SWITCH
  zone-member security INSIDE
  ip address <CHANGE-ME-inside-ip> <CHANGE-ME-inside-mask>
  ip nat inside
  no shutdown
!
interface GigabitEthernet0/0/2
  description DMZ-SERVERS
  zone-member security DMZ
  ip address <CHANGE-ME-dmz-ip> <CHANGE-ME-dmz-mask>
  no shutdown
!
! ── NAT (outside → inside PAT for INSIDE zone) ───────────────────────────────
ip nat pool INSIDE-NAT <CHANGE-ME-nat-pool-start> <CHANGE-ME-nat-pool-end> netmask 255.255.255.0
ip nat inside source route-map RM-NAT pool INSIDE-NAT overload
!
route-map RM-NAT permit 10
  match ip address ACL-INSIDE-TO-OUTSIDE
!
! ── ROUTING ───────────────────────────────────────────────────────────────────
ip route 0.0.0.0 0.0.0.0 <CHANGE-ME-default-gateway>
!
! ── IPS (if inline IDS/IPS sensor enabled) ───────────────────────────────────
! ip ips signature-category
!   category all
!     retired true
!   category ios_ips basic
!     retired false
! interface GigabitEthernet0/0/0
!   ip ips OUTSIDE-IPS in
!
! ── VRF SEGMENTATION (for multi-tenant or PCI isolation) ────────────────────
! vrf definition PCI-ZONE
!   rd 1:1
!   address-family ipv4
!     route-target export 1:1
!     route-target import 1:1
!
! ── OBJECT TRACKING (HA failover) ────────────────────────────────────────────
track 1 ip sla 1 reachability
ip sla 1
  icmp-echo <CHANGE-ME-default-gateway> source-interface GigabitEthernet0/0/0
  frequency 5
ip sla schedule 1 life forever start-time now
`
}

// ── Palo Alto PAN-OS ──────────────────────────────────────────────────────────

function paloAltoFirewallConfig(dev: BOMDevice, _idx: number): string {
  return `# ═══════════════════════════════════════════════════════════════
# Device : ${dev.hostname}
# Role   : Internet Perimeter Firewall
# OS     : Palo Alto PAN-OS
# Model  : ${dev.model}
# Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
# Syntax : PAN-OS set commands (CLI)
# ═══════════════════════════════════════════════════════════════

# ── DEVICE SETTINGS ──────────────────────────────────────────────────────────
set deviceconfig system hostname ${dev.hostname}
set deviceconfig system domain <CHANGE-ME-domain.example.com>
set deviceconfig system dns-setting servers primary <CHANGE-ME-dns-ip>
set deviceconfig system login-banner "Authorized access only. All activity monitored."
!
# ── ADMIN + AAA ──────────────────────────────────────────────────────────────
set mgt-config users admin phash <CHANGE-ME-admin-phash>
set mgt-config users admin permissions role-based superuser yes
!
set server-profile tacacs TACACS-PROFILE server TACACS-PRIMARY server-address <CHANGE-ME-tacacs-primary-ip>
set server-profile tacacs TACACS-PROFILE server TACACS-PRIMARY secret <CHANGE-ME-tacacs-key>
set server-profile tacacs TACACS-PROFILE server TACACS-SECONDARY server-address <CHANGE-ME-tacacs-secondary-ip>
set server-profile tacacs TACACS-PROFILE server TACACS-SECONDARY secret <CHANGE-ME-tacacs-key>
set server-profile tacacs TACACS-PROFILE use-radius-for-users no
!
set authentication-profile TACACS-AUTH method tacacs server-profile TACACS-PROFILE
set authentication-profile TACACS-AUTH allow-list all
set authentication-sequence TACACS-THEN-LOCAL authentication-profiles [ TACACS-AUTH ]
!
# ── SNMP / SYSLOG / NTP ───────────────────────────────────────────────────────
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address <CHANGE-ME-ntp-primary>
set deviceconfig system ntp-servers secondary-ntp-server ntp-server-address <CHANGE-ME-ntp-secondary>
!
set server-profile syslog SYSLOG-PROFILE servers SYSLOG1 server <CHANGE-ME-syslog-ip>
set server-profile syslog SYSLOG-PROFILE servers SYSLOG1 transport UDP
set server-profile syslog SYSLOG-PROFILE servers SYSLOG1 port 514
set server-profile syslog SYSLOG-PROFILE servers SYSLOG1 facility LOG_USER
!
set server-profile snmp SNMP-PROFILE version v3 users NETDESIGN-USER authpwd <CHANGE-ME-snmp-auth-pass>
set server-profile snmp SNMP-PROFILE version v3 users NETDESIGN-USER privpwd <CHANGE-ME-snmp-priv-pass>
!
# ── INTERFACES ───────────────────────────────────────────────────────────────
set network interface ethernet ethernet1/1 layer3 ipv4 addr primary ip-address <CHANGE-ME-outside-ip>/<CHANGE-ME-prefix>
set network interface ethernet ethernet1/1 comment "OUTSIDE-INTERNET"
!
set network interface ethernet ethernet1/2 layer3 ipv4 addr primary ip-address <CHANGE-ME-inside-ip>/<CHANGE-ME-prefix>
set network interface ethernet ethernet1/2 comment "INSIDE-CORP"
!
set network interface ethernet ethernet1/3 layer3 ipv4 addr primary ip-address <CHANGE-ME-dmz-ip>/<CHANGE-ME-prefix>
set network interface ethernet ethernet1/3 comment "DMZ-SERVERS"
!
# ── ZONES ─────────────────────────────────────────────────────────────────────
set zone OUTSIDE network layer3 ethernet1/1
set zone OUTSIDE enable-user-identification no
set zone INSIDE  network layer3 ethernet1/2
set zone INSIDE  enable-user-identification yes
set zone DMZ     network layer3 ethernet1/3
set zone DMZ     enable-user-identification no
!
# ── SECURITY POLICY ───────────────────────────────────────────────────────────
# Rule 1: Allow INSIDE → OUTSIDE with Threat Prevention + URL filtering
set rulebase security rules INSIDE-TO-OUTSIDE from INSIDE
set rulebase security rules INSIDE-TO-OUTSIDE to OUTSIDE
set rulebase security rules INSIDE-TO-OUTSIDE source any
set rulebase security rules INSIDE-TO-OUTSIDE destination any
set rulebase security rules INSIDE-TO-OUTSIDE application any
set rulebase security rules INSIDE-TO-OUTSIDE service application-default
set rulebase security rules INSIDE-TO-OUTSIDE action allow
set rulebase security rules INSIDE-TO-OUTSIDE profile-setting profiles virus default
set rulebase security rules INSIDE-TO-OUTSIDE profile-setting profiles spyware default
set rulebase security rules INSIDE-TO-OUTSIDE profile-setting profiles vulnerability default
set rulebase security rules INSIDE-TO-OUTSIDE profile-setting profiles url-filtering default
set rulebase security rules INSIDE-TO-OUTSIDE profile-setting profiles file-blocking basic-file-blocking
set rulebase security rules INSIDE-TO-OUTSIDE log-end yes
!
# Rule 2: Allow OUTSIDE → DMZ (HTTPS/HTTP only)
set rulebase security rules OUTSIDE-TO-DMZ from OUTSIDE
set rulebase security rules OUTSIDE-TO-DMZ to DMZ
set rulebase security rules OUTSIDE-TO-DMZ destination <CHANGE-ME-dmz-server-ip>
set rulebase security rules OUTSIDE-TO-DMZ application ssl
set rulebase security rules OUTSIDE-TO-DMZ service application-default
set rulebase security rules OUTSIDE-TO-DMZ action allow
set rulebase security rules OUTSIDE-TO-DMZ profile-setting profiles vulnerability default
set rulebase security rules OUTSIDE-TO-DMZ log-end yes
!
# Rule 3: Implicit deny all — logged
set rulebase security rules DENY-ALL from any
set rulebase security rules DENY-ALL to any
set rulebase security rules DENY-ALL source any
set rulebase security rules DENY-ALL destination any
set rulebase security rules DENY-ALL application any
set rulebase security rules DENY-ALL service any
set rulebase security rules DENY-ALL action deny
set rulebase security rules DENY-ALL log-end yes
!
# ── NAT ───────────────────────────────────────────────────────────────────────
set rulebase nat rules INSIDE-PAT from INSIDE
set rulebase nat rules INSIDE-PAT to OUTSIDE
set rulebase nat rules INSIDE-PAT source any
set rulebase nat rules INSIDE-PAT destination any
set rulebase nat rules INSIDE-PAT source-translation dynamic-ip-and-port interface-address interface ethernet1/1
!
# ── THREAT PREVENTION ─────────────────────────────────────────────────────────
set profiles virus default action reset-both alert wildfire-action reset-both
set profiles spyware default action reset-both botnet-domains dns-security-policy sinkhole
set profiles vulnerability default action reset-both threat-exception any
!
# ── WILDFIRE ─────────────────────────────────────────────────────────────────
set deviceconfig setting wildfire file-size-limit pe 16
set deviceconfig setting wildfire file-size-limit elf 16
!
# ── ROUTING ───────────────────────────────────────────────────────────────────
set network virtual-router default routing-table ip static-route DEFAULT-ROUTE destination 0.0.0.0/0
set network virtual-router default routing-table ip static-route DEFAULT-ROUTE nexthop ip-address <CHANGE-ME-default-gateway>
!
# ── HA (Active/Passive) ────────────────────────────────────────────────────────
# set high-availability mode active-passive
# set high-availability group 1 peer-ip <CHANGE-ME-peer-ha-ip>
# set high-availability group 1 election-option priority 100
# set high-availability group 1 interface ha1 ip-address <CHANGE-ME-ha1-ip>
`
}

// ── Cisco IOS-XE WAN Edge ─────────────────────────────────────────────────────

function iosxeWanConfig(dev: BOMDevice, _idx: number): string {
  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : WAN Edge Router
! OS     : Cisco IOS-XE
! Model  : ${dev.model}
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

${mgmtBlock(dev.hostname, 10)}
!
! ── UNDERLAY: OSPF only (no IS-IS on WAN edge) ──────────────────────────────
router ospf 1
  router-id <CHANGE-ME-router-id>
  passive-interface default
  no passive-interface GigabitEthernet0/0/0
  no passive-interface GigabitEthernet0/0/1
  area 0 authentication message-digest
  log-adjacency-changes detail
!
interface GigabitEthernet0/0/0
  description WAN-UPLINK-TO-PROVIDER
  ip address <CHANGE-ME-wan-ip> <CHANGE-ME-wan-mask>
  ip ospf 1 area 0
  ip ospf message-digest-key 1 md5 <CHANGE-ME-ospf-auth-key>
  no ip ospf passive-interface
  no shutdown
!
interface GigabitEthernet0/0/1
  description LAN-DOWNLINK-TO-CORE
  ip address <CHANGE-ME-lan-ip> <CHANGE-ME-lan-mask>
  ip ospf 1 area 0
  no shutdown
!
! ── BGP (eBGP to SP, iBGP to DC if multisite) ────────────────────────────────
router bgp <CHANGE-ME-local-asn>
  bgp router-id <CHANGE-ME-router-id>
  bgp log-neighbor-changes
  !
  neighbor <CHANGE-ME-sp-peer-ip> remote-as <CHANGE-ME-sp-asn>
  neighbor <CHANGE-ME-sp-peer-ip> description ISP-eBGP-PEER
  neighbor <CHANGE-ME-sp-peer-ip> password 7 <CHANGE-ME-bgp-password>
  neighbor <CHANGE-ME-sp-peer-ip> send-community
  !
  address-family ipv4
    neighbor <CHANGE-ME-sp-peer-ip> activate
    neighbor <CHANGE-ME-sp-peer-ip> prefix-list PL-OUT out
    neighbor <CHANGE-ME-sp-peer-ip> prefix-list PL-IN  in
    network <CHANGE-ME-advertised-prefix>
!
ip prefix-list PL-OUT seq 10 permit <CHANGE-ME-advertised-prefix>
ip prefix-list PL-IN  seq 5  permit 0.0.0.0/0
ip prefix-list PL-IN  seq 99 deny   0.0.0.0/0 le 32
!
! ── IPSec / DMVPN (if SD-WAN overlay required) ───────────────────────────────
! crypto isakmp policy 10
!   encr aes 256
!   authentication pre-share
!   group 14
!   lifetime 28800
! crypto isakmp key <CHANGE-ME-psk> address 0.0.0.0
!
! ── QoS (WAN egress shaping) ─────────────────────────────────────────────────
class-map match-any CM-VOICE
  match dscp ef
class-map match-any CM-CRITICAL
  match dscp af31 af32
class-map match-any CM-BULK
  match dscp af11 af12
!
policy-map PM-WAN-SHAPING
  class CM-VOICE
    priority percent 15
  class CM-CRITICAL
    bandwidth percent 30
    random-detect dscp-based
  class CM-BULK
    bandwidth percent 10
    random-detect dscp-based
  class class-default
    fair-queue
    random-detect
!
interface GigabitEthernet0/0/0
  service-policy output PM-WAN-SHAPING
`
}

// ── Fortinet FortiOS ─────────────────────────────────────────────────────────

function fortinetFirewallConfig(dev: BOMDevice, _idx: number): string {
  return `# ═══════════════════════════════════════════════════════════════
# Device : ${dev.hostname}
# Role   : NGFW (FortiGate)
# Model  : ${dev.model}
# OS     : Fortinet FortiOS 7.x
# Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
# ═══════════════════════════════════════════════════════════════

config system global
    set hostname "${dev.hostname}"
    set timezone 00
    set admintimeout 10
    set admin-ssh-v1 disable
    set admin-telnet disable
    set strong-crypto enable
    set password-policy-status enable
    set password-policy-min-length 12
    set password-policy-must-contain upper-case-letter lower-case-letter number non-alphanumeric
end

config system admin
    edit "admin"
        set password <CHANGE-ME-admin-password>
        set trusthost1 <CHANGE-ME-mgmt-subnet>/24
        set accprofile "super_admin"
    next
end

config system interface
    edit "mgmt"
        set mode static
        set ip <CHANGE-ME-mgmt-ip>/24
        set allowaccess ping https ssh
        set type physical
        set role lan
    next
    edit "port1"
        set mode static
        set ip <CHANGE-ME-outside-ip>/30
        set allowaccess ping
        set type physical
        set role wan
    next
    edit "port2"
        set mode static
        set ip <CHANGE-ME-inside-ip>/30
        set allowaccess ping
        set type physical
        set role lan
    next
end

config router static
    edit 1
        set gateway <CHANGE-ME-default-gw>
        set device "port1"
    next
end

config system dns
    set primary 8.8.8.8
    set secondary 8.8.4.4
end

config log syslogd setting
    set status enable
    set server "<CHANGE-ME-syslog-ip>"
    set facility local7
    set format default
end

config system ntp
    set ntpsync enable
    set type custom
    config ntpserver
        edit 1
            set server "<CHANGE-ME-ntp-primary>"
        next
        edit 2
            set server "<CHANGE-ME-ntp-secondary>"
        next
    end
end

config system snmp sysinfo
    set status enable
    set description "${dev.hostname} — NetDesign AI managed"
    set contact-info "<CHANGE-ME-noc-email>"
    set location "<CHANGE-ME-site-location>"
end

config system snmp user
    edit "netmon"
        set status enable
        set queries enable
        set query-port 161
        set notify-hosts <CHANGE-ME-nms-ip>
        set security-level auth-priv
        set auth-proto sha256
        set auth-pwd <CHANGE-ME-snmp-auth-pass>
        set priv-proto aes256
        set priv-pwd <CHANGE-ME-snmp-priv-pass>
    next
end

# ── Firewall Policies ────────────────────────────────────────────────────────
config firewall policy
    edit 1
        set name "Allow-Outbound"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set logtraffic all
        set utm-status enable
        set av-profile "default"
        set ips-sensor "default"
        set ssl-ssh-profile "certificate-inspection"
    next
    edit 2
        set name "Deny-Inbound"
        set srcintf "port1"
        set dstintf "port2"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
        set logtraffic all
    next
end

# ── IPS / Application Control ────────────────────────────────────────────────
config ips sensor
    edit "default"
        set comment "Default IPS sensor — high security"
        config entries
            edit 1
                set rule all
                set action block
                set severity high critical
            next
        end
    next
end
`
}

// ── Dell EMC OS10 ────────────────────────────────────────────────────────────

function dellOs10SwitchConfig(dev: BOMDevice, _idx: number, isGpu = false): string {
  const isSpine = dev.subLayer === 'spine'
  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : ${isSpine ? 'Spine' : 'Leaf / ToR'}
! Model  : ${dev.model}
! OS     : Dell EMC OS10 (Enterprise SONiC compatible)
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

hostname ${dev.hostname}
!
ip name-server 8.8.8.8
!
username admin password <CHANGE-ME-admin-password> role sysadmin
!
interface mgmt 1/1/1
  no shutdown
  ip address <CHANGE-ME-mgmt-ip>/24
!
management route 0.0.0.0/0 <CHANGE-ME-mgmt-gw>
!
! ── NTP ─────────────────────────────────────────────────────────────────────
ntp server <CHANGE-ME-ntp-primary>
ntp server <CHANGE-ME-ntp-secondary>
!
! ── SNMP v3 ─────────────────────────────────────────────────────────────────
snmp-server group NETDESIGN-RO v3 priv read NETDESIGN-VIEW
snmp-server user netmon NETDESIGN-RO v3 auth sha <CHANGE-ME-snmp-auth-pass> priv aes-256 <CHANGE-ME-snmp-priv-pass>
snmp-server host <CHANGE-ME-nms-ip> traps version 3 priv netmon
!
! ── Syslog ──────────────────────────────────────────────────────────────────
logging server <CHANGE-ME-syslog-ip>
!
! ── LLDP ────────────────────────────────────────────────────────────────────
lldp enable
!
! ── BGP (eBGP spine-leaf, unnumbered) ───────────────────────────────────────
router bgp <CHANGE-ME-asn>
  bestpath as-path multipath-relax
  !
  address-family ipv4 unicast
    maximum-paths 64
  !
  address-family l2vpn evpn
    advertise-all-vni
  !
${isSpine ? `  ! ── Spine: accept all leaf peers ────────────────────────────────────────
  neighbor interface ethernet1/1/1-1/1/32
    peer-group LEAVES
  !
  peer-group LEAVES
    remote-as external
    advertisement-interval 0
    timers 3 9
    send-community extended
    address-family l2vpn evpn
      activate
    address-family ipv4 unicast
      activate` : `  ! ── Leaf: peer to spines ──────────────────────────────────────────────────
  neighbor <CHANGE-ME-spine1-ip>
    remote-as <CHANGE-ME-spine-asn>
    advertisement-interval 0
    timers 3 9
    bfd
    send-community extended
    address-family l2vpn evpn
      activate
  !
  neighbor <CHANGE-ME-spine2-ip>
    remote-as <CHANGE-ME-spine-asn>
    advertisement-interval 0
    timers 3 9
    bfd
    send-community extended
    address-family l2vpn evpn
      activate`}
!
! ── VXLAN ───────────────────────────────────────────────────────────────────
interface virtual-network 1
  vxlan-vni 10001
!
${isGpu ? `! ── GPU / RoCEv2 QoS ────────────────────────────────────────────────────────
qos-map pfc-priority-queue-map RDMA
  priority 3 queue 3
!
interface range ethernet 1/1/1-1/1/${dev.ports}
  priority-flow-control mode on
  priority-flow-control priority 3 no-drop
  dcb-map RDMA
  pfc-watchdog on` : ''}
`
}

// ── HPE Aruba CX ─────────────────────────────────────────────────────────────

function arubaOsCxConfig(dev: BOMDevice, _idx: number): string {
  const isSpine = dev.subLayer === 'spine'
  const isDist  = dev.subLayer === 'distribution'
  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : ${dev.subLayer}
! Model  : ${dev.model}
! OS     : ArubaOS-CX 10.x
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

hostname ${dev.hostname}
!
user admin group administrators password ciphertext <CHANGE-ME-admin-password>
!
interface mgmt
  shutdown
  ip static <CHANGE-ME-mgmt-ip>/24
  default-gateway <CHANGE-ME-mgmt-gw>
no interface mgmt shutdown
!
ntp server <CHANGE-ME-ntp-primary> iburst
ntp server <CHANGE-ME-ntp-secondary> iburst
ntp enable
!
! ── LLDP ────────────────────────────────────────────────────────────────────
lldp enable
!
! ── SSH ─────────────────────────────────────────────────────────────────────
ssh server vrf mgmt
aaa authentication login default local
!
! ── SNMP v3 ─────────────────────────────────────────────────────────────────
snmp-server vrf default
snmp-server group NETDESIGN-RO v3 priv
snmp-server user netmon NETDESIGN-RO v3 auth sha <CHANGE-ME-snmp-auth-pass> priv aes <CHANGE-ME-snmp-priv-pass>
!
! ── Logging ─────────────────────────────────────────────────────────────────
logging <CHANGE-ME-syslog-ip> vrf default severity informational
!
${isSpine || isDist ? `! ── BGP + EVPN ───────────────────────────────────────────────────────────────
router bgp <CHANGE-ME-asn>
  bgp router-id <CHANGE-ME-loopback-ip>
  maximum-paths 64
  !
  address-family l2vpn evpn
    advertise-all-vni
  !
  neighbor SPINES peer-group
    remote-as external
    timers 3 9
    send-community
    send-community extended
    address-family ipv4 unicast
      activate
    address-family l2vpn evpn
      activate
  !
  neighbor <CHANGE-ME-peer-ip> peer-group SPINES
!
! ── VXLAN ────────────────────────────────────────────────────────────────────
interface loopback 0
  ip address <CHANGE-ME-loopback-ip>/32
!
interface vxlan 1
  source ip <CHANGE-ME-loopback-ip>
  no shutdown` : `! ── Access layer: VLANs + PoE ───────────────────────────────────────────────
vlan 10
  name Management
vlan 20
  name Data
vlan 30
  name Voice
!
interface 1/1/1-1/1/${dev.ports}
  no shutdown
  vlan access 20
  spanning-tree bpduguard enable
  spanning-tree port-type admin-edge`}
`
}

// ── NVIDIA Cumulus Linux ──────────────────────────────────────────────────────

function nvidiaSpectrumConfig(dev: BOMDevice, _idx: number, isGpu = false): string {
  const isSpine = dev.subLayer === 'spine'
  return `# ═══════════════════════════════════════════════════════════════
# Device : ${dev.hostname}
# Role   : ${isSpine ? 'Spine' : 'Leaf / ToR'}
# Model  : ${dev.model}
# OS     : NVIDIA Cumulus Linux 5.x / Air
# Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
# ═══════════════════════════════════════════════════════════════

# /etc/hostname
${dev.hostname}

# /etc/network/interfaces
auto lo
iface lo inet loopback
  address <CHANGE-ME-loopback-ip>/32

auto mgmt
iface mgmt inet dhcp
  address <CHANGE-ME-mgmt-ip>/24
  gateway <CHANGE-ME-mgmt-gw>
  vrf mgmt

# /etc/frr/frr.conf  (FRRouting)
frr version 9.1
frr defaults datacenter
hostname ${dev.hostname}
log syslog informational
!
ip forwarding
ipv6 forwarding
!
! ── BGP eBGP spine-leaf (RFC 7938) ──────────────────────────────────────────
router bgp <CHANGE-ME-asn>
  bgp router-id <CHANGE-ME-loopback-ip>
  bgp bestpath as-path multipath-relax
  !
  neighbor FABRIC peer-group
  neighbor FABRIC remote-as external
  neighbor FABRIC timers 3 9
  neighbor FABRIC advertisement-interval 0
  neighbor FABRIC bfd
  neighbor FABRIC capability extended-nexthop
  !
${isSpine
  ? `  ! Spine — swp1..swp${dev.ports} peer to leaves
  neighbor swp1-swp${dev.ports} interface peer-group FABRIC`
  : `  ! Leaf — swp${dev.ports - 1}..swp${dev.ports} peer to spines
  neighbor swp${dev.ports - 1} interface peer-group FABRIC
  neighbor swp${dev.ports}   interface peer-group FABRIC`}
  !
  address-family ipv4 unicast
    redistribute connected
    maximum-paths 64
    neighbor FABRIC activate
  !
  address-family l2vpn evpn
    neighbor FABRIC activate
    advertise-all-vni
${isSpine ? '    route-reflector-client' : ''}
  !
!
${isGpu ? `# ── RoCEv2 / PFC / ECN (Spectrum QoS) ──────────────────────────────────────
# /etc/cumulus/datapath/traffic.conf
# pfc.pfc_port_list = swp1-swp${dev.ports}
# pfc.pfc_priority_list = 3
# link_pause.pfc_xoff_threshold = 122880
# link_pause.pfc_xon_threshold  = 81920

# ECMP hashing for RoCEv2
net add interface swp1-${dev.ports} ip ecmp
net add routing protocol bgp
net add bgp bestpath as-path multipath-relax
net add bgp maximum-paths 64

# ECN marking
tc qdisc add dev swp1 root fq_codel limit 10000 ecn` : ''}

# NTP
net add time ntp server <CHANGE-ME-ntp-primary> iburst
net add time ntp server <CHANGE-ME-ntp-secondary> iburst

# SNMP v3
net add snmp-server listening-address all
net add snmp-server username netmon auth-sha <CHANGE-ME-snmp-auth-pass> encrypt-aes <CHANGE-ME-snmp-priv-pass>
`
}

// ── Generic fallback ─────────────────────────────────────────────────────────

function genericConfig(dev: BOMDevice): string {
  return `! ═══════════════════════════════════════════════════════════════
! Device : ${dev.hostname}
! Role   : ${dev.subLayer}
! Model  : ${dev.model} (${dev.vendor})
! Generated by NetDesign AI — replace <CHANGE-ME-*> before deploying.
! ═══════════════════════════════════════════════════════════════

${mgmtBlock(dev.hostname, 10)}
!
! ── TODO: Add ${dev.vendor} ${dev.subLayer}-specific configuration ────────────
! This template provides management plane hardening.
! Add data-plane config (routing, switching, VLANs) for your deployment.
`
}

// ── Dispatch ──────────────────────────────────────────────────────────────────

export function generateConfig(dev: BOMDevice, idx: number, useCase: UseCase | '' = ''): string {
  const isGpu = useCase === 'gpu'
  const v = dev.vendor
  const l = dev.subLayer

  if (v === 'Palo Alto' && l === 'firewall')                        return paloAltoFirewallConfig(dev, idx)
  if (v === 'Cisco'     && l === 'firewall')                         return ciscoFirewallConfig(dev, idx)
  if (v === 'Cisco'     && l === 'wan-edge')                         return iosxeWanConfig(dev, idx)
  if (v === 'Cisco'     && l === 'spine')                            return nxosSpineConfig(dev, idx, isGpu)
  if (v === 'Cisco'     && l === 'leaf')                             return nxosLeafConfig(dev, idx, isGpu)
  if (v === 'Cisco'     && (l === 'distribution' || l === 'access')) return iosxeWanConfig(dev, idx)
  if (v === 'Arista'    && l === 'spine')                            return aristaSpineConfig(dev, idx, isGpu)
  if (v === 'Arista'    && l === 'leaf')                             return aristaLeafConfig(dev, idx, isGpu)
  if (v === 'Juniper'   && (l === 'leaf' || l === 'spine'))          return juniperLeafConfig(dev, idx)
  if (v === 'Fortinet'  && l === 'firewall')                         return fortinetFirewallConfig(dev, idx)
  if (v === 'Dell EMC'  && (l === 'spine' || l === 'leaf'))          return dellOs10SwitchConfig(dev, idx, isGpu)
  if (v === 'HPE Aruba')                                             return arubaOsCxConfig(dev, idx)
  if (v === 'NVIDIA'    && (l === 'spine' || l === 'leaf'))          return nvidiaSpectrumConfig(dev, idx, isGpu)
  return genericConfig(dev)
}

export function generateAllConfigs(
  devices: BOMDevice[],
  useCase: UseCase | '' = '',
): Record<string, string> {
  return Object.fromEntries(
    devices.map((dev, i) => [dev.id, generateConfig(dev, i, useCase)])
  )
}
