import type { BOMDevice } from '@/types'

function nxosSpineConfig(dev: BOMDevice): string {
  const asn = 65000
  return `! ${dev.hostname} — Cisco NX-OS Spine
hostname ${dev.hostname}
feature bgp
feature pim
feature interface-vlan
feature vn-segment-vlan-based
feature nv overlay

ip pim rp-address 10.0.0.1 group-list 239.0.0.0/8
ip pim ssm range 232.0.0.0/8

router bgp ${asn}
  router-id 10.0.0.1
  address-family l2vpn evpn
    retain route-target all
  neighbor 10.1.0.0/24
    remote-as route-map LEAF-ASN
    update-source loopback0
    address-family l2vpn evpn
      send-community both
      route-reflector-client
`
}

function nxosLeafConfig(dev: BOMDevice, idx: number): string {
  const leafAsn = 65001 + idx
  return `! ${dev.hostname} — Cisco NX-OS Leaf
hostname ${dev.hostname}
feature bgp
feature pim
feature interface-vlan
feature vn-segment-vlan-based
feature nv overlay
feature lacp
feature vpc

vlan 10
  name SERVERS
  vn-segment 10010

interface nve1
  no shutdown
  source-interface loopback1
  host-reachability protocol bgp
  member vni 10010 associate-vrf

router bgp ${leafAsn}
  router-id 10.1.0.${idx + 1}
  address-family ipv4 unicast
    network 10.1.0.${idx + 1}/32
  address-family l2vpn evpn
  neighbor 10.0.0.0/24
    remote-as 65000
    update-source loopback0
    address-family l2vpn evpn
      send-community both
`
}

function aristaSpineConfig(dev: BOMDevice): string {
  return `! ${dev.hostname} — Arista EOS Spine
hostname ${dev.hostname}

service routing protocols model multi-agent

ip routing
router bgp 65000
   router-id 10.0.0.1
   bgp listen range 10.1.0.0/24 peer-group LEAF-PEERS remote-as 65001
   neighbor LEAF-PEERS peer group
   neighbor LEAF-PEERS send-community extended
   address-family evpn
      neighbor LEAF-PEERS activate
   address-family ipv4
      neighbor LEAF-PEERS activate
`
}

function juniperLeafConfig(dev: BOMDevice): string {
  return `# ${dev.hostname} — Juniper QFX Leaf
set system host-name ${dev.hostname}
set protocols bgp group SPINES type external
set protocols bgp group SPINES export LOOPBACKS
set protocols bgp group SPINES neighbor 10.0.0.1 peer-as 65000
set protocols bgp group SPINES neighbor 10.0.0.2 peer-as 65000
set protocols evpn encapsulation vxlan
set protocols evpn extended-vni-list all
set switch-options vtep-source-interface lo0.0
set switch-options vrf-target target:65000:1
`
}

function genericConfig(dev: BOMDevice): string {
  return `! ${dev.hostname} — ${dev.vendor} ${dev.subLayer}
hostname ${dev.hostname}
! Generated by NetDesign AI
! Model: ${dev.model}
! Use this as a starting-point template.
`
}

export function generateConfig(dev: BOMDevice, idx: number): string {
  if (dev.vendor === 'Cisco' && dev.subLayer === 'spine') return nxosSpineConfig(dev)
  if (dev.vendor === 'Cisco' && dev.subLayer === 'leaf')  return nxosLeafConfig(dev, idx)
  if (dev.vendor === 'Arista' && dev.subLayer === 'spine') return aristaSpineConfig(dev)
  if (dev.vendor === 'Juniper' && dev.subLayer === 'leaf') return juniperLeafConfig(dev)
  return genericConfig(dev)
}

export function generateAllConfigs(devices: BOMDevice[]): Record<string, string> {
  return Object.fromEntries(
    devices.map((dev, i) => [dev.id, generateConfig(dev, i)])
  )
}
