import type { Product, UseCase } from '@/types'

export const PRODUCTS: Product[] = [
  // ── Spine / Core ────────────────────────────────────────────────────────────
  {
    id: 'nxos-9336c',
    model: 'Nexus 9336C-FX2',
    vendor: 'Cisco',
    subLayer: 'spine',
    ports: 36,
    uplinks: 0,
    speed: '100G',
    asic: 'Cloud Scale',
    powerW: 650,
    priceUSD: 28000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '36x100G QSFP28, MACsec, CloudScale ASIC, 3.6Tbps',
  },
  {
    id: 'nxos-9364c',
    model: 'Nexus 9364C-GX',
    vendor: 'Cisco',
    subLayer: 'spine',
    ports: 64,
    uplinks: 0,
    speed: '400G',
    asic: 'Cloud Scale GX',
    powerW: 1200,
    priceUSD: 72000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multicloud'],
    detail: '64x400G QSFP-DD, AI/ML optimised, 25.6Tbps',
  },
  {
    id: 'arista-7800r3',
    model: 'Arista 7800R3',
    vendor: 'Arista',
    subLayer: 'spine',
    ports: 48,
    uplinks: 0,
    speed: '400G',
    asic: 'Jericho2+',
    powerW: 1400,
    priceUSD: 95000,
    features: ['VXLAN', 'EVPN', 'BGP', 'MPLS', 'FlowSpec'],
    useCases: ['dc', 'wan', 'multisite', 'multicloud'],
    detail: '48x400G QSFP-DD, segment routing, 19.2Tbps',
  },
  {
    id: 'juniper-qfx10002',
    model: 'QFX10002-72Q',
    vendor: 'Juniper',
    subLayer: 'spine',
    ports: 72,
    uplinks: 0,
    speed: '40G',
    asic: 'Q5',
    powerW: 800,
    priceUSD: 35000,
    features: ['VXLAN', 'EVPN', 'BGP', 'MPLS'],
    useCases: ['dc', 'multisite'],
    detail: '72x40G QSFP+, 2.88Tbps, VC-capable',
  },

  // ── Leaf / ToR ──────────────────────────────────────────────────────────────
  {
    id: 'nxos-93180yc',
    model: 'Nexus 93180YC-FX',
    vendor: 'Cisco',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Cloud Scale',
    powerW: 480,
    priceUSD: 14000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28 uplinks',
  },
  {
    id: 'nxos-9332c',
    model: 'Nexus 9332C',
    vendor: 'Cisco',
    subLayer: 'leaf',
    ports: 32,
    uplinks: 2,
    speed: '100G',
    asic: 'Cloud Scale',
    powerW: 550,
    priceUSD: 18000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC'],
    useCases: ['dc', 'gpu'],
    detail: '32x100G QSFP28 + 2x100G uplinks, GPU-optimised',
  },
  {
    id: 'arista-7050cx3',
    model: 'Arista 7050CX3-32S',
    vendor: 'Arista',
    subLayer: 'leaf',
    ports: 32,
    uplinks: 2,
    speed: '100G',
    asic: 'Trident3',
    powerW: 460,
    priceUSD: 16000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECMP'],
    useCases: ['dc', 'multisite'],
    detail: '32x100G QSFP28 + 2x100G uplinks, Trident3',
  },
  {
    id: 'juniper-qfx5120',
    model: 'QFX5120-48Y',
    vendor: 'Juniper',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Trident3',
    powerW: 440,
    priceUSD: 12000,
    features: ['VXLAN', 'EVPN', 'BGP', 'LLDP'],
    useCases: ['dc', 'multisite'],
    detail: '48x25G SFP28 + 8x100G QSFP28 uplinks',
  },

  // ── Distribution ────────────────────────────────────────────────────────────
  {
    id: 'cat9500',
    model: 'Catalyst 9500-48Y4C',
    vendor: 'Cisco',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 4,
    speed: '25G',
    asic: 'UADP 3.0',
    powerW: 715,
    priceUSD: 22000,
    features: ['SDA', 'VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'multisite'],
    detail: '48x25G + 4x100G, Cisco SDA-ready',
  },
  {
    id: 'cat9300l',
    model: 'Catalyst 9300L-48T-4G',
    vendor: 'Cisco',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'UADP 2.0',
    powerW: 390,
    priceUSD: 4800,
    features: ['PoE+', 'SDA', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x1G SFP uplinks, 740W PoE budget',
  },
  {
    id: 'cat9200',
    model: 'Catalyst 9200-48P',
    vendor: 'Cisco',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'UADP 2.0 Lite',
    powerW: 370,
    priceUSD: 3200,
    features: ['PoE+', 'QoS', 'LLDP'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x1G SFP uplinks',
  },

  // ── WAN / Edge ───────────────────────────────────────────────────────────────
  {
    id: 'asr1002hx',
    model: 'ASR 1002-HX',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 4,
    uplinks: 0,
    speed: '10G',
    asic: 'QuantumFlow',
    powerW: 280,
    priceUSD: 18000,
    features: ['BGP', 'MPLS', 'OSPF', 'IPSec', 'DMVPN', 'SD-WAN'],
    useCases: ['wan', 'multisite'],
    detail: '4x10G, 60Gbps aggregate, crypto capable',
  },
  {
    id: 'asr9904',
    model: 'ASR 9904',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 8,
    uplinks: 0,
    speed: '100G',
    asic: 'Lightspeed-Plus',
    powerW: 1200,
    priceUSD: 95000,
    features: ['IOS-XR', 'BGP', 'MPLS', 'SR-MPLS', 'L3VPN', 'IS-IS', 'OSPF', 'FlexAlgo'],
    useCases: ['wan', 'multisite'],
    detail: 'IOS-XR SP edge (PE/P), SR-MPLS + L3VPN, 8x100G',
  },
  {
    id: 'ncs540',
    model: 'NCS 540',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 24,
    uplinks: 0,
    speed: '10G',
    asic: 'Qumran',
    powerW: 240,
    priceUSD: 22000,
    features: ['IOS-XR', 'BGP', 'MPLS', 'SR-MPLS', 'L3VPN', 'IS-IS', 'EVPN'],
    useCases: ['wan', 'multisite'],
    detail: 'IOS-XR access/aggregation PE, SR-MPLS + L3VPN, 24x10G',
  },
  {
    id: 'viptela-vedge',
    model: 'Catalyst SD-WAN vEdge 2000',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 8,
    uplinks: 0,
    speed: '1G',
    asic: 'Software',
    powerW: 150,
    priceUSD: 9500,
    features: ['SD-WAN', 'BGP', 'IPSec', 'ZTP', 'AppQoE'],
    useCases: ['wan', 'multisite', 'multicloud'],
    detail: '8x1G, SD-WAN ZTP, AppQoE, 20Gbps',
  },

  // ── SD-WAN Controllers (G-A12) ──────────────────────────────────────────────
  {
    id: 'sdwan-vmanage',
    model: 'vManage',
    vendor: 'Cisco',
    subLayer: 'sdwan-controller',
    ports: 2,
    uplinks: 0,
    speed: '1G',
    asic: 'Software',
    powerW: 400,
    priceUSD: 35000,
    features: ['SD-WAN', 'NMS', 'Analytics', 'REST-API'],
    useCases: ['wan', 'multisite', 'multicloud'],
    detail: 'SD-WAN network management system — centralised config, monitoring, analytics',
  },
  {
    id: 'sdwan-vsmart',
    model: 'vSmart Controller',
    vendor: 'Cisco',
    subLayer: 'sdwan-controller',
    ports: 2,
    uplinks: 0,
    speed: '1G',
    asic: 'Software',
    powerW: 200,
    priceUSD: 15000,
    features: ['SD-WAN', 'OMP', 'Route-Reflector', 'Policy-Distribution'],
    useCases: ['wan', 'multisite', 'multicloud'],
    detail: 'SD-WAN control plane — OMP route reflector, centralised policy distribution',
  },
  {
    id: 'sdwan-vbond',
    model: 'vBond Orchestrator',
    vendor: 'Cisco',
    subLayer: 'sdwan-controller',
    ports: 2,
    uplinks: 0,
    speed: '1G',
    asic: 'Software',
    powerW: 150,
    priceUSD: 10000,
    features: ['SD-WAN', 'Orchestration', 'NAT-Traversal', 'Authentication'],
    useCases: ['wan', 'multisite', 'multicloud'],
    detail: 'SD-WAN orchestrator — WAN edge authentication, NAT traversal, initial bootstrap',
  },
  {
    id: 'cat8300-edge',
    model: 'Catalyst 8300 Edge',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 8,
    uplinks: 0,
    speed: '10G',
    asic: 'QFP3',
    powerW: 220,
    priceUSD: 14000,
    features: ['SD-WAN', 'BGP', 'OSPF', 'IPSec', 'AppQoE', 'DPI', 'ZTP', 'ThousandEyes'],
    useCases: ['wan', 'multisite', 'multicloud'],
    detail: 'Catalyst SD-WAN cEdge — IOS-XE SD-WAN mode, DPI, AppQoE, 8x10G, 40Gbps',
  },

  // ── Private 5G / O-RAN (G-A10) ──────────────────────────────────────────────
  {
    id: 'oran-cu',
    model: 'O-CU Server (Dell R750)',
    vendor: 'Dell EMC',
    subLayer: 'oran-cu',
    ports: 4,
    uplinks: 2,
    speed: '25G',
    asic: 'x86 DPDK',
    powerW: 800,
    priceUSD: 22000,
    features: ['eCPRI', 'F1', 'E1', 'SCTP', 'GTP-U', 'PTP', '5G-NR'],
    useCases: ['oran'],
    detail: 'O-RAN Centralized Unit (CU-CP + CU-UP), COTS server, F1/E1 split',
  },
  {
    id: 'oran-du',
    model: 'O-DU Server (Dell XR4000)',
    vendor: 'Dell EMC',
    subLayer: 'oran-du',
    ports: 4,
    uplinks: 2,
    speed: '25G',
    asic: 'x86 + FPGA',
    powerW: 600,
    priceUSD: 18000,
    features: ['eCPRI', 'PTP', 'FAPI', 'L1-offload', '5G-NR'],
    useCases: ['oran'],
    detail: 'O-RAN Distributed Unit, real-time L1/L2 processing, eCPRI fronthaul',
  },
  {
    id: 'oran-ru',
    model: 'O-RU Radio Unit (Fujitsu)',
    vendor: 'Fujitsu',
    subLayer: 'oran-ru',
    ports: 2,
    uplinks: 0,
    speed: '25G',
    asic: 'RF ASIC',
    powerW: 350,
    priceUSD: 8000,
    features: ['eCPRI', 'PTP', 'MIMO-64T64R', 'beamforming', '5G-NR'],
    useCases: ['oran'],
    detail: 'O-RAN Radio Unit, 64T64R mMIMO, 3.5GHz n78 band, eCPRI 25G',
  },
  {
    id: 'oran-fronthaul-sw',
    model: 'Nexus 93180YC-FX3',
    vendor: 'Cisco',
    subLayer: 'oran-fronthaul',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Cloud Scale',
    powerW: 480,
    priceUSD: 18000,
    features: ['PTP-TC', 'eCPRI', 'LLDP', 'QoS', 'IEEE-1588'],
    useCases: ['oran'],
    detail: 'Fronthaul switch — PTP transparent-clock, eCPRI Class C7, 48x25G + 6x100G',
  },
  {
    id: 'oran-midhaul-rtr',
    model: 'ASR 9901',
    vendor: 'Cisco',
    subLayer: 'oran-midhaul',
    ports: 20,
    uplinks: 4,
    speed: '100G',
    asic: 'Lightspeed+',
    powerW: 600,
    priceUSD: 45000,
    features: ['SR-MPLS', 'PTP-BC', 'IEEE-1588', 'eCPRI', 'FlexE', 'BGP', '5G-NR'],
    useCases: ['oran'],
    detail: 'Midhaul/backhaul router — PTP boundary-clock, SR-MPLS, 20x100G, timing-grade',
  },
  {
    id: 'oran-core-upf',
    model: '5G Core UPF (COTS)',
    vendor: 'Dell EMC',
    subLayer: 'oran-core',
    ports: 4,
    uplinks: 2,
    speed: '100G',
    asic: 'x86 + SmartNIC',
    powerW: 1000,
    priceUSD: 35000,
    features: ['GTP-U', 'N3', 'N6', 'N9', 'UPF', 'DPDK', '5G-NR'],
    useCases: ['oran'],
    detail: '5G Core User Plane Function — GTP-U/N3/N6 termination, COTS + SmartNIC offload',
  },
  {
    id: 'ptp-grandmaster',
    model: 'Calnex PTP GM (IEEE 1588)',
    vendor: 'Calnex',
    subLayer: 'oran-timing',
    ports: 4,
    uplinks: 0,
    speed: '1G',
    asic: 'Timing ASIC',
    powerW: 50,
    priceUSD: 12000,
    features: ['PTP', 'IEEE-1588', 'GNSS', 'SyncE', 'G.8275.1'],
    useCases: ['oran'],
    detail: 'PTP Grandmaster clock — GNSS-synced, G.8275.1 telecom profile, Class A',
  },

  // ── GPU Compute Servers ──────────────────────────────────────────────────
  {
    id: 'gpu-server-4u',
    model: 'GPU Server 4U (8x H100)',
    vendor: 'NVIDIA',
    subLayer: 'gpu-compute',
    ports: 4,
    uplinks: 0,
    speed: '100G',
    asic: 'H100 SXM',
    powerW: 6500,
    priceUSD: 150000,
    features: ['RoCEv2', 'RDMA', 'NCCL', 'GPU-Direct', 'NVLink'],
    useCases: ['gpu'],
    detail: '4U chassis, 8x H100 SXM GPUs, dual ConnectX-7 100G NICs',
  },

  // ── Aviatrix ────────────────────────────────────────────────────────────────
  {
    id: 'aviatrix-gw',
    model: 'Aviatrix Gateway (c5.xlarge)',
    vendor: 'Aviatrix',
    subLayer: 'cloud-gw',
    ports: 0,
    uplinks: 0,
    speed: '10G',
    asic: 'Software',
    powerW: 0,
    priceUSD: 4200,
    features: ['BGP', 'IPSec', 'SNAT', 'DNAT', 'FireNet', 'TGW'],
    useCases: ['aviatrix', 'multicloud'],
    detail: 'Cloud-native gateway, AWS/Azure/GCP',
  },
  {
    id: 'aviatrix-transit',
    model: 'Aviatrix Transit GW (c5.2xlarge)',
    vendor: 'Aviatrix',
    subLayer: 'cloud-transit',
    ports: 0,
    uplinks: 0,
    speed: '25G',
    asic: 'Software',
    powerW: 0,
    priceUSD: 9800,
    features: ['BGP', 'EVPN', 'Segmentation', 'FireNet', 'TGW'],
    useCases: ['aviatrix', 'multicloud'],
    detail: 'Cloud transit, multi-cloud meshing',
  },

  // ── Firewalls / Security ────────────────────────────────────────────────────
  {
    id: 'ftd4145',
    model: 'Firepower 4145 NGFW',
    vendor: 'Cisco',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '40G',
    asic: 'Liqid',
    powerW: 800,
    priceUSD: 65000,
    features: ['IPS', 'AVC', 'TLS-decrypt', 'AMP', 'HA'],
    useCases: ['campus', 'dc', 'multisite', 'multicloud'],
    detail: '8x40G, 80Gbps FW throughput, HA pair',
  },
  {
    id: 'panos-pa5260',
    model: 'PA-5260 NGFW',
    vendor: 'Palo Alto',
    subLayer: 'firewall',
    ports: 16,
    uplinks: 0,
    speed: '100G',
    asic: 'CN-Series',
    powerW: 1100,
    priceUSD: 120000,
    features: ['IPS', 'URL-filter', 'GlobalProtect', 'TLS-decrypt', 'HA'],
    useCases: ['campus', 'dc', 'multicloud'],
    detail: '16x100G, 200Gbps threat prevention',
  },

  // ── Fortinet ─────────────────────────────────────────────────────────────────
  {
    id: 'fortinet-fg2600f',
    model: 'FortiGate 2600F',
    vendor: 'Fortinet',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '40G',
    asic: 'NP7',
    powerW: 750,
    priceUSD: 52000,
    features: ['IPS', 'SSL-Inspect', 'SD-WAN', 'ZTNA', 'HA'],
    useCases: ['campus', 'dc', 'multisite', 'multicloud'],
    detail: '8x40G, 100Gbps FW + 25Gbps IPS, NP7 ASIC, HA pair',
  },
  {
    id: 'fortinet-fst1024e',
    model: 'FortiSwitch T1024E',
    vendor: 'Fortinet',
    subLayer: 'distribution',
    ports: 24,
    uplinks: 4,
    speed: '10G',
    asic: 'Marvell',
    powerW: 285,
    priceUSD: 6800,
    features: ['VLAN', 'QoS', 'LLDP', 'FortiLink', 'MACsec'],
    useCases: ['campus'],
    detail: '24x10G SFP+ + 4x40G QSFP uplinks, FortiLink managed',
  },
  {
    id: 'fortinet-fst148f',
    model: 'FortiSwitch 148F-POE',
    vendor: 'Fortinet',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Marvell',
    powerW: 740,
    priceUSD: 2800,
    features: ['PoE+', 'VLAN', 'QoS', 'FortiLink', 'LLDP'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, 740W PoE budget',
  },

  // ── Dell EMC ─────────────────────────────────────────────────────────────────
  {
    id: 'dell-z9332f',
    model: 'PowerSwitch Z9332F-ON',
    vendor: 'Dell EMC',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '400G',
    asic: 'Broadcom Trident4',
    powerW: 900,
    priceUSD: 38000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'SONiC'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '32x400G QSFP-DD, Dell OS10/SONiC-compatible, 12.8Tbps',
  },
  {
    id: 'dell-s5248f',
    model: 'PowerSwitch S5248F-ON',
    vendor: 'Dell EMC',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 480,
    priceUSD: 11000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28 uplinks, Dell OS10',
  },

  // ── HPE Aruba ────────────────────────────────────────────────────────────────
  {
    id: 'aruba-cx10000',
    model: 'Aruba CX 10000',
    vendor: 'HPE Aruba',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '400G',
    asic: 'Pensando Elba',
    powerW: 1050,
    priceUSD: 45000,
    features: ['VXLAN', 'EVPN', 'BGP', 'Stateful FW', 'DPU'],
    useCases: ['dc', 'campus', 'multisite'],
    detail: '32x400G QSFP-DD, integrated DPU-based stateful firewall, ArubaOS-CX',
  },
  {
    id: 'aruba-cx6400',
    model: 'Aruba CX 6400',
    vendor: 'HPE Aruba',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 680,
    priceUSD: 18000,
    features: ['VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'dc'],
    detail: '48x25G SFP28 + 8x100G QSFP28 uplinks, ArubaOS-CX',
  },
  {
    id: 'aruba-cx6300',
    model: 'Aruba CX 6300M',
    vendor: 'HPE Aruba',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Broadcom',
    powerW: 420,
    priceUSD: 4200,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, ArubaOS-CX',
  },

  // ── NVIDIA ───────────────────────────────────────────────────────────────────
  {
    id: 'nvidia-sn5600',
    model: 'NVIDIA Spectrum SN5600',
    vendor: 'NVIDIA',
    subLayer: 'spine',
    ports: 64,
    uplinks: 0,
    speed: '400G',
    asic: 'Spectrum-4',
    powerW: 1550,
    priceUSD: 98000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'RoCEv2', 'RDMA', 'SHARP'],
    useCases: ['gpu', 'dc'],
    detail: '64x400G QSFP-DD, Spectrum-4 ASIC, Cumulus Linux, SHARP in-network compute',
  },
  {
    id: 'nvidia-sn4600c',
    model: 'NVIDIA Spectrum SN4600C',
    vendor: 'NVIDIA',
    subLayer: 'leaf',
    ports: 64,
    uplinks: 8,
    speed: '100G',
    asic: 'Spectrum-3',
    powerW: 750,
    priceUSD: 32000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'RoCEv2', 'RDMA'],
    useCases: ['gpu', 'dc'],
    detail: '64x100G QSFP28 + 8x400G uplinks, Cumulus Linux, RoCEv2-optimized',
  },

  // ── Nokia ────────────────────────────────────────────────────────────────────
  {
    id: 'nokia-srl-7220d3',
    model: 'Nokia 7220 IXR-D3',
    vendor: 'Nokia',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Memory-Marvell',
    powerW: 400,
    priceUSD: 9800,
    features: ['VXLAN', 'EVPN', 'BGP', 'LLDP', 'gNMI'],
    useCases: ['dc', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28, SR Linux, model-driven mgmt',
  },
  {
    id: 'nokia-srl-7250ixr',
    model: 'Nokia 7250 IXR-10',
    vendor: 'Nokia',
    subLayer: 'spine',
    ports: 36,
    uplinks: 0,
    speed: '400G',
    asic: 'FP5',
    powerW: 1100,
    priceUSD: 68000,
    features: ['VXLAN', 'EVPN', 'BGP', 'MPLS', 'SR-MPLS', 'gNMI'],
    useCases: ['dc', 'wan', 'multisite'],
    detail: '36x400G QSFP-DD, FP5 silicon, SR Linux / SR OS, 14.4Tbps',
  },

  // ── Budget / Entry-Level — Cisco ────────────────────────────────────────────
  {
    id: 'nxos-3232c',
    model: 'Nexus 3232C',
    vendor: 'Cisco',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '100G',
    asic: 'Memory-Memory',
    powerW: 450,
    priceUSD: 15000,
    features: ['VXLAN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '32x100G QSFP28, cost-optimised spine, 3.2Tbps',
  },
  {
    id: 'nxos-93108tc',
    model: 'Nexus 93108TC-FX',
    vendor: 'Cisco',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '10G',
    asic: 'Cloud Scale',
    powerW: 380,
    priceUSD: 8500,
    features: ['VXLAN', 'BGP', 'LLDP'],
    useCases: ['dc', 'multisite'],
    detail: '48x10G BASE-T + 6x100G QSFP28 uplinks, 10G copper ToR',
  },
  {
    id: 'cat9300',
    model: 'Catalyst 9300-48UXM',
    vendor: 'Cisco',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 4,
    speed: '10G',
    asic: 'UADP 2.0',
    powerW: 520,
    priceUSD: 9500,
    features: ['SDA', 'VLAN', 'QoS', 'PoE+', 'LLDP', 'MACsec'],
    useCases: ['campus', 'multisite'],
    detail: '48x mGig + 4x10G SFP+, mid-range campus distribution, 490W PoE',
  },
  {
    id: 'isr4331',
    model: 'ISR 4331',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 3,
    uplinks: 0,
    speed: '1G',
    asic: 'QuantumFlow',
    powerW: 150,
    priceUSD: 5500,
    features: ['BGP', 'OSPF', 'IPSec', 'DMVPN'],
    useCases: ['wan', 'multisite'],
    detail: '3x1G, 100Mbps aggregate, branch WAN router',
  },
  {
    id: 'ftd1150',
    model: 'Firepower 1150 NGFW',
    vendor: 'Cisco',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '10G',
    asic: 'x86',
    powerW: 250,
    priceUSD: 12000,
    features: ['IPS', 'AVC', 'TLS-decrypt', 'AMP', 'HA'],
    useCases: ['campus', 'dc', 'multisite'],
    detail: '8x1G + 2x10G, 6Gbps FW throughput, SMB/mid-market NGFW',
  },

  // ── Budget / Entry-Level — Arista ───────────────────────────────────────────
  {
    id: 'arista-7020r',
    model: 'Arista 7020R-48YM',
    vendor: 'Arista',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Memory-memory',
    powerW: 350,
    priceUSD: 9200,
    features: ['VXLAN', 'EVPN', 'BGP', 'LLDP'],
    useCases: ['dc', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28, entry-level DC leaf, EOS',
  },
  {
    id: 'arista-7060x',
    model: 'Arista 7060X4-32',
    vendor: 'Arista',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '400G',
    asic: 'Memory-Memory',
    powerW: 950,
    priceUSD: 48000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '32x400G QSFP-DD, mid-tier spine, 12.8Tbps, EOS',
  },
  {
    id: 'arista-7010t',
    model: 'Arista 7010T-48',
    vendor: 'Arista',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Memory-Memory',
    powerW: 200,
    priceUSD: 5500,
    features: ['VLAN', 'BGP', 'LLDP'],
    useCases: ['dc', 'campus'],
    detail: '48x1G BASE-T + 4x10G SFP+, entry-level access/ToR, EOS',
  },
  {
    id: 'arista-720xp',
    model: 'Arista CCS-720XP-48Y6',
    vendor: 'Arista',
    subLayer: 'access',
    ports: 48,
    uplinks: 6,
    speed: '1G',
    asic: 'Memory-Memory',
    powerW: 380,
    priceUSD: 5800,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 6x25G SFP28 uplinks, campus access, CloudVision',
  },
  {
    id: 'arista-750',
    model: 'Arista CCS-750-24',
    vendor: 'Arista',
    subLayer: 'distribution',
    ports: 24,
    uplinks: 4,
    speed: '25G',
    asic: 'Memory-Memory',
    powerW: 450,
    priceUSD: 14000,
    features: ['VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'dc'],
    detail: '24x25G SFP28 + 4x100G QSFP28 uplinks, campus distribution, EOS',
  },

  // ── Budget / Entry-Level — Juniper ──────────────────────────────────────────
  {
    id: 'juniper-ex4400',
    model: 'EX4400-48T',
    vendor: 'Juniper',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Memory-Memory',
    powerW: 350,
    priceUSD: 5200,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP', 'MACsec', 'VC'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x25G SFP28 uplinks, Virtual Chassis, Junos',
  },
  {
    id: 'juniper-ex4650',
    model: 'EX4650-48Y-AFO',
    vendor: 'Juniper',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Memory-Memory',
    powerW: 480,
    priceUSD: 13000,
    features: ['VXLAN', 'EVPN', 'BGP', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus', 'dc'],
    detail: '48x25G SFP28 + 8x100G QSFP28, campus core/distribution, Junos',
  },
  {
    id: 'juniper-qfx5130',
    model: 'QFX5130-32CD',
    vendor: 'Juniper',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '400G',
    asic: 'Memory-Memory',
    powerW: 900,
    priceUSD: 52000,
    features: ['VXLAN', 'EVPN', 'BGP', 'MPLS', 'PFC'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '32x400G QSFP-DD, 12.8Tbps, Junos Evolved, 400G spine',
  },
  {
    id: 'juniper-srx1500',
    model: 'SRX1500',
    vendor: 'Juniper',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '10G',
    asic: 'x86',
    powerW: 200,
    priceUSD: 8500,
    features: ['IPS', 'UTM', 'AppSecure', 'HA', 'VPN'],
    useCases: ['campus', 'dc', 'wan', 'multisite'],
    detail: '8x1G + 2x10G, 5Gbps FW, SMB/branch NGFW, Junos',
  },
  {
    id: 'juniper-srx4600',
    model: 'SRX4600',
    vendor: 'Juniper',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '40G',
    asic: 'x86 + FPGA',
    powerW: 650,
    priceUSD: 55000,
    features: ['IPS', 'UTM', 'AppSecure', 'HA', 'VPN', 'TLS-decrypt'],
    useCases: ['campus', 'dc', 'multisite', 'multicloud'],
    detail: '8x40G, 80Gbps FW, enterprise/DC NGFW, Junos',
  },
  {
    id: 'juniper-mx204',
    model: 'MX204',
    vendor: 'Juniper',
    subLayer: 'wan-edge',
    ports: 4,
    uplinks: 0,
    speed: '100G',
    asic: 'Memory-Memory',
    powerW: 350,
    priceUSD: 24000,
    features: ['BGP', 'MPLS', 'SR-MPLS', 'OSPF', 'IS-IS', 'L3VPN'],
    useCases: ['wan', 'multisite'],
    detail: '4x100G, 400Gbps, universal edge router, Junos',
  },

  // ── Budget / Entry-Level — Palo Alto ────────────────────────────────────────
  {
    id: 'panos-pa460',
    model: 'PA-460',
    vendor: 'Palo Alto',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '1G',
    asic: 'x86',
    powerW: 120,
    priceUSD: 4500,
    features: ['IPS', 'URL-filter', 'GlobalProtect', 'HA'],
    useCases: ['campus', 'wan'],
    detail: '8x1G + 2x5G, 4.7Gbps FW, SMB branch NGFW',
  },
  {
    id: 'panos-pa3260',
    model: 'PA-3260',
    vendor: 'Palo Alto',
    subLayer: 'firewall',
    ports: 12,
    uplinks: 0,
    speed: '10G',
    asic: 'Cavium',
    powerW: 450,
    priceUSD: 32000,
    features: ['IPS', 'URL-filter', 'GlobalProtect', 'TLS-decrypt', 'HA'],
    useCases: ['campus', 'dc', 'multisite'],
    detail: '12x1G + 4x10G + 4x40G, 60Gbps FW, mid-range NGFW',
  },

  // ── Budget / Entry-Level — Fortinet ─────────────────────────────────────────
  {
    id: 'fortinet-fg100f',
    model: 'FortiGate 100F',
    vendor: 'Fortinet',
    subLayer: 'firewall',
    ports: 18,
    uplinks: 0,
    speed: '1G',
    asic: 'SOC4',
    powerW: 80,
    priceUSD: 3200,
    features: ['IPS', 'SSL-Inspect', 'SD-WAN', 'ZTNA', 'HA'],
    useCases: ['campus', 'wan'],
    detail: '18x1G + 2x10G SFP+, 20Gbps FW, branch/SMB NGFW',
  },
  {
    id: 'fortinet-fg600f',
    model: 'FortiGate 600F',
    vendor: 'Fortinet',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '10G',
    asic: 'NP7',
    powerW: 350,
    priceUSD: 18000,
    features: ['IPS', 'SSL-Inspect', 'SD-WAN', 'ZTNA', 'HA'],
    useCases: ['campus', 'dc', 'multisite'],
    detail: '8x1G + 8x10G + 4x25G, 40Gbps FW + 10Gbps IPS, mid-range',
  },

  // ── Budget / Entry-Level — Dell EMC ─────────────────────────────────────────
  {
    id: 'dell-s5232f',
    model: 'PowerSwitch S5232F-ON',
    vendor: 'Dell EMC',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '100G',
    asic: 'Broadcom Memory-Memory',
    powerW: 550,
    priceUSD: 18000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'SONiC'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '32x100G QSFP28, cost-optimised spine, Dell OS10/SONiC, 3.2Tbps',
  },
  {
    id: 'dell-n3248te',
    model: 'PowerSwitch N3248TE-ON',
    vendor: 'Dell EMC',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Broadcom',
    powerW: 280,
    priceUSD: 4800,
    features: ['VLAN', 'QoS', 'LLDP', 'PoE+'],
    useCases: ['campus', 'dc'],
    detail: '48x1G BASE-T + 4x10G SFP+, entry-level access/ToR, OS10',
  },

  // ── Budget / Entry-Level — HPE Aruba ────────────────────────────────────────
  {
    id: 'aruba-cx6200',
    model: 'Aruba CX 6200 48G',
    vendor: 'HPE Aruba',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Broadcom',
    powerW: 320,
    priceUSD: 2800,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, entry campus, ArubaOS-CX',
  },

  // ── Extreme Networks ──────────────────────────────────────────────────────────
  {
    id: 'extreme-8720',
    model: 'ExtremeSwitching 8720',
    vendor: 'Extreme Networks',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '100G',
    asic: 'Broadcom Trident3',
    powerW: 700,
    priceUSD: 30000,
    features: ['VXLAN', 'EVPN', 'BGP', 'Fabric Connect', 'PFC'],
    useCases: ['dc', 'multisite'],
    detail: '32x100G QSFP28, Switch Engine (EXOS), Fabric Connect / SPB',
  },
  {
    id: 'extreme-8520',
    model: 'ExtremeSwitching 8520',
    vendor: 'Extreme Networks',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 460,
    priceUSD: 13000,
    features: ['VXLAN', 'EVPN', 'BGP', 'Fabric Connect'],
    useCases: ['dc', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28 uplinks, Switch Engine (EXOS)',
  },
  {
    id: 'extreme-5720',
    model: 'ExtremeSwitching 5720',
    vendor: 'Extreme Networks',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 620,
    priceUSD: 16000,
    features: ['VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'dc'],
    detail: '48x25G SFP28 + 8x100G QSFP28 uplinks, Universal Switch Engine',
  },
  {
    id: 'extreme-5420',
    model: 'ExtremeSwitching 5420',
    vendor: 'Extreme Networks',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Broadcom',
    powerW: 410,
    priceUSD: 3900,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, Universal Switch Engine',
  },
]

export const LAYER_PAIRS: Record<UseCase, string[]> = {
  dc: ['spine-leaf'],
  gpu: ['spine-leaf'],
  campus: ['distribution-access', 'core-distribution'],
  wan: ['wan-edge'],
  multisite: ['spine-leaf', 'wan-edge'],
  multicloud: ['cloud-gw', 'cloud-transit'],
  aviatrix: ['cloud-gw', 'cloud-transit'],
  oran: ['oran-fronthaul', 'oran-midhaul', 'oran-core'],
}

export function productsByUseCase(useCase: UseCase): Product[] {
  return PRODUCTS.filter(p => p.useCases.includes(useCase))
}
