import type { Product, UseCase } from '@/types'

export const PRODUCTS: Product[] = [
  // ── Spine / Core ────────────────────────────────────────────────────────────
  {
    id: 'nxos-9336c',
    model: 'Nexus 9336C-FX2',
    vendor: 'Cisco',
    subLayer: 'spine',
    ports: 36,
    uplinks: 0,
    speed: '100G',
    asic: 'Cloud Scale',
    powerW: 650,
    priceUSD: 28000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '36x100G QSFP28, MACsec, CloudScale ASIC, 3.6Tbps',
  },
  {
    id: 'nxos-9364c',
    model: 'Nexus 9364C-GX',
    vendor: 'Cisco',
    subLayer: 'spine',
    ports: 64,
    uplinks: 0,
    speed: '400G',
    asic: 'Cloud Scale GX',
    powerW: 1200,
    priceUSD: 72000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multicloud'],
    detail: '64x400G QSFP-DD, AI/ML optimised, 25.6Tbps',
  },
  {
    id: 'arista-7800r3',
    model: 'Arista 7800R3',
    vendor: 'Arista',
    subLayer: 'spine',
    ports: 48,
    uplinks: 0,
    speed: '400G',
    asic: 'Jericho2+',
    powerW: 1400,
    priceUSD: 95000,
    features: ['VXLAN', 'EVPN', 'BGP', 'MPLS', 'FlowSpec'],
    useCases: ['dc', 'wan', 'multisite', 'multicloud'],
    detail: '48x400G QSFP-DD, segment routing, 19.2Tbps',
  },
  {
    id: 'juniper-qfx10002',
    model: 'QFX10002-72Q',
    vendor: 'Juniper',
    subLayer: 'spine',
    ports: 72,
    uplinks: 0,
    speed: '40G',
    asic: 'Q5',
    powerW: 800,
    priceUSD: 35000,
    features: ['VXLAN', 'EVPN', 'BGP', 'MPLS'],
    useCases: ['dc', 'multisite'],
    detail: '72x40G QSFP+, 2.88Tbps, VC-capable',
  },

  // ── Leaf / ToR ──────────────────────────────────────────────────────────────
  {
    id: 'nxos-93180yc',
    model: 'Nexus 93180YC-FX',
    vendor: 'Cisco',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Cloud Scale',
    powerW: 480,
    priceUSD: 14000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'LLDP'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28 uplinks',
  },
  {
    id: 'nxos-9332c',
    model: 'Nexus 9332C',
    vendor: 'Cisco',
    subLayer: 'leaf',
    ports: 32,
    uplinks: 2,
    speed: '100G',
    asic: 'Cloud Scale',
    powerW: 550,
    priceUSD: 18000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC'],
    useCases: ['dc', 'gpu'],
    detail: '32x100G QSFP28 + 2x100G uplinks, GPU-optimised',
  },
  {
    id: 'arista-7050cx3',
    model: 'Arista 7050CX3-32S',
    vendor: 'Arista',
    subLayer: 'leaf',
    ports: 32,
    uplinks: 2,
    speed: '100G',
    asic: 'Trident3',
    powerW: 460,
    priceUSD: 16000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECMP'],
    useCases: ['dc', 'multisite'],
    detail: '32x100G QSFP28 + 2x100G uplinks, Trident3',
  },
  {
    id: 'juniper-qfx5120',
    model: 'QFX5120-48Y',
    vendor: 'Juniper',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Trident3',
    powerW: 440,
    priceUSD: 12000,
    features: ['VXLAN', 'EVPN', 'BGP', 'LLDP'],
    useCases: ['dc', 'multisite'],
    detail: '48x25G SFP28 + 8x100G QSFP28 uplinks',
  },

  // ── Distribution ────────────────────────────────────────────────────────────
  {
    id: 'cat9500',
    model: 'Catalyst 9500-48Y4C',
    vendor: 'Cisco',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 4,
    speed: '25G',
    asic: 'UADP 3.0',
    powerW: 715,
    priceUSD: 22000,
    features: ['SDA', 'VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'multisite'],
    detail: '48x25G + 4x100G, Cisco SDA-ready',
  },
  {
    id: 'cat9300l',
    model: 'Catalyst 9300L-48T-4G',
    vendor: 'Cisco',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'UADP 2.0',
    powerW: 390,
    priceUSD: 4800,
    features: ['PoE+', 'SDA', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x1G SFP uplinks, 740W PoE budget',
  },
  {
    id: 'cat9200',
    model: 'Catalyst 9200-48P',
    vendor: 'Cisco',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'UADP 2.0 Lite',
    powerW: 370,
    priceUSD: 3200,
    features: ['PoE+', 'QoS', 'LLDP'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x1G SFP uplinks',
  },

  // ── WAN / Edge ───────────────────────────────────────────────────────────────
  {
    id: 'asr1002hx',
    model: 'ASR 1002-HX',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 4,
    uplinks: 0,
    speed: '10G',
    asic: 'QuantumFlow',
    powerW: 280,
    priceUSD: 18000,
    features: ['BGP', 'MPLS', 'OSPF', 'IPSec', 'DMVPN', 'SD-WAN'],
    useCases: ['wan', 'multisite'],
    detail: '4x10G, 60Gbps aggregate, crypto capable',
  },
  {
    id: 'asr9904',
    model: 'ASR 9904',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 8,
    uplinks: 0,
    speed: '100G',
    asic: 'Lightspeed-Plus',
    powerW: 1200,
    priceUSD: 95000,
    features: ['IOS-XR', 'BGP', 'MPLS', 'SR-MPLS', 'L3VPN', 'IS-IS', 'OSPF', 'FlexAlgo'],
    useCases: ['wan', 'multisite'],
    detail: 'IOS-XR SP edge (PE/P), SR-MPLS + L3VPN, 8x100G',
  },
  {
    id: 'ncs540',
    model: 'NCS 540',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 24,
    uplinks: 0,
    speed: '10G',
    asic: 'Qumran',
    powerW: 240,
    priceUSD: 22000,
    features: ['IOS-XR', 'BGP', 'MPLS', 'SR-MPLS', 'L3VPN', 'IS-IS', 'EVPN'],
    useCases: ['wan', 'multisite'],
    detail: 'IOS-XR access/aggregation PE, SR-MPLS + L3VPN, 24x10G',
  },
  {
    id: 'viptela-vedge',
    model: 'Catalyst SD-WAN vEdge 2000',
    vendor: 'Cisco',
    subLayer: 'wan-edge',
    ports: 8,
    uplinks: 0,
    speed: '1G',
    asic: 'Software',
    powerW: 150,
    priceUSD: 9500,
    features: ['SD-WAN', 'BGP', 'IPSec', 'ZTP', 'AppQoE'],
    useCases: ['wan', 'multisite', 'multicloud'],
    detail: '8x1G, SD-WAN ZTP, AppQoE, 20Gbps',
  },

  // ── Aviatrix ────────────────────────────────────────────────────────────────
  {
    id: 'aviatrix-gw',
    model: 'Aviatrix Gateway (c5.xlarge)',
    vendor: 'Aviatrix',
    subLayer: 'cloud-gw',
    ports: 0,
    uplinks: 0,
    speed: '10G',
    asic: 'Software',
    powerW: 0,
    priceUSD: 4200,
    features: ['BGP', 'IPSec', 'SNAT', 'DNAT', 'FireNet', 'TGW'],
    useCases: ['aviatrix', 'multicloud'],
    detail: 'Cloud-native gateway, AWS/Azure/GCP',
  },
  {
    id: 'aviatrix-transit',
    model: 'Aviatrix Transit GW (c5.2xlarge)',
    vendor: 'Aviatrix',
    subLayer: 'cloud-transit',
    ports: 0,
    uplinks: 0,
    speed: '25G',
    asic: 'Software',
    powerW: 0,
    priceUSD: 9800,
    features: ['BGP', 'EVPN', 'Segmentation', 'FireNet', 'TGW'],
    useCases: ['aviatrix', 'multicloud'],
    detail: 'Cloud transit, multi-cloud meshing',
  },

  // ── Firewalls / Security ────────────────────────────────────────────────────
  {
    id: 'ftd4145',
    model: 'Firepower 4145 NGFW',
    vendor: 'Cisco',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '40G',
    asic: 'Liqid',
    powerW: 800,
    priceUSD: 65000,
    features: ['IPS', 'AVC', 'TLS-decrypt', 'AMP', 'HA'],
    useCases: ['campus', 'dc', 'multisite', 'multicloud'],
    detail: '8x40G, 80Gbps FW throughput, HA pair',
  },
  {
    id: 'panos-pa5260',
    model: 'PA-5260 NGFW',
    vendor: 'Palo Alto',
    subLayer: 'firewall',
    ports: 16,
    uplinks: 0,
    speed: '100G',
    asic: 'CN-Series',
    powerW: 1100,
    priceUSD: 120000,
    features: ['IPS', 'URL-filter', 'GlobalProtect', 'TLS-decrypt', 'HA'],
    useCases: ['campus', 'dc', 'multicloud'],
    detail: '16x100G, 200Gbps threat prevention',
  },

  // ── Fortinet ─────────────────────────────────────────────────────────────────
  {
    id: 'fortinet-fg2600f',
    model: 'FortiGate 2600F',
    vendor: 'Fortinet',
    subLayer: 'firewall',
    ports: 8,
    uplinks: 0,
    speed: '40G',
    asic: 'NP7',
    powerW: 750,
    priceUSD: 52000,
    features: ['IPS', 'SSL-Inspect', 'SD-WAN', 'ZTNA', 'HA'],
    useCases: ['campus', 'dc', 'multisite', 'multicloud'],
    detail: '8x40G, 100Gbps FW + 25Gbps IPS, NP7 ASIC, HA pair',
  },
  {
    id: 'fortinet-fst1024e',
    model: 'FortiSwitch T1024E',
    vendor: 'Fortinet',
    subLayer: 'distribution',
    ports: 24,
    uplinks: 4,
    speed: '10G',
    asic: 'Marvell',
    powerW: 285,
    priceUSD: 6800,
    features: ['VLAN', 'QoS', 'LLDP', 'FortiLink', 'MACsec'],
    useCases: ['campus'],
    detail: '24x10G SFP+ + 4x40G QSFP uplinks, FortiLink managed',
  },
  {
    id: 'fortinet-fst148f',
    model: 'FortiSwitch 148F-POE',
    vendor: 'Fortinet',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Marvell',
    powerW: 740,
    priceUSD: 2800,
    features: ['PoE+', 'VLAN', 'QoS', 'FortiLink', 'LLDP'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, 740W PoE budget',
  },

  // ── Dell EMC ─────────────────────────────────────────────────────────────────
  {
    id: 'dell-z9332f',
    model: 'PowerSwitch Z9332F-ON',
    vendor: 'Dell EMC',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '400G',
    asic: 'Broadcom Trident4',
    powerW: 900,
    priceUSD: 38000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'SONiC'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '32x400G QSFP-DD, Dell OS10/SONiC-compatible, 12.8Tbps',
  },
  {
    id: 'dell-s5248f',
    model: 'PowerSwitch S5248F-ON',
    vendor: 'Dell EMC',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 480,
    priceUSD: 11000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN'],
    useCases: ['dc', 'gpu', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28 uplinks, Dell OS10',
  },

  // ── HPE Aruba ────────────────────────────────────────────────────────────────
  {
    id: 'aruba-cx10000',
    model: 'Aruba CX 10000',
    vendor: 'HPE Aruba',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '400G',
    asic: 'Pensando Elba',
    powerW: 1050,
    priceUSD: 45000,
    features: ['VXLAN', 'EVPN', 'BGP', 'Stateful FW', 'DPU'],
    useCases: ['dc', 'campus', 'multisite'],
    detail: '32x400G QSFP-DD, integrated DPU-based stateful firewall, ArubaOS-CX',
  },
  {
    id: 'aruba-cx6400',
    model: 'Aruba CX 6400',
    vendor: 'HPE Aruba',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 680,
    priceUSD: 18000,
    features: ['VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'dc'],
    detail: '48x25G SFP28 + 8x100G QSFP28 uplinks, ArubaOS-CX',
  },
  {
    id: 'aruba-cx6300',
    model: 'Aruba CX 6300M',
    vendor: 'HPE Aruba',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Broadcom',
    powerW: 420,
    priceUSD: 4200,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, ArubaOS-CX',
  },

  // ── NVIDIA ───────────────────────────────────────────────────────────────────
  {
    id: 'nvidia-sn5600',
    model: 'NVIDIA Spectrum SN5600',
    vendor: 'NVIDIA',
    subLayer: 'spine',
    ports: 64,
    uplinks: 0,
    speed: '400G',
    asic: 'Spectrum-4',
    powerW: 1550,
    priceUSD: 98000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'RoCEv2', 'RDMA', 'SHARP'],
    useCases: ['gpu', 'dc'],
    detail: '64x400G QSFP-DD, Spectrum-4 ASIC, Cumulus Linux, SHARP in-network compute',
  },
  {
    id: 'nvidia-sn4600c',
    model: 'NVIDIA Spectrum SN4600C',
    vendor: 'NVIDIA',
    subLayer: 'leaf',
    ports: 64,
    uplinks: 8,
    speed: '100G',
    asic: 'Spectrum-3',
    powerW: 750,
    priceUSD: 32000,
    features: ['VXLAN', 'EVPN', 'BGP', 'PFC', 'ECN', 'RoCEv2', 'RDMA'],
    useCases: ['gpu', 'dc'],
    detail: '64x100G QSFP28 + 8x400G uplinks, Cumulus Linux, RoCEv2-optimized',
  },

  // ── Extreme Networks ──────────────────────────────────────────────────────────
  {
    id: 'extreme-8720',
    model: 'ExtremeSwitching 8720',
    vendor: 'Extreme Networks',
    subLayer: 'spine',
    ports: 32,
    uplinks: 0,
    speed: '100G',
    asic: 'Broadcom Trident3',
    powerW: 700,
    priceUSD: 30000,
    features: ['VXLAN', 'EVPN', 'BGP', 'Fabric Connect', 'PFC'],
    useCases: ['dc', 'multisite'],
    detail: '32x100G QSFP28, Switch Engine (EXOS), Fabric Connect / SPB',
  },
  {
    id: 'extreme-8520',
    model: 'ExtremeSwitching 8520',
    vendor: 'Extreme Networks',
    subLayer: 'leaf',
    ports: 48,
    uplinks: 6,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 460,
    priceUSD: 13000,
    features: ['VXLAN', 'EVPN', 'BGP', 'Fabric Connect'],
    useCases: ['dc', 'multisite'],
    detail: '48x25G SFP28 + 6x100G QSFP28 uplinks, Switch Engine (EXOS)',
  },
  {
    id: 'extreme-5720',
    model: 'ExtremeSwitching 5720',
    vendor: 'Extreme Networks',
    subLayer: 'distribution',
    ports: 48,
    uplinks: 8,
    speed: '25G',
    asic: 'Broadcom Trident3',
    powerW: 620,
    priceUSD: 16000,
    features: ['VXLAN', 'EVPN', 'BGP', 'QoS', 'MACsec'],
    useCases: ['campus', 'dc'],
    detail: '48x25G SFP28 + 8x100G QSFP28 uplinks, Universal Switch Engine',
  },
  {
    id: 'extreme-5420',
    model: 'ExtremeSwitching 5420',
    vendor: 'Extreme Networks',
    subLayer: 'access',
    ports: 48,
    uplinks: 4,
    speed: '1G',
    asic: 'Broadcom',
    powerW: 410,
    priceUSD: 3900,
    features: ['PoE+', 'VLAN', 'QoS', 'LLDP', 'MACsec'],
    useCases: ['campus'],
    detail: '48x1G PoE+ + 4x10G SFP uplinks, Universal Switch Engine',
  },
]

export const LAYER_PAIRS: Record<UseCase, string[]> = {
  dc: ['spine-leaf'],
  gpu: ['spine-leaf'],
  campus: ['distribution-access', 'core-distribution'],
  wan: ['wan-edge'],
  multisite: ['spine-leaf', 'wan-edge'],
  multicloud: ['cloud-gw', 'cloud-transit'],
  aviatrix: ['cloud-gw', 'cloud-transit'],
}

export function productsByUseCase(useCase: UseCase): Product[] {
  return PRODUCTS.filter(p => p.useCases.includes(useCase))
}
