import type { Compliance } from '@/types'

export type ScanType = 'compliance' | 'drift' | 'both'
export type ScanAction = 'report' | 'remediate' | 'alert'

export interface WatcherConfig {
  id: string
  name: string
  scanType: ScanType
  intervalMinutes: number
  frameworks: Compliance[]
  action: ScanAction
  enabled: boolean
  notifyEmail: string
  scope: 'all' | 'drifted'
}

export interface ScanHistoryEntry {
  id: string
  watcherId: string
  watcherName: string
  scanType: ScanType
  timestamp: string
  durationMs: number
  complianceScore: number | null
  driftCount: number | null
  deviceCount: number
  status: 'ok' | 'warn' | 'fail'
  detail: string
}

export const INTERVAL_PRESETS: Array<{ label: string; minutes: number }> = [
  { label: 'Every 15 min', minutes: 15 },
  { label: 'Every hour', minutes: 60 },
  { label: 'Every 4 hours', minutes: 240 },
  { label: 'Every 12 hours', minutes: 720 },
  { label: 'Daily', minutes: 1440 },
  { label: 'Weekly', minutes: 10080 },
]

let nextId = 1
export function createWatcher(partial: Partial<WatcherConfig> = {}): WatcherConfig {
  const id = `watcher-${nextId++}`
  return {
    id,
    name: partial.name ?? 'Untitled Watcher',
    scanType: partial.scanType ?? 'both',
    intervalMinutes: partial.intervalMinutes ?? 60,
    frameworks: partial.frameworks ?? [],
    action: partial.action ?? 'report',
    enabled: partial.enabled ?? true,
    notifyEmail: partial.notifyEmail ?? '',
    scope: partial.scope ?? 'all',
  }
}

function intervalToCron(minutes: number): string {
  if (minutes < 60) return `*/${minutes} * * * *`
  const h = Math.floor(minutes / 60)
  if (h < 24) return `0 */${h} * * *`
  const d = Math.floor(h / 24)
  if (d === 7) return '0 2 * * 0'
  return `0 2 */${d} * *`
}

export function exportCronTab(watchers: WatcherConfig[]): string {
  const lines = [
    '# NetDesign AI — Scheduled Compliance & Drift Scans',
    '# Generated by the Scheduled Scans watcher config',
    '# Install: crontab -e  (paste these lines)',
    '',
    'SHELL=/bin/bash',
    'PATH=/usr/local/bin:/usr/bin:/bin',
    'MAILTO=""',
    '',
  ]
  for (const w of watchers.filter(w => w.enabled)) {
    const cron = intervalToCron(w.intervalMinutes)
    const scanFlag = w.scanType === 'compliance' ? '--compliance-only'
      : w.scanType === 'drift' ? '--drift-only'
      : '--compliance --drift'
    const fwFlag = w.frameworks.length > 0 ? ` --frameworks ${w.frameworks.join(',')}` : ''
    const actionFlag = ` --action ${w.action}`
    const scopeFlag = w.scope === 'drifted' ? ' --scope drifted' : ''
    const mailFlag = w.notifyEmail ? ` --notify ${w.notifyEmail}` : ''
    lines.push(`# ${w.name} (${w.id})`)
    lines.push(`${cron}  /opt/netdesign/bin/scan-runner ${scanFlag}${fwFlag}${actionFlag}${scopeFlag}${mailFlag}`)
    lines.push('')
  }
  return lines.join('\n')
}

export function exportSystemdTimer(watcher: WatcherConfig): { timer: string; service: string } {
  const sec = watcher.intervalMinutes * 60
  const scanFlag = watcher.scanType === 'compliance' ? '--compliance-only'
    : watcher.scanType === 'drift' ? '--drift-only'
    : '--compliance --drift'
  const fwFlag = watcher.frameworks.length > 0 ? ` --frameworks ${watcher.frameworks.join(',')}` : ''
  const actionFlag = ` --action ${watcher.action}`
  const scopeFlag = watcher.scope === 'drifted' ? ' --scope drifted' : ''
  const mailFlag = watcher.notifyEmail ? ` --notify ${watcher.notifyEmail}` : ''

  const timer = [
    '[Unit]',
    `Description=NetDesign AI scan timer — ${watcher.name}`,
    '',
    '[Timer]',
    `OnBootSec=120`,
    `OnUnitActiveSec=${sec}`,
    'AccuracySec=60',
    '',
    '[Install]',
    'WantedBy=timers.target',
  ].join('\n')

  const service = [
    '[Unit]',
    `Description=NetDesign AI scan — ${watcher.name}`,
    '',
    '[Service]',
    'Type=oneshot',
    `ExecStart=/opt/netdesign/bin/scan-runner ${scanFlag}${fwFlag}${actionFlag}${scopeFlag}${mailFlag}`,
    'TimeoutStartSec=300',
    'StandardOutput=journal',
    'StandardError=journal',
  ].join('\n')

  return { timer, service }
}

export function exportScanScript(_watchers: WatcherConfig[]): string {
  const lines = [
    '#!/usr/bin/env bash',
    '# NetDesign AI — scan-runner wrapper',
    '# Usage: scan-runner [--compliance-only|--drift-only|--compliance --drift]',
    '#        [--frameworks PCI,SOC2] [--action report|remediate|alert]',
    '#        [--scope all|drifted] [--notify email@example.com]',
    '',
    'set -euo pipefail',
    '',
    'SCAN_TYPE="both"',
    'FRAMEWORKS=""',
    'ACTION="report"',
    'SCOPE="all"',
    'NOTIFY=""',
    '',
    'while [[ $# -gt 0 ]]; do',
    '  case "$1" in',
    '    --compliance-only) SCAN_TYPE="compliance"; shift ;;',
    '    --drift-only) SCAN_TYPE="drift"; shift ;;',
    '    --compliance) SCAN_TYPE="both"; shift ;;',
    '    --drift) SCAN_TYPE="both"; shift ;;',
    '    --frameworks) FRAMEWORKS="$2"; shift 2 ;;',
    '    --action) ACTION="$2"; shift 2 ;;',
    '    --scope) SCOPE="$2"; shift 2 ;;',
    '    --notify) NOTIFY="$2"; shift 2 ;;',
    '    *) echo "Unknown option: $1"; exit 1 ;;',
    '  esac',
    'done',
    '',
    'LOG_DIR="/var/log/netdesign/scans"',
    'mkdir -p "$LOG_DIR"',
    'TIMESTAMP=$(date +%Y%m%d-%H%M%S)',
    'LOG_FILE="$LOG_DIR/scan-$TIMESTAMP.log"',
    '',
    'echo "=== NetDesign AI Scan — $TIMESTAMP ===" | tee "$LOG_FILE"',
    'echo "Type: $SCAN_TYPE | Frameworks: ${FRAMEWORKS:-all} | Action: $ACTION | Scope: $SCOPE" | tee -a "$LOG_FILE"',
    '',
    'if [[ "$SCAN_TYPE" != "drift" ]]; then',
    '  echo "--- Running compliance scan ---" | tee -a "$LOG_FILE"',
    '  # Call the NetDesign API or local compliance-scan CLI',
    '  curl -sS -X POST http://localhost:8000/api/compliance/scan \\',
    '    -H "Content-Type: application/json" \\',
    '    -d "{\\"frameworks\\": \\"${FRAMEWORKS:-all}\\"}" \\',
    '    | tee -a "$LOG_FILE"',
    '  echo "" | tee -a "$LOG_FILE"',
    'fi',
    '',
    'if [[ "$SCAN_TYPE" != "compliance" ]]; then',
    '  echo "--- Running drift check ---" | tee -a "$LOG_FILE"',
    '  curl -sS -X POST http://localhost:8000/api/drift/config \\',
    '    -H "Content-Type: application/json" \\',
    '    -d "{\\"scope\\": \\"$SCOPE\\"}" \\',
    '    | tee -a "$LOG_FILE"',
    '  echo "" | tee -a "$LOG_FILE"',
    '',
    '  if [[ "$ACTION" == "remediate" ]]; then',
    '    echo "--- Auto-remediating drifted devices ---" | tee -a "$LOG_FILE"',
    '    curl -sS -X POST http://localhost:8000/api/drift/remediate \\',
    '      -H "Content-Type: application/json" \\',
    '      -d "{\\"scope\\": \\"$SCOPE\\", \\"auto_apply\\": true}" \\',
    '      | tee -a "$LOG_FILE"',
    '    echo "" | tee -a "$LOG_FILE"',
    '  fi',
    'fi',
    '',
    'if [[ -n "$NOTIFY" ]]; then',
    '  echo "--- Sending notification to $NOTIFY ---" | tee -a "$LOG_FILE"',
    '  # Placeholder: integrate with your alerting stack (PagerDuty, Slack, email)',
    '  echo "Notification sent to $NOTIFY" | tee -a "$LOG_FILE"',
    'fi',
    '',
    'echo "=== Scan complete ===" | tee -a "$LOG_FILE"',
  ]
  return lines.join('\n')
}

export function simulateScanHistory(
  watchers: WatcherConfig[],
  deviceCount: number,
  count: number = 12,
): ScanHistoryEntry[] {
  const entries: ScanHistoryEntry[] = []
  const now = Date.now()
  const enabled = watchers.filter(w => w.enabled)
  if (enabled.length === 0 || deviceCount === 0) return entries

  for (let i = 0; i < count; i++) {
    const w = enabled[i % enabled.length]
    const hoursAgo = i * (w.intervalMinutes / 60) + 0.5
    const ts = new Date(now - hoursAgo * 3600_000)

    const hasDrift = i % 5 === 2 || i % 7 === 3
    const compScore = w.scanType !== 'drift'
      ? 70 + ((i * 7 + 13) % 31)
      : null
    const dCount = w.scanType !== 'compliance'
      ? (hasDrift ? 1 + (i % 3) : 0)
      : null

    const status: ScanHistoryEntry['status'] =
      (dCount !== null && dCount > 0) ? 'warn'
      : (compScore !== null && compScore < 80) ? 'warn'
      : 'ok'

    let detail: string
    if (w.scanType === 'compliance') {
      detail = compScore !== null && compScore < 80
        ? `Compliance score ${compScore}% — review required`
        : `Compliance score ${compScore}% — all clear`
    } else if (w.scanType === 'drift') {
      detail = dCount && dCount > 0
        ? `${dCount} device(s) drifted`
        : 'No drift detected'
    } else {
      const parts: string[] = []
      if (compScore !== null) parts.push(`compliance ${compScore}%`)
      if (dCount !== null && dCount > 0) parts.push(`${dCount} drifted`)
      else if (dCount !== null) parts.push('no drift')
      detail = parts.join(' · ')
    }

    entries.push({
      id: `scan-${i}`,
      watcherId: w.id,
      watcherName: w.name,
      scanType: w.scanType,
      timestamp: ts.toISOString(),
      durationMs: 800 + ((i * 31) % 4200),
      complianceScore: compScore,
      driftCount: dCount,
      deviceCount,
      status,
      detail,
    })
  }
  return entries
}

export function watcherSummaryText(watchers: WatcherConfig[]): string {
  const enabled = watchers.filter(w => w.enabled)
  if (enabled.length === 0) return 'No active watchers'
  const parts = enabled.map(w => {
    const preset = INTERVAL_PRESETS.find(p => p.minutes === w.intervalMinutes)
    const interval = preset?.label ?? `Every ${w.intervalMinutes}m`
    return `${w.name}: ${w.scanType} scan ${interval} → ${w.action}`
  })
  return parts.join('\n')
}
